### ISSUE TITLE
Issue when using widgets in the home screen

### ISSUE THREAD

**Issue by Nuklear92** [Tikipeter/repository.tikipeter#635] opened 2021-11-10 17:20 UTC
I recorded a clip reproducing the issue which I'll leave down below. Okay, when setting up FEN widgets in the Home Screen, when you go into the SS UI from an Episode/Movie and you back out without selecting any links the screen stays frozen with a **Busy...** spinning wheel. Usually it's supposed to let you scroll again maybe after one sec. However it just stays there spinning unless you manually hit the back button of the remote in my case using an Nvidia Shield TV. I already tried setting up Venom widgets in the Home Screen as well and it works no problem when you get into the SS UI and back out without selecting/resolving any links it lets you scroll the Home screen widgets instantly, same with Seren widgets. So, my guess is it might have to do with FEN's Source Select UI when you back out of it without selecting any links while using widgets in the Home Screen. 🤔

I'll leave a log here too, however I don't think it might be of any use since nothing prompted errors just that the screen stays frozen with the busy spinning wheel on top.

https://paste.kodi.tv/megaqevazu

**Heres the clip showing the issue**

https://streamable.com/bwv90w

**Comment by Tikipeter** [comment] 2021-11-10 21:13
I've been putting up with that for a while myself. I might have a quick chat to the Venom dev and see what he's doing. I know why it happens (stupid Kodi), but I need to be careful of force closing dialogs when the SS is closed as someone might have an Extras window underneath it. Hopefully a simple busy dialog close command will do.

The problem is on my coding machine (windows) I don't have this issue. The busy dialog is there for at most half a second when I exit SS, and then it goes away by itself like it should. So it's harder than it should be to pop in a bit of code and see if it works. I need to zip up the addon and install it on one of my other machines just to do a 5 second test to see if the one line of code I added works or not. :)

I need to push an update in 24 hours, so hopefully there's a fix for this by then. Otherwise it will be in the next update after that.

**Comment by omaramiromo** [comment] 2021-11-12 01:09
It happen to me too. I just push back button again when busy dialogue shows and it will gone immediately

**Comment by Tikipeter** [comment] 2021-11-16 16:21
Still struggling with this I'm afraid, but I certainly haven't forgotten about it...

**Comment by Nuklear92** [comment] 2021-11-17 04:54
No worries, take your time. 🙂👍

**Comment by acf150** [comment] 2021-11-20 22:02
I love your addon one of the best if not the best around. I haven't been using it because I've been reading about issues installing it with the url? Has this been taken care of? Thank you for all you do and for such a great addon. 🙏

**Comment by Tikipeter** [comment] 2021-11-23 17:12
Should be fixed for next update. We won't worry about the stupid reason why it wasn't working before. :) :)

**Closed** 2021-11-23 19:36 UTC
Labels: bug, pending update
