### ISSUE TITLE
No Easynews results

### ISSUE THREAD

**Issue by omen124** [Tikipeter/repository.tikipeter#310] opened 2020-11-14 00:39 UTC
I have been trying over the last few weeks with 3 separate installs of FEN to get results when searching with the 3.0 build of EasyNews. There are results via its website, but FEN is not returning any results.
Is there any particular log you will prefer, PC or Firestick 4K, or the Debug mode from FEN?
If needed I will provide account access again for you to investigate.

**Comment by Tikipeter** [comment] 2020-11-14 15:03
I'll need to make a test build with some logging when I get home.

**Comment by Tikipeter** [comment] 2020-11-14 22:16
Here's a version I'll need you to install that will hopefully log for me what's being returned by Easynews when the call is made.
No need to turn on debugging or anything.
Testing on the PC would be best, simply because it's easy to get the log file from it. Either device is fine though.
Test a search or two (both using the scraper and searching from "My Services"). Grab the log and post it here.
Hopefully we won't have to use your account again, that is a last resort.

[plugin.video.fen-1.8.18c-test1.zip](https://github.com/Tikipeter/repository.tikipeter/files/5541520/plugin.video.fen-1.8.18c-test1.zip)

BTW, when you go to the v3 webpage for Easynews, does it look the same as it always has? I'm thinking/hoping they've just changed the layout slightly, and that's where the issue is coming from.

**Comment by omen124** [comment] 2020-11-15 03:04
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5541775/kodi.log)
The my services does not return results, when choosing a TV show of movie and then selecting an episode, no result is found and they definitely are available online.
The EasyNews website hasn't changed its interface (didn't see any changes)

**Comment by omen124** [comment] 2020-11-15 03:05
You already have my email address, send me another email if you want the updated password for testing on your end.

**Comment by djdirty60** [comment] 2020-11-15 14:56
> I check GAIA which updated their addon recently, what version is there now?  Because I still have the 5.6.0 version.

**Comment by omen124** [comment] 2020-11-15 15:05
> > I check GAIA which updated their addon recently, what version is there now?  Because I still have the 5.6.0 version.

5.6.0 seems to be the latest update I am talking about which released the Easynews 3.0 functionality

**Comment by Tikipeter** [comment] 2020-11-16 16:00
Can you confirm for me that Gaia is definitely providing results for you.

Gaia is using the v2 web address for queries, but differs from Fen by utilizing cookies, whereas Fen sends the user/pass in the headers.

 `....which released the Easynews 3.0 functionality` <=== Are you sure this happened recently? Gaia's Changelog says 5.6.0 was released one year ago (17th November 2019). If that's true then Easynews should have been working in Gaia all year.

I will (begrudingly, because I don't like using cookies) implement cookies if you are 100% sure Gaia is giving you results. This would likely remove the need to have a setting for v2/v3 in Fen as well, since they will use the same endpoint.

I just need confirmation that Gaia 5.6.0 is DEFINITELY working with Easynews.

**Comment by Tikipeter** [comment] 2020-11-16 23:38
I don't know what to make of it to be honest. There's no update past 5.6.0 12 months ago.

I suppose trying cookies is worth the chance.

I'll post up a test zip here when I've got it done, but it's a re-write so it might be a day or two.

**Comment by Aguzy** [comment] 2020-11-18 15:44
I don't know if it would make any difference but I seen they were changing to https only on the 16th of November, my easynews stopped working round about this time through the addon. I know nothing about this sort of thing but just wonder if a change like that could affect the addon

**Comment by Aguzy** [comment] 2020-11-18 23:19
Scratch my last comment, I turned it onto version 2 from 3 just on the off chance it might work and it did. Always worked with version 3 before

**Comment by Tikipeter** [comment] 2020-11-19 15:04
@Aguzy , is it still working by using the v2 setting instead of v3?

If this is the case, @omen124  can you switch to v2 in settings, clear Internal Sources Cache, and check if it works.

**Comment by Aguzy** [comment] 2020-11-19 16:03
@Tikipeter it is mate, I tried it on 2 different devices and works on both on v2

**Comment by omen124** [comment] 2020-11-19 19:50
> @Aguzy , is it still working by using the v2 setting instead of v3?
> 
> If this is the case, @omen124 can you switch to v2 in settings, clear Internal Sources Cache, and check if it works.

I switched it over to v2 and I wasn't sure about the Internal Sources Cache thing (checked all of the easy news settings and couldn't see that). So I tried a search and found some content and it was playing with the v2 setting.

Outside of FEN/Kodi I did some checking on the back end of Easynews.
The 3.0 page https://members-beta.easynews.com/3.0/ is still where I land when I log in and can perform searches there manually and they work.
Meanwhile, the vintage search at https://members.easynews.com/ now doesn't force a redirect to 3.0 anymore. So it seems that the 2.0 search in FEN and GAIA (I am guessing if your non-update statement for 3.0 is true) is working because of now having access to the vintage search.

I wouldn't write off 3.0 yet as they will likely eventually force everyone onto it. But in the meantime, it looks like vintage (Not sure if this is 2.0 or not) is working.

**Comment by Tikipeter** [comment] 2020-11-20 03:41
Good news.

I will close this issue because using v2 is working for now.

I definitely agree with you about not giving up on v3. They could switch back to using that only at any time. I'd be interested to know why they stopped forcing the redirect from v2-v3 webpage.

In saying that, I also don't want to half re-write the v3 code to use cookies if I can get away with not doing it. So, for now, let's all just enjoy v2 together and hopefully they keep it that way.

Let me know here immediately if it stops working again on v2 (if that happens, check again with v3 as well).

In more good news, I just tried to browse to the v3 webpage with my "old" Easynews account, and it didn't redirect me to v2. That's really good news because as it stands right now, I would be able to use my own account for any testing/fixing.

**Closed by Tikipeter** 2020-11-20 03:41 UTC
Labels: bug
