### ISSUE TITLE
Request & Issue

### ISSUE THREAD

**Issue by techecoyote** [Tikipeter/repository.tikipeter#30] opened 2019-09-22 08:47 UTC
Outstanding job with FEN. Quick & efficient. Would it be too much trouble to add numbers to the
searched links? Reason being, if you start in the found links & it fails, it could go through a few more & just return. So I don't know where it last left off. Other than trying to follow all the providers names, which is very difficult, it would be easier if they had numbers too... Thanx for the time....
GREAT Work!!!

Tikiscrapers gives an error when clicking, Clear Cache Results, Yes, Error clearing results cache...

**Comment by Tikipeter** [comment] 2019-09-22 23:25
Hi techcoyote.

I should be able to add numbering to the resolve dialog. I'll let you know here if I run into troubles and can't do it, otherwise it will be in the next update. It's bugged me for a while too. :)

As for the Tikiscrapers error, I cannot replicate that. It works fine for me. If you want to you can attach a log of it happening and I'll look into it. :)

**Comment by techecoyote** [comment] 2019-09-23 19:09
Thanx for the update.. Hope this help.

Here's the log..
14:58:35.226 T:12580   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=Results%20Display&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Results%20Display%20Settings.&list_name=Settings%20Results%20Display&mode=open_settings&query=4.0
14:58:35.227 T:12580   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=Results%20Display&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Results%20Display%20Settings.&list_name=Settings%20Results%20Display&mode=open_settings&query=4.0) failed
14:58:35.785 T:12580   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
15:00:58.046 T:12580   ERROR: Previous line repeats 1 times.
15:00:58.046 T:12580   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=General&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20General%20Settings.&list_name=Settings%20General&mode=open_settings&query=0.0
15:00:58.047 T:12580   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=General&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20General%20Settings.&list_name=Settings%20General&mode=open_settings&query=0.0) failed
15:00:58.184 T:12580   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
15:01:54.791 T:13196  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:0c8b541e-ceb7-43a2-aa44-503745dc242a" for service "urn:upnp-org:serviceId:ConnectionManager" of device "DELL-2: Dell User:" (timeout = 300)
15:01:59.780 T:13240  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:f1386fee-7d0d-4a2d-a823-09018b1dcae4" for service "urn:upnp-org:serviceId:ContentDirectory" of device "DELL-2: Dell User:" (timeout = 300)
15:03:21.460 T:12580   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
15:03:28.118 T:12580   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=External%20Scraper&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20External%20Scraper%20Settings.&list_name=Settings%20External%20Scraper&mode=open_settings&query=6.0
15:03:28.119 T:12580   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=External%20Scraper&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20External%20Scraper%20Settings.&list_name=Settings%20External%20Scraper&mode=open_settings&query=6.0) failed
15:03:41.167 T:12580   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?ext_addon=script.module.tikiscrapers&foldername=Tiki%20Scraper%20Settings&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Tiki%20Scraper%20Settings.&list_name=Settings%20Tiki%20Scraper%20Settings&mode=external_settings
15:03:41.168 T:12580   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?ext_addon=script.module.tikiscrapers&foldername=Tiki%20Scraper%20Settings&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Tiki%20Scraper%20Settings.&list_name=Settings%20Tiki%20Scraper%20Settings&mode=external_settings) failed
15:03:44.286 T:12580   ERROR: ADDON: extension '' is not currently supported for service addon
15:03:57.321 T:12580   ERROR: Previous line repeats 9 times.
15:03:57.321 T:12580   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
15:03:57.321 T:12580   ERROR: Control 200 in window 10146 has been asked to focus, but it can't
15:05:24.829 T:6132  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:0c8b541e-ceb7-43a2-aa44-503745dc242a" for service "urn:upnp-org:serviceId:ConnectionManager" of device "DELL-2: Dell User:" (timeout = 300)
15:05:29.818 T:4148  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:f1386fee-7d0d-4a2d-a823-09018b1dcae4" for service "urn:upnp-org:serviceId:ContentDirectory" of device "DELL-2: Dell User:" (timeout = 300)
15:05:31.522 T:12580   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
15:06:08.062 T:12808  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
15:06:09.103 T:9496   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi176\portable_data\userdata\addon_data\plugin.video.fen\TV Show Downloads\
15:07:16.384 T:12580   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?ext_addon=script.module.tikiscrapers&foldername=Tiki%20Scraper%20Settings&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Tiki%20Scraper%20Settings.&list_name=Settings%20Tiki%20Scraper%20Settings&mode=external_settings
15:07:16.385 T:12580   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?ext_addon=script.module.tikiscrapers&foldername=Tiki%20Scraper%20Settings&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20Tiki%20Scraper%20Settings.&list_name=Settings%20Tiki%20Scraper%20Settings&mode=external_settings) failed

**Comment by techecoyote** [comment] 2019-09-23 19:18
The above is the normal KODI Log. Here is the Full DEBUG of KOD.

15:14:03.342 T:4888    INFO: Previous line repeats 11 times.
15:14:03.342 T:4888   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
15:14:03.342 T:4888   DEBUG: XFILE::CPluginDirectory::RunScriptWithParams - calling plugin Tiki Scrapers Module('plugin://script.module.tikiscrapers/','-1','?mode=TikiScraperSettings')
15:14:03.343 T:10336   DEBUG: Thread LanguageInvoker start, auto delete: false
15:14:03.343 T:10336    INFO: initializing python engine.
15:14:03.343 T:10336   DEBUG: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): start processing
15:14:03.355 T:4888   DEBUG: ------ Window Init (Pointer.xml) ------
15:14:03.372 T:10336   DEBUG: -->Python Interpreter Initialized<--
15:14:03.372 T:10336   DEBUG: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): the source file to load is "C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py"
15:14:03.372 T:10336   DEBUG: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): setting the Python path to C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib;C:\Program Files\Kodi176\portable_data\addons\script.module.beautifulsoup4\lib;C:\Program Files\Kodi176\system\python\DLLs;C:\Program Files\Kodi176\system\python\Lib;C:\Program Files\Kodi176\python27.zip;C:\Program Files\Kodi176\system\python\lib\plat-win;C:\Program Files\Kodi176\system\python\lib\lib-tk;C:\Program Files\Kodi176;C:\Program Files\Kodi176\system\python;C:\Program Files\Kodi176\system\python\lib\site-packages
15:14:03.372 T:10336   DEBUG: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): entering source directory C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib
15:14:03.372 T:10336   DEBUG: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): instantiating addon using automatically obtained id of "script.module.tikiscrapers" dependent on version 2.1.0 of the xbmc.python api
15:14:03.495 T:4888   DEBUG: ------ Window Deinit (DialogAddonSettings.xml) ------
15:14:03.606 T:10336    INFO: CPythonInvoker(58, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): script successfully run
15:14:03.637 T:4888   DEBUG: ------ Window Init (DialogAddonSettings.xml) ------
15:14:03.638 T:4888   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
15:14:03.638 T:4888   ERROR: Control 200 in window 10146 has been asked to focus, but it can't
15:14:03.639 T:12964   DEBUG: Thread JobWorker start, auto delete: true
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=d8 avail_size_in_buf=14177
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 0 bytes (0 bits)
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=fe avail_size_in_buf=14175
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 16 bytes (128 bits)
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=db avail_size_in_buf=14157
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] index=0
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] qscale[0]: 2
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 67 bytes (536 bits)
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=c4 avail_size_in_buf=14088
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] class=0 index=0 nb_codes=12
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] class=0 index=1 nb_codes=12
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] class=1 index=0 nb_codes=251
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] class=1 index=1 nb_codes=251
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 418 bytes (3344 bits)
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=c0 avail_size_in_buf=13668
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] Changing bps from 0 to 8
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] sof0: picture: 256x256
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component 0 2:2 id: 0 quant:0
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component 1 1:1 id: 1 quant:0
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component 2 1:1 id: 2 quant:0
15:14:03.641 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] pix fmt id 22111100
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 17 bytes (136 bits)
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] escaping removed 135 bytes
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=da avail_size_in_buf=13649
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component: 0
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component: 1
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] component: 2
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker parser used 13513 bytes (108100 bits)
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] marker=d9 avail_size_in_buf=0
15:14:03.642 T:12964   DEBUG: ffmpeg[32A4]: [mjpeg] decode frame unused 0 bytes
15:14:03.700 T:10336    INFO: Python script stopped
15:14:03.700 T:10336   DEBUG: Thread LanguageInvoker 10336 terminating
15:14:05.370 T:9512   DEBUG: [plugin.video.youtube] HTTPServer: Request uri path |/ping|
15:14:05.370 T:9512   DEBUG: [plugin.video.youtube] HTTPServer: Connection from |127.0.0.1| Local range: |True|
15:14:05.372 T:3108   DEBUG: [plugin.video.youtube] HTTPServer: Ping |127.0.0.1:50152| |204|
15:14:07.468 T:8240    INFO: Platinum [platinum.core.ctrlpoint]: Device "ATV_134" expiration time renewed..
15:14:09.508 T:4888    INFO: Previous line repeats 11 times.
15:14:09.508 T:4888   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
15:14:09.508 T:4888   DEBUG: XFILE::CPluginDirectory::RunScriptWithParams - calling plugin Tiki Scrapers Module('plugin://script.module.tikiscrapers/','-1','?mode=clearProviderCache')
15:14:09.509 T:12452   DEBUG: Thread LanguageInvoker start, auto delete: false
15:14:09.509 T:12452    INFO: initializing python engine.
15:14:09.509 T:12452   DEBUG: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): start processing
15:14:09.537 T:12452   DEBUG: -->Python Interpreter Initialized<--
15:14:09.538 T:12452   DEBUG: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): the source file to load is "C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py"
15:14:09.538 T:12452   DEBUG: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): setting the Python path to C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib;C:\Program Files\Kodi176\portable_data\addons\script.module.beautifulsoup4\lib;C:\Program Files\Kodi176\system\python\DLLs;C:\Program Files\Kodi176\system\python\Lib;C:\Program Files\Kodi176\python27.zip;C:\Program Files\Kodi176\system\python\lib\plat-win;C:\Program Files\Kodi176\system\python\lib\lib-tk;C:\Program Files\Kodi176;C:\Program Files\Kodi176\system\python;C:\Program Files\Kodi176\system\python\lib\site-packages
15:14:09.538 T:12452   DEBUG: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): entering source directory C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib
15:14:09.538 T:12452   DEBUG: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): instantiating addon using automatically obtained id of "script.module.tikiscrapers" dependent on version 2.1.0 of the xbmc.python api
15:14:09.574 T:4888   DEBUG: ------ Window Init (DialogConfirm.xml) ------
15:14:09.677 T:4888   DEBUG: ------ Window Deinit (DialogAddonSettings.xml) ------
15:14:12.445 T:4888   DEBUG: CInputManager::ProcessMouse: trying mouse action leftclick
15:14:12.602 T:4888   DEBUG: ------ Window Deinit (DialogConfirm.xml) ------
15:14:12.929 T:4888   DEBUG: ------ Window Init (DialogNotification.xml) ------
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=d8 avail_size_in_buf=19131
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 0 bytes (0 bits)
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=e0 avail_size_in_buf=19129
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 16 bytes (128 bits)
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=e1 avail_size_in_buf=19111
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 161 bytes (1288 bits)
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=db avail_size_in_buf=18947
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] index=0
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] qscale[0]: 1
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 67 bytes (536 bits)
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=db avail_size_in_buf=18878
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] index=1
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] qscale[1]: 1
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 67 bytes (536 bits)
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=c0 avail_size_in_buf=18809
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] Changing bps from 0 to 8
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] sof0: picture: 256x256
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component 0 2:2 id: 0 quant:0
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component 1 1:1 id: 1 quant:1
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component 2 1:1 id: 2 quant:1
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] pix fmt id 22111100
15:14:12.933 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 17 bytes (136 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=c4 avail_size_in_buf=18790
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] class=0 index=0 nb_codes=12
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 31 bytes (248 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=c4 avail_size_in_buf=18757
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] class=1 index=0 nb_codes=251
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 181 bytes (1448 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=c4 avail_size_in_buf=18574
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] class=0 index=1 nb_codes=12
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 31 bytes (248 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=c4 avail_size_in_buf=18541
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] class=1 index=1 nb_codes=251
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 181 bytes (1448 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] escaping removed 179 bytes
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=da avail_size_in_buf=18358
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component: 0
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component: 1
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] component: 2
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker parser used 18178 bytes (145421 bits)
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] marker=d9 avail_size_in_buf=0
15:14:12.934 T:4888   DEBUG: ffmpeg[1318]: [mjpeg] decode frame unused 0 bytes
15:14:13.130 T:12452    INFO: CPythonInvoker(59, C:\Program Files\Kodi176\portable_data\addons\script.module.tikiscrapers\lib\default.py): script successfully run

**Comment by techecoyote** [comment] 2019-09-23 19:21
From what I can see, In the full debug log, it doesn't show an error. In the normal KODI log it does, interesting....
Here's a pic, if it helps...

![screenshot000](https://user-images.githubusercontent.com/30167562/65455740-d58d5680-de15-11e9-9f9d-f8eeee59a460.png)

**Comment by Tikipeter** [comment] 2019-09-23 21:16
Thanks for the info techecoyote.

The log doesn't show the reason for the error, so I'll push an update to Tikiscrapers with some logging info that should catch why it's erroring. If you have the time, could you post another log here after the update?

Oh, make sure you have Tikiscrapers Version 1.1.13 as well. There was a change to the cache clearing function in that update. If you don't have 1.1.13, that is likely the issue...

**Comment by techecoyote** [comment] 2019-09-23 22:20
Thank you for the update... FYI, since I've installed Fen, long time ago, the error in tikiscrapers has always been there. I do have 1.1.14... But will keep you updated. Do you have a Telegram account? Just wondering. Thanx again!!!

**Comment by Tikipeter** [comment] 2019-09-23 22:42
I don't have a telegram account, no.

Interesting that it's always happened. I've just pushed an update for Tikiscrapers (and Fen), hopefully a new log will show the error. It can surely only be a couple of things.....

**Comment by techecoyote** [comment] 2019-09-23 23:54
Thank you for the update... FYI, since I've installed Fen, long time ago, the error in tikiscrapers has always been there. I do have 1.1.14... But will keep you updated. Do you have a Telegram account? Just wondering. Thanx again!!!

**Comment by techecoyote** [comment] 2019-09-24 00:03
ok, received update. Hereis a log clip...

19:49:15.142 T:6012   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi176\portable_data\userdata\addon_data\plugin.video.fen\TV Show Downloads\
19:49:21.891 T:11320  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
19:49:25.022 T:10420   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi176\portable_data\userdata\addon_data\plugin.video.fen\TV Show Downloads\
19:49:42.102 T:9592  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
19:49:43.674 T:9592 WARNING: CSkinInfo: failed to load skin settings
19:49:43.674 T:9592   ERROR: XFILE::CDirectory::GetDirectory - Error getting resources/skins/Default
19:49:43.676 T:9592   ERROR: EXCEPTION: XML File for Window is missing
19:49:43.677 T:9592 WARNING: CSkinInfo: failed to load skin settings
19:49:43.690 T:3948 WARNING: Skin has invalid include: Animation_DialogPopupOpenClose
19:49:43.690 T:3948 WARNING: Skin has invalid include: VisibleFadeEffect
19:49:45.030 T:9592   ERROR: ResolveURL: ResolverError Error - From: openload Link: https://openload.co/embed/mQG9Z-j1wpI?c1_file=https://sub.seriesonline.io/the-i-land-season-1-episode-1/the-i-land-season-1-episode-1.vtt&c1_label=English: No OpenLoad Authorization
19:49:48.869 T:3948   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?id=None&mode=play_file&name=None&source=%5b%7b%22debrid%22%3a%20%22%22%2c%20%22language%22%3a%20%22en%22%2c%20%22name_rank%22%3a%201%2c%20%22url%22%3a%20%22https%3a%2f%2fopenload.co%2fembed%2fmQG9Z-j1wpI%3fc1_file%3dhttps%3a%2f%2fsub.seriesonline.io%2fthe-i-land-season-1-episode-1%2fthe-i-land-season-1-episode-1.vtt%26c1_label%3dEnglish%22%2c%20%22debridonly%22%3a%20false%2c%20%22scrape_provider%22%3a%20%22external%22%2c%20%22multiline_label%22%3a%20%2201%20%7c%20%5bB%5dEXT%5b%2fB%5d%20%7c%20%5bI%5d%5bB%5d720P%5b%2fB%5d%5b%2fI%5d%20%20%7c%20SERIESONLINE%20%7c%20OPENLOAD%22%2c%20%22direct%22%3a%20false%2c%20%22source%22%3a%20%22openload.co%22%2c%20%22external%22%3a%20true%2c%20%22provider%22%3a%20%22seriesonline%22%2c%20%22quality_rank%22%3a%204%2c%20%22label%22%3a%20%2201%20%7c%20%5bB%5dEXT%5b%2fB%5d%20%7c%20%5bI%5d%5bB%5d720P%5b%2fB%5d%5b%2fI%5d%20%20%7c%20SERIESONLINE%20%7c%20OPENLOAD%22%2c%20%22quality%22%3a%20%22720p%22%2c%20%22size%22%3a%200%7d%5d&title=None
19:49:48.870 T:3948   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?id=None&mode=play_file&name=None&source=%5b%7b%22debrid%22%3a%20%22%22%2c%20%22language%22%3a%20%22en%22%2c%20%22name_rank%22%3a%201%2c%20%22url%22%3a%20%22https%3a%2f%2fopenload.co%2fembed%2fmQG9Z-j1wpI%3fc1_file%3dhttps%3a%2f%2fsub.seriesonline.io%2fthe-i-land-season-1-episode-1%2fthe-i-land-season-1-episode-1.vtt%26c1_label%3dEnglish%22%2c%20%22debridonly%22%3a%20false%2c%20%22scrape_provider%22%3a%20%22external%22%2c%20%22multiline_label%22%3a%20%2201%20%7c%20%5bB%5dEXT%5b%2fB%5d%20%7c%20%5bI%5d%5bB%5d720P%5b%2fB%5d%5b%2fI%5d%20%20%7c%20SERIESONLINE%20%7c%20OPENLOAD%22%2c%20%22direct%22%3a%20false%2c%20%22source%22%3a%20%22openload.co%22%2c%20%22external%22%3a%20true%2c%20%22provider%22%3a%20%22seriesonline%22%2c%20%22quality_rank%22%3a%204%2c%20%22label%22%3a%20%2201%20%7c%20%5bB%5dEXT%5b%2fB%5d%20%7c%20%5bI%5d%5bB%5d720P%5b%2fB%5d%5b%2fI%5d%20%20%7c%20SERIESONLINE%20%7c%20OPENLOAD%22%2c%20%22quality%22%3a%20%22720p%22%2c%20%22size%22%3a%200%7d%5d&title=None) failed
19:49:56.641 T:11748   ERROR: Unable to find plugin
19:49:56.641 T:3948   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://
19:49:56.641 T:3948   ERROR: CGUIMediaWindow::GetDirectory(plugin://) failed
19:49:58.235 T:3948   ERROR: ADDON: extension '' is not currently supported for service addon
19:50:40.040 T:10024   ERROR: Previous line repeats 3 times.
19:50:40.040 T:10024  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:71740fe9-d9c0-4906-9750-b400d0d57e75" for service "urn:upnp-org:serviceId:ConnectionManager" of device "DELL-2: Dell User:" (timeout = 300)
19:50:40.040 T:3472  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:71740fe9-d9c0-4906-9750-b400d0d57e75" for service "urn:upnp-org:serviceId:ContentDirectory" of device "DELL-2: Dell User:" (timeout = 300)
19:50:45.040 T:8044  NOTICE: Platinum [platinum.core.ctrlpoint]: Updating timeout for subscriber "uuid:013d3ca9-6991-4778-9545-3ddcb207a2d2" for service "urn:upnp-org:serviceId:ContentDirectory" of device "DELL-2: Dell User:" (timeout = 300)
19:50:55.771 T:3948   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
19:51:08.091 T:2680  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.34
19:51:08.601 T:8452   ERROR: XFILE::CDirectory::GetDirectory - Error getting C:\Program Files\Kodi176\portable_data\userdata\addon_data\plugin.video.fen\TV Show Downloads\
19:51:54.172 T:3948   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
19:51:56.902 T:3948   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.fen/?foldername=External%20Scraper&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20External%20Scraper%20Settings.&list_name=Settings%20External%20Scraper&mode=open_settings&query=6.0
19:51:56.903 T:3948   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fen/?foldername=External%20Scraper&iconImage=C%3a%5cProgram%20Files%5cKodi176%5cportable_data%5caddons%5cscript.tiki.artwork%5cresources%5cmedia%5clight%5csettings.png&info=Access%20External%20Scraper%20Settings.&list_name=Settings%20External%20Scraper&mode=open_settings&query=6.0) failed
19:51:57.411 T:3948   ERROR: Control 200 in window 10140 has been asked to focus, but it can't
19:52:04.587 T:8552  NOTICE: ####TIKISCRAPERS (Exception)###: no such table: debrid_data
19:52:22.126 T:3948  NOTICE: Previous line repeats 3 times.
19:52:22.126 T:3948   ERROR: ADDON: extension '' is not currently supported for service addon

It looks like something with debrid. I don't use debrid at all , just trakt.

Another thing I just noticed..........
Results Sort order. Is that option suppose to change the view info of the results? Provider - Quality or
Quality - Provider when it is displayed? If so, It doesn't seem to change what I see for the results. They always display the quality - provider... No biggy.. Not trying to pick at the addon, just giving you info...
Love your work... Thanx for all your effort...

**Comment by Tikipeter** [comment] 2019-09-24 01:06
Yep, this is what I wanted to see:

####TIKISCRAPERS (Exception)###: no such table: debrid_data

I'll push another update with the fix for this. Thanks for your debugging efforts techecoyote.

The results order should do the following if you have it set to Provider-Quality:

Provider A 4k

Provider A 1080p

Provider A 720p etc.

Provider A SD

Provider B 4k

Provider B 1080p

..etc

If set to Quality-Provider it should do the following:

Provider A 4k

Provider B 4k

Provider A 1080p

Provider B 1080p

..etc

I'll have a look and see what's going on with it....

EDIT: Actually, I think I remember what the issue is. I class 'Providers' as each of the Fen Internal Providers plus the External Provider. So the whole set of results for the External Provider is classed as one provider when sorting. Meaning if you don't use any of Fen's Internal Providers, you wouldn't see a difference.

This should be fixed, but will not be an entirely trivial fix. Give me some time for this one.

**Comment by techecoyote** [comment] 2019-09-24 02:02
Outstanding... I guess the squeaky wheel does get the grease... I do appreciate everything you do. And I don't give compliments lightly, meaning, I mean what I say. Thank you again.

The Results Sort order was very confusing, I assumed it did one thing when it had nothing to do what I was thinking. I only use the externals. Maybe there are others just as confused. Could it be worded differently? Or could you explain it in the Help?

BTW, you have 2(two) #16 in your test directory. I know it doesn't matter anymore because you don't display the numbers of the Help section in Fen. Again, Just wanted to let you know....

**Comment by Tikipeter** [comment] 2019-09-25 22:29
All issues should be fixed with v.1.5.52.

**Closed by Tikipeter** 2019-09-25 22:29 UTC
Labels: bug, enhancement, pending update
