### ISSUE TITLE
No Sources found

### ISSUE THREAD

**Issue by Converted007** [Tikipeter/repository.tikipeter#185] opened 2020-04-07 05:28 UTC
Hi,

This is a log provided after a cold restart and 1 search of the movie "Joker" from my 18.6 system with RD enabled and openScrapers too: https://paste.kodi.tv/zizejozite

I have the exact same issue on a Pi3 with 17.6 on it.

Basically it doesnt find any sources (debrid) or torrents with the standard settings enabled. So i dont know what im doing wrong here. Before this update it worked just fine. So something must have happened because its the exact same behaviour on 2 different systems.

**Comment by Tikipeter** [comment] 2020-04-07 22:28
How much of the scraping process is completed? Do you see the scraping progress dialog as the results come through from Openscrapers, or does it immediatelt show no results?

**Comment by Converted007** [comment] 2020-04-07 22:42
> How much of the scraping process is completed? Do you see the scraping progress dialog as the results come through from Openscrapers, or does it immediatelt show no results?

It gives the openscrapers dialog box and find some sources. But not alot if you compare it from before or with another addon like seren.
And it removes duplicates, turned that on and off but no difference.

Remember its on 2 different setups with the same result. Its scraping almost nothing and then says no file or no sources or something and thats it.

Timeout is set as the default: 30. Tried 50 as well but no difference.

**Comment by Tikipeter** [comment] 2020-04-07 22:56
When you say you have RD enabled, is that in Fen's settings or ResolveURL's?

**Comment by Converted007** [comment] 2020-04-07 22:59
> When you say you have RD enabled, is that in Fen's settings or ResolveURL's?

Both. And retried authentication in Fen itself but didnt worked. On both systems (pi3 and pi4)

**Comment by Tikipeter** [comment] 2020-04-07 23:03
If you don't have RD/PM or AD currently authenticated in Fen, then you won't see many results, and won't see ANY premium results. Fen doesn't use ResolveURL for resolving debrid links anymore, so you NEED your debrid accounts authenticated in Fen in order to use them in Fen. You need to get that sorted first.

**Comment by Converted007** [comment] 2020-04-07 23:27
> If you don't have RD/PM or AD currently authenticated in Fen, then you won't see many results, and won't see ANY premium results. Fen doesn't use ResolveURL for resolving debrid links anymore, so you NEED your debrid accounts authenticated in Fen in order to use them in Fen. You need to get that sorted first.

I meant that i have a RD account. And that i have re-authenticated it in Fen on both the pi3 and pi4 a couple of times now. But it still scrapes (dialog is shown) way too little and it gives the no result dialog on both systems.

Openscrapers and resolveurl works too. Because in Venom i get hundreds of results (both cached torrents and hosters)

**Comment by Tikipeter** [comment] 2020-04-07 23:32
I don't understand. What did you mean by this..

> And retried authentication in Fen itself but didnt worked.

You need to make sure RD is authed in Fen. Maybe see if you can browse your RD Cloud by navigating to Premium Services->Real-Debrid->Cloud Storage. If RD isn't authed in Fen, not Premium results will show.

**Comment by Converted007** [comment] 2020-04-07 23:50
> I don't understand. What did you mean by this..
> 
> > And retried authentication in Fen itself but didnt worked.
> 
> You need to make sure RD is authed in Fen. Maybe see if you can browse your RD Cloud by navigating to Premium Services->Real-Debrid->Cloud Storage. If RD isn't authed in Fen, not Premium results will show.

I authenticated it. RD is active. RD works in all addons except yours...

**Comment by jaimsitecom** [comment] 2020-04-08 06:26
> > I don't understand. What did you mean by this..
> > > And retried authentication in Fen itself but didnt worked.
> > 
> > 
> > You need to make sure RD is authed in Fen. Maybe see if you can browse your RD Cloud by navigating to Premium Services->Real-Debrid->Cloud Storage. If RD isn't authed in Fen, not Premium results will show.
> 
> I authed it. RD is active. RD works in all other addons. Possibly in yours too. But it doesnt show any results and it scrapes way too little...
> 
> What i meant is that i re-authed my RD account in Fen. To make sure it got saved.

Converted007, 

SETTINGS: 

EXTERNAL(resolveurl): Resolveurl settings- realbebrid -then reauthorize

Settings: Accounts-Realdebrid-reauthorize. 

Then SETTINGS: 
Internal scrapers - enable RD CLOUD
external scrapers -enable external
- uncheck (for now) stop search early...
- uncheck remove duplicates
- uncheck remove failing
- Uncheck pre emptive termination

Torrents minimum seeders (1-3)

Settings :results - scraper timeout 60
Torrents sorting 
Sort torrents to top
Enable Check debrid services for cached
Enable didplay uncached
Uncheck filter torrents

Settings: external (openscrapers settings)
General : enable paid real debrid w torrents
Double check if ‘debrid only’ list are all checked
Also check if torrent (cached) are all checked too

* in my case i disabled all hosters, foreign, foreign2 since i want only debrid sources. 

Then go to tools- clear databases- clear all caches (exclusive favorites....)

Exit kodi. Restart your android box. Then try opening the movie if it get more scraped sources than before

**Comment by Tikipeter** [comment] 2020-04-09 18:08
I don't know what the problem is if you are CERTAIN you have RD authed IN FEN.

You may have to supply me with your "Results" tab settings so I can replicate your settings and hopefully also the problem.

**Comment by Converted007** [comment] 2020-04-09 22:20
> I don't know what the problem is if you are CERTAIN you have RD authed IN FEN.
> 
> You may have to supply me with your "Results" tab settings so I can replicate your settings and hopefully also the problem.

Done. These settings are from my pi4 with 18.6 and are the same on my pi3 with 17.6 where it doesnt work either.
![screenshot003](https://user-images.githubusercontent.com/36426581/78945638-1ce0e900-7ac1-11ea-9699-d18127442f3a.png)
![screenshot002](https://user-images.githubusercontent.com/36426581/78945643-1e121600-7ac1-11ea-9dd1-0208eb7383f7.png)
![screenshot001](https://user-images.githubusercontent.com/36426581/78945645-1e121600-7ac1-11ea-8314-4d60f89b90fb.png)
![screenshot000](https://user-images.githubusercontent.com/36426581/78945648-1f434300-7ac1-11ea-909b-13f36e725c84.png)

**Comment by Tikipeter** [comment] 2020-04-10 00:11
Unfortunately, I get lots of results showing with those exact settings.

If you are willing to install a test file on one machine, I can add extra logging to try and see what's going on. There's not much else I can do at this stage to help you...

**Comment by Converted007** [comment] 2020-04-10 05:32
> Unfortunately, I get lots of results showing with those exact settings.
> 
> If you are willing to install a test file on one machine, I can add extra logging to try and see what's going on. There's not much else I can do at this stage to help you...

Ok thats fine with me. Ill install it on the pi3 with 17.6 if thats ok for u...

**Comment by Tikipeter** [comment] 2020-04-10 15:48
The only issue with Openscrapers is to make sure you are on version 0.0.1.106.
I'll have a test build posted here shortly...

**Comment by Converted007** [comment] 2020-04-11 22:17
> The only issue with Openscrapers is to make sure you are on version 0.0.1.106.
> I'll have a test build posted here shortly...
> 
> Here is a test build to try:
> http://s000.tinyupload.com/index.php?file_id=90432755446375681826
> 
> Please send me through a log after testing a scrape.

This is the log: https://paste.kodi.tv/noyuzaluru
Made the test on my pi3 with 17.6 and the movie "Joker"

**Comment by Tikipeter** [comment] 2020-04-11 22:45
Can you firstly turn ON "Include Non Debrid" in Results->Sorting & Filtering, and then try this new test build and send me a log again.

The previous log showed you received 56 sources originally (not nearly enough if RD is active in Fen), and then none were left after filtering.

New test build:
http://s000.tinyupload.com/index.php?file_id=15445707198532432974

**Comment by Converted007** [comment] 2020-04-12 00:07
> Can you firstly turn ON "Include Non Debrid" in Results->Sorting & Filtering, and then try this new test build and send me a log again.
> 
> The previous log showed you received 56 sources originally (not nearly enough if RD is active in Fen), and then none were left after filtering.
> 
> New test build:
> http://s000.tinyupload.com/index.php?file_id=15445707198532432974

Kodi log: https://paste.kodi.tv/doluzumaxi

Before i restarted again i authed my RD account in FEN again, to make sure it was authed correctly. Which it was, because it gave the OK dialog.
And tried with paid/premium torrent providers settings in openscrapers but with the same result. Now its set to its default providers.

**Comment by Tikipeter** [comment] 2020-04-12 00:52
I'm afraid it's what I've been saying all along. The log shows that there are no debrid accounts active in Fen:

`###debrid_enabled###: []`

For some reason it is not seeing that you have authed RD in Fen.

From the root directory of Fen (start page), please go to Premium Services->Real Debrid->Download History. Did that open OK? Is "Download History" even there to select?

In Settings->Accounts->Real Debrid you need to be seeing an entry next to  'Real Debrid Username'.

**Comment by jaimsitecom** [comment] 2020-04-12 05:35
> > Can you firstly turn ON "Include Non Debrid" in Results->Sorting & Filtering, and then try this new test build and send me a log again.
> > The previous log showed you received 56 sources originally (not nearly enough if RD is active in Fen), and then none were left after filtering.
> > New test build:
> > http://s000.tinyupload.com/index.php?file_id=15445707198532432974
> 
> Kodi log: https://paste.kodi.tv/doluzumaxi
> 
> Before i restarted again i authed my RD account in FEN again, to make sure it was authed correctly. Which it was, because it gave the OK dialog.
> And tried with paid/premium torrent providers settings in openscrapers but with the same result. Now its set to its default providers.

I’m also guessing you only entered your debrid details inside resolveurl (which is also inside the settings of FEN). So not to be confused, please go to FEN-SETTINGS-ACCOUNTS. 

![88405104-3B31-413B-B189-E160A295A087](https://user-images.githubusercontent.com/58242813/79061384-5c2a5800-7cc2-11ea-8e3e-f1b91ac382e9.jpeg)

**Comment by Converted007** [comment] 2020-04-12 06:07
> I'm afraid it's what I've been saying all along. The log shows that there are no debrid accounts active in Fen:
> 
> `###debrid_enabled###: []`
> 
> For some reason it is not seeing that you have authed RD in Fen.
> 
> From the root directory of Fen (start page), please go to Premium Services->Real Debrid->Download History. Did that open OK? Is "Download History" even there to select?
> 
> In Settings->Accounts->Real Debrid you need to be seeing an entry next to 'Real Debrid Username'.

Ill show it to you in a few videos. Because its like you dont believe me...

1: https://www.dropbox.com/s/wkcqaum773edudq/IMG_0568.MOV?dl=0
2: https://www.dropbox.com/s/tqpgiwntto0mkzb/IMG_0567.MOV?dl=0

There is and was never an entry next to "Real-Debrid Username".
But the RD account is authed and active inside FEN: https://www.dropbox.com/s/l7vbthcj6s59iiw/InkedIMG_0569_LI.jpg?dl=0

And this is on my pi3 with 17.6 BUT also on my Pi4 with 18.6. So something is wrong with your addon. Because my RD works on all other plugins with or without resolveurl.

**Comment by Tikipeter** [comment] 2020-04-12 07:48
It's certainly not that I don't believe you Converted007, the log shows no active debrid account. And its the only explanation as to the problem you are having. I did say that for some reason Fen wasn't seeing your debrid account as active, not that you hadn't activated it.

There are occadionally

**Comment by Converted007** [comment] 2020-04-12 08:16
> It's certainly not that I don't believe you Converted007, the log shows no active debrid account. And its the only explanation as to the problem you are having. I did say that for some reason Fen wasn't seeing your debrid account as active, not that you hadn't activated it.
> 
> There are occasionally issues with settings being saved successfully when accessed how you are accessing them in that video (through the "Information" screen of the addon). I would navigate through the addon to Settings->Accounts and try authorizing RD again.
> 
> Neither your RD Username nor your RD Token are being saved in the settings after authorization. That seems to be the issue here.
> 
> Especially the token is needed or the debrid account will come back as unauthed.

Problem solved on my pi3 with 17.6 after reinstalling FEN. The RD username in settings appeared and scraping works now.
On my pi4 I have to begin from scratch again because for some reason the RD authentication dialog in all my adding doesn’t appear. Or very slowly...

**Comment by Tikipeter** [comment] 2020-04-12 11:00
I'm glad one is fixed. As for the second device, you might have to wait a while. RD seems to be having issues atm, so it might be that.

That settings issue I talked of has been around a long time, it's mainly a problem with settings that shut the settings menus and then perform an action (like authing debrid accts). The settings aren't loaded properly until you navigate back from that info screen.

**Comment by Converted007** [comment] 2020-04-12 17:39
> I'm glad one is fixed. As for the second device, you might have to wait a while. RD seems to be having issues atm, so it might be that.
> 
> That settings issue I talked of has been around a long time, it's mainly a problem with settings that shut the settings menus and then perform an action (like authing debrid accts). The settings aren't loaded properly until you navigate back from that info screen.

Damnit. Already deleted my micro-sd card from my pi4 lol. But now I know it’s best to open the add-on and then go into settings instead of opening it from the information screen.

For me the issue is solved and may be closed:)
Thanks for the support!

**Comment by Tikipeter** [comment] 2020-04-12 22:16
I don't know where to go to see of issues for RD, but I noticed their API was much slower the last couple of days when checking for cached torrents.

Hopefully your second device will also work properly now when you get the chance. Let me know if you have more troubles....

**Closed by Tikipeter** 2020-04-12 22:16 UTC
Labels: possible bug

**Comment by Converted007** [comment] 2020-04-13 06:19
> I don't know where to go to see of issues for RD, but I noticed their API was much slower the last couple of days when checking for cached torrents.
> 
> Hopefully your second device will also work properly now when you get the chance. Let me know if you have more troubles....

Thanks!
A reinstall of my pi4 solved the issue with the authentication dialog appearing very slow. AND FEN works out of the box. 
And as you told me i first authed RD within FEN and changed a few settings within the add-on and not via the information screen.

Thanks!
