### ISSUE TITLE
Folder Scraper does not scrape Movies.

### ISSUE THREAD

**Issue by SJ50** [Tikipeter/repository.tikipeter#82] opened 2019-12-14 01:52 UTC
I have set up folder scraper for TV and Movies, it scrapes TV Shows but not able to scrape movies. movies are separated in their own folder.

**Comment by Tikipeter** [comment] 2019-12-14 22:48
Hi SJ50.

This will be hard to diagnose because it is working for me. Some things you can do to troubleshoot:

* Make certain you have the ROOT folder for your movies set in the scraper's settings. i.e.

        --- ROOT MOVIE FOLDER  <-- Place this folder in the scraper's settings.
     
                --- Movie 1 Folder
                 
                        --- Movie1.mkv
      
                --- Movie 2 Folder
                  
                        --- Movie2.mkv

* Make sure you have assigned the scraper a name.
* If you have any quality limits set, then perhaps the folder scraper results are being filtered. Go to the folder scraper you have set, and make sure "Apply Quality Limit to Source# Files" is UNCHECKED. This will stop Fen filtering out the result/s. Fen relies purely on the filename of the video file to determine quality, so if your file doesn't have 1080p, 4k etc in the filename, it will label it as 'SD', and won't show it in results if you don't have SD in your list of included resolutions.
* ENABLE "Show Source# Results at Top" so you will definitely see the result at the top of the display. Perhaps it is getting lost within other results.
* Disable ALL other scrapers except for the Folder scraper you are having problems with, and see if Fen counts the file on the Progress Display dialog, but then doesn't show it as a result after the dialog closes.
* ENABLE "Check Source# Scraper before Search" to see if Fen finds the file in the pre-scrape search.

If none of those suggestions bring about a resolution, you could provide here the following:
* A Kodi log after performing a search with that Scraper enabled, to see if there are any errors.
* Your folder structure (like I have done above) and the actual name of a movie that you have that won't scrape. I will set up the same folder structure and movie name and see if it works for me.

**Comment by SJ50** [comment] 2019-12-14 23:50
I followed your suggestions and no result.

Here is is my folder structure

 $ ls /mnt/cloud/team_drive_crypt/media/Movies/Movies_HD/Avengers.Endgame.2019.1080p.WEBRip.EAC3.5.1ch.x264.\[tt4154796\]-GEEK/
Avengers.Endgame.2019.1080p.WEBRip.EAC3.5.1ch.x264-GEEK.mkv

/mnt/cloud/team_drive_crypt/media/Movies/Movies_HD/ is mapped in folder scraper.

may be "[" "]" is a problem, I will test this and reply back.

For log I will google how to export it and post it later.

**Comment by Tikipeter** [comment] 2019-12-15 00:34
Good job SJ50. No need for a log yet.

In Fen's root menu (main menu), navigate into "Sources Folders". (if you don't have this menu item, bring up the context menu on any other item, select "Edit Menu", then select "Check if Root Menu has New Menu Items". It should show you the new menu item (Sources Folders) which you can then place anywhere on the main menu.

When you are in Sources Folders, find the source that you are having trouble with, and see if you can navigate into it and see the movie folders etc.

I will recreate your folder structure and see if it works for me in the meantime...

**Comment by Tikipeter** [comment] 2019-12-15 00:44
I've worked out what the problem is.
No need for you to do anymore testing @SJ50 
Fix will be in next update.

**Closed** 2019-12-16 18:42 UTC
Labels: bug, pending update

**Comment by SJ50** [comment] 2019-12-16 21:00
Checked with one movie and it worked. 
Thank you @Tikipeter for fast fix.
