### ISSUE TITLE
A few small bugs

### ISSUE THREAD

**Issue by Bequiet19** [Tikipeter/repository.tikipeter#685] opened 2022-01-15 13:09 UTC
First I want to thank you for this great addon. What surprised me the most was the speed. Amazing how quickly it opens lists with all-inclusive fanart images. However, I noticed some little things, so I would like it to be sorted out. First I noticed that mpaa ratings don't work the best. Fen doesn't show them for a lot of movies and tv shows. I compared it with elementum and tmdb helper and there are all those ratings.
Second, the studio and network logo for some movies and tv shows doesn't display. Again, checked in tmdb helper and elementum displays the same. 
This is what I noticed during this short time of use. I hope you will continue to improve this great addon.

**Comment by Tikipeter** [comment] 2022-01-15 23:50
MPAA, coincidentally, was fixed a couple of days ago. Will be in next update.

The rest is harder (impossible) to sort out. To see the issue, switch your skin to the default Estuary, and then do the same comparison. Fen will display far more network logos than either Elementum or TMDbHelper.

The issue is data for networks (studios) from tmdb is usually a list. Multiple studios. I can either give that to Kodi as a list, or give that to Kodi as a single studio (only use the first one in the list). Different skins and skin helper scripts will attempt to display logos based on either being given a list of studios, or a single studio.

Addons like Elementum and TMDbHelper give the list, so for skins and skin helper scripts that want a list it will work a lot better. Fen provides a single studio. So for skins and skin helper scripts that need it that way, Fen will work a lot better.

The issue is it needs to be one or the other. Can't do both. As such, the best way to decide what to use is to check with the Kodi default skin. So single studio it has to be for Fen.

**Comment by Bequiet19** [comment] 2022-01-16 12:01
OK. I understand to some extent. I'm not an expert. I didn't understand why it's better for fen to show only one logo and not a list? If it displays a list, couldn't it be set to display the first logo? I'm sorry once again because I don't understand this issue.
I tried a few skins. My default skin is titani bingie mod. For example, it does not show the studio logo in some movies. The aura mode doesn't display the same logos. Aeon nox is a slightly different story. It does not display the same logos but displays text where it does not. So the problem is that he doesn't display the logo either.
Is there a possibility to insert as an option in fen to choose whether I want a list or an individual logo to suit all skins? 
I love the Netflix look and I would love for titan bingie mod to show me all the logos as in elementum and tmdb helper. I would be very grateful if you could find a some compromise solution. Thanks in advance.

**Comment by Tikipeter** [comment] 2022-01-16 17:41
The studios code is not changing. Any compromise will have to come from your side.

**Comment by Bequiet19** [comment] 2022-01-16 18:46
Ok. I just checked in the default etuary skin. Everything that is missing in titan bingie mode is also missing in estuary skins. So they use the same way to showing the studio logo. Why does it happen then that the studio logo is missing for some very famous titles. For example: Nomadland, American beauty, One flew over the cuckoo's nest, the french conection, Lawrence of arabia, Spider man 3, The suicide squad (2021), The hitmans bodyguard... It is not possible that these titles do not have a studio in metadata. Can you check please, do you also missing the studio logo in these titles.

**Comment by xyzfre** [comment] 2022-01-16 18:54
![image](https://user-images.githubusercontent.com/49699869/149673748-6f19e816-26c2-46b5-8d27-ea1202a511fb.jpeg)

**Comment by Bequiet19** [comment] 2022-01-16 18:59
@xyzfre I didn't mean new Spider Man 3, old from 2007.

**Comment by xyzfre** [comment] 2022-01-16 19:51
Yeah sorry for the first comment I thought you were referring to the latest Spider-Man ...but I just check with TMDB helper the hitman's bodyguard and using AuraMod I have all my APIs set up and the same as Fen no studio network logo so it could just be a different skin thing going on the mystery of Kodi lol

**Comment by xyzfre** [comment] 2022-01-16 19:52
![image](https://user-images.githubusercontent.com/49699869/149675629-16bdbf02-3ce0-436b-9df6-7ee6db9ae0fc.jpeg)

**Comment by xyzfre** [comment] 2022-01-16 19:54
That's using TMDB helper in the pic above and I just check with Venom also no studio network for this film haven't tested the rest Will try when I get a chance

**Comment by Tikipeter** [comment] 2022-01-16 20:42
Here's TMDb's response for production companies for Spiderman 3 (2007):
`['Laura Ziskin Productions', 'Marvel Studios']`
The first item in the list is chosen, meaning `Laura Ziskin Productions` is set as the Studio for that movie. If there is no logo for that studio in the artwork being used by the skin, then there will be no studio logo shown.

**Comment by Tikipeter** [comment] 2022-01-16 21:03
What I can do is use the fact that tmdb will give also a logo location (not used by the skin) for the studio if it has one. I'll attempy to use the first studio in the list that has a logo location. This should mean it will also have a logo in the skin/skin helper that can be used.

**Comment by Bequiet19** [comment] 2022-01-16 21:27
@Tikipeter If you want I can test the version before putting it on repo for public.

**Comment by Tikipeter** [comment] 2022-01-17 12:40
No thanks.

Meta will need to be cleared after next update for anyone who cares about these logos.

**Closed by Tikipeter** 2022-01-17 12:40 UTC

**Comment by 123Venom** [comment] 2022-01-17 17:28
> Lawrence of arabia

When you tested Estuary did you by chance go back into TMDb Helper and test those same titles you listed?  Only a couple had studio logos and the reason is because Estuary does not support studios as a list that TMDb Helper uses.  I'm kind of surprised jurial did that seeing how many are missing.  Take **Laurence of Arabia**, only one studio existed in the TMDb endpoint response so that's all that was set and Estuary could then set the logo match it found.  Spider-Man 3...nada.  In fact I think only 2 of your titles had studio logos.

In Venom I removed setting of studio logos for movies...to petty for me to care about but my reasoning is different.  I use Silvo skin, another skin that does not support studios as a list.  Silvo replaces thumbs with studio logos and in many views it looks downright awful so I gave up setting it till he either fixes that or I start to care about having that little logo.  Personally I think setting studios as a list is a bad idea as it sure seems to me more skins do not support it than does.

**Comment by Bequiet19** [comment] 2022-01-18 06:10
@123Venom I only compared esuarty with titan bingie mod to say they use the same way of displaying the logos. Things like logos, ratings... make a lot more sense in slightly richer skins like titan, aura... There are people who like such things and such skins that show a lot of information and show it all visually.

**Comment by 123Venom** [comment] 2022-01-18 23:53
Maybe I misunderstood you.  When you listed all those titles I was under the impression that Fen, under Titan Bingie mod, did not show the logos but TMDb Helper does?
