### ISSUE TITLE
Downloads to NAS Devices Not working

### ISSUE THREAD

**Issue by flhthemi** [Tikipeter/repository.tikipeter#191] opened 2020-04-15 20:25 UTC
I have 4 different NAS devices. If I set the downloads path to any of them the downloads never show up. If I set the path to a local folder on the PC (Windows) it works fine. Other addons are working fine with any of the NAS devices set for the path for downloads.

From the log file:
`2020-04-15 15:43:38.594 T:1632   ERROR: XFILE::CDirectory::Create - Error creating smb://MYBOOKLIVE/Public/Downloads/Whose Line Is It Anyway (1998)/Season 16
2020-04-15 15:44:36.631 T:1328  NOTICE: localGetNetworkResources: Can't open network enumeration for "MICROSOFTACCOUNT" (provider "Microsoft Windows Network"). Error: 87
2020-04-15 15:44:36.631 T:1328  NOTICE: localGetNetworkResources: Can't get servers from "MICROSOFTACCOUNT", skipping
2020-04-15 15:44:39.864 T:1328  NOTICE: localGetNetworkResources: Can't open network enumeration for "MICROSOFTACCOUNT" (provider "Microsoft Windows Network"). Error: 87
2020-04-15 15:44:39.864 T:1328  NOTICE: localGetNetworkResources: Can't get servers from "MICROSOFTACCOUNT", skipping
2020-04-15 15:45:01.218 T:1328 WARNING: CGUIWindowManager - CGUIWindowManager::HandleAction - ignoring action 107, because topmost modal dialog closing animation is running`

I see there were issues with this in November??? I hope I'm not just repeating the problem :)

Thanks!

**Comment by Tikipeter** [comment] 2020-04-15 22:03
Does it show the progress of the download as if it is downloading the file, or fail immediately?

**Comment by flhthemi** [comment] 2020-04-16 14:30
> Does it show the progress of the download as if it is downloading the file, or fail immediately?

Yes it shows progress and all appears it is downloading the file but no files shows up in the designated folder IF it's an NFS or SMB folder.

**Comment by Tinuz97** [comment] 2020-04-16 16:09
I have this with Android devices (phone and nvidia shield), but if i use windows to windows it works (for me, SMB share), weird. (shows progress and complete afterwards,but file not on my server,only if using my pc to pc, in my situation a Android limit i guess? )

**Comment by Tikipeter** [comment] 2020-04-16 22:00
I hate to say it, but it's definitely possible I don't have the skills/knowledge to fix this issue.

I'm going to do my best.

**Comment by flhthemi** [comment] 2020-04-17 19:36
> I hate to say it, but it's definitely possible I don't have the skills/knowledge to fix this issue.
> 
> I'm going to do my best.

That's good enough for me! Would it help to look over code from another addon that has this function working?

**Comment by Tikipeter** [comment] 2020-04-17 20:24
> That's good enough for me! Would it help to look over code from another addon that has this function working?

I thought it would, as I based my code originally from the downloader.py file everyone else uses (written a long time ago by spoyser). The problem is I've changed that file a lot, so it's hard to compare the two these days.

I was able to replicate the fail by trying to do a download FROM a Windows machine TO a LibreELEC install, just so I could try to fix this.

Turned out a check I had in the code to make sure the folder was made successfully failed in this situation, so when I removed the check it worked no problem. I'm hoping it will also fix your specific setup, as I can't replicate it to test.

The possible 'fix' will be in the next update...

**Comment by flhthemi** [comment] 2020-04-18 12:04
Ok..I'll let you know after I get the next update. Glad you kept at it! It's a great addon, probably the best since SALTS IMO.

**Comment by flhthemi** [comment] 2020-04-19 17:25
No luck. Still only downloads to a local folder. It's not a big deal for me, I use it very rarely but it might be a problem for others.

**Comment by Tikipeter** [comment] 2020-04-19 22:48
That's a shame. I'll keep on it..

Also, I was a huge SALTS fan back in the day. Everyone used Genesis/Exodus, but I always loved SALTS. I can't remember exactly what unique features tknorris had in it, but I know as soon as I started making Fen (Furk It in those days) I wanted to incorporate certain things that SALTS had that I loved. What a great add-on. Plus, there was a good community at tvaddons, before the shit hit the fan.

**Comment by flhthemi** [comment] 2020-04-20 15:12
Well I think you're doing every bit as good as, or better as SALTS. I did a couple theme packs for SALTS..think they were called IGTB (I Got The Blues).

**Comment by Tikipeter** [comment] 2020-04-23 15:39
More changes for this problem in next update.

If you get the time, could you check if it's working after the update?

Thanks @flhthemi

**Comment by flhthemi** [comment] 2020-04-23 22:53
> More changes for this problem in next update.
> 
> If you get the time, could you check if it's working after the update?
> 
> Thanks @flhthemi

Pretty sure you nailed it! Both NFS and SMB are working in Windows installs. Android works NFS. Kodi has SMB issues with Android (as you may know) so I haven't tested SMB with Android yet.

But I did see Kodi totally crash once. I had backed out of the Fen addon all the way to the main Kodi menu while a download was in progress. Kodi hard crashed...not a lockup but an crash to desktop. I can't say for sure that it was anything to do with Fen. I'm still trying to reproduce it.

Good job on this one mate!

**Comment by Tikipeter** [comment] 2020-04-24 12:29
Thanks for reporting back flhthemi. I'll close this issue. Let me know if there's more problems with crashes..

**Closed by Tikipeter** 2020-04-24 12:29 UTC
Labels: bug, pending update
