### ISSUE TITLE
FEN error everytime it Updates subscription

### ISSUE THREAD

**Issue by jaimsitecom** [Tikipeter/repository.tikipeter#181] opened 2020-04-03 06:45 UTC
Hi Tikipeter!  I just wanna report everytime Fen tries to update the subscription, it gets stopped by ‘FEN ERROR’. Am on 1.6.11 and tiki meta module 1.1.39. hoping this gets check (fixed), new episodes cant get on the library coz of this error. 
Let me know if i need to upload the log for this. 

Thanks!

**Comment by Tikipeter** [comment] 2020-04-03 15:25
I will definitely need a log for this.

**Comment by jaimsitecom** [comment] 2020-04-03 16:19
Thanks!  

Here’s the download link for the log:
https://mega.nz/file/5QARBSbQ#PPvd3Ek-01nolIsVJkrn-9-gwZTUfMJs2JYUkaB3eyo

**Comment by jaimsitecom** [comment] 2020-04-04 05:41
I cleared the meta cache and did the subscription update. Still gettin the ‘FEN ERROR’ then update stops/hangs.

**Comment by Tikipeter** [comment] 2020-04-04 19:05
I'm going to leave this for a bit, because TVDb API is having issues, so there's no use in testing atm. It could even be the reason for your problem.

**Comment by Tikipeter** [comment] 2020-04-05 16:45
OK. TVDb seem to have sorted out their issues. There will be some extra logging in the next update. Try your subscriptions again and see what happens then. Post a log if there are still issues.

**Comment by jaimsitecom** [comment] 2020-04-05 17:24
Cool! Thanks Tikipeter!

**Comment by jaimsitecom** [comment] 2020-04-06 06:38
Tikipeter, good news! I think 1.6.12 solved the subscription update error. Thanks so much!

Only thing ‘bugging out’ is the saving of backups. Keeps on saying ‘ERROR backing up Fen User Data’. Is there a default folder on where to backup the files? Coz i changed the output folder to a different one. Is that an issue?

Anyways, thanks again for fixing the FEN subscription update feature!

**Comment by jaimsitecom** [comment] 2020-04-06 07:23
Sorry. Found another bug(?) re: subscription updates. The update ran fine but in the Kodi Library, some shows list down unaired /future episodes. I unchecked ‘not to show unaired episodes’ in the settings but now it shows it. It doesn’t do that from prior builds.

**Comment by Tikipeter** [comment] 2020-04-06 11:31
With regard to settings backup, since I can't replicate the problem, send me through a log after trying it and I should see an error there.

As for the new subscriptions problem, how far ahead are future episodes being added? Is it just one day. or are episodes being added that don't air for more than one day away? Also, what is your setting for Settings->General->UTC Time Offset?

**Comment by jaimsitecom** [comment] 2020-04-06 12:02
Ok i ll send you the log asap. 

2 shows have four to five future episodes listed. Some shows one or 2 advance episodes.

**Comment by jaimsitecom** [comment] 2020-04-06 12:08
Btw, i deleted the future episodes (.strm files) then updated the subsciption, and it added the future episodes again. So i experimented on downgrading back to 1.6.11 to see if problem is only at latest version. I can confirm that 1.6.11 sticks to current episodes only BUT has the FEN ERROR subscription update, and also that 1.6.12 solves the Subscription update error but then adds unnecessary future episodes despite instruction in setting not to add. 

Ty

**Comment by Tikipeter** [comment] 2020-04-06 12:16
OK. When you post the log, also let me know the 2 shows with four to five future episodes and I will try them and hopefully see what the problem is.

**Comment by jaimsitecom** [comment] 2020-04-06 12:22
Kodi log:
https://mega.nz/file/oN4B0YyJ#Dgg2xY1oJLsKVYebxnKZEGykPU5xFDJVxZLkbCi9HbA

2 shows that added 4-6 future episodes:
The Flash
DC Legends of Tomorrow 

Other shows that added 1-2 future episodes:
Attack on Titan
Russian doll
This is us
Love Deat & Robots

Thanks Tikipeter!

Xiaomi mibox S; kodi 18.6; FEN 1.6.12; Tiki Meta Module 1.1.40

**Comment by Tikipeter** [comment] 2020-04-06 12:32
Did you do a settings backup that failed within that log? There is nothing there related to a failed backup...

**Comment by jaimsitecom** [comment] 2020-04-06 12:42
Oh no. It must have reset when i downgraded and upgraded back to the latest version. Am goin to replicate the error now and resend the log. Ty

**Comment by jaimsitecom** [comment] 2020-04-06 12:47
Latest Log w/ Backup error:
https://mega.nz/file/RMoDWKID#xKv63dzVEXcaEcQcecJTq6Ofgs2qHWuhQh1aSfqnCig


Thanks again!

**Comment by Tikipeter** [comment] 2020-04-06 13:00
Thanks for all the help jaimisitecom.

I'll have to add more logging to the next update to see what's going on with the Settings Backup function.

I'll look into the future date subscription episodes issue now...

**Comment by Tikipeter** [comment] 2020-04-06 13:09
I see the issue with the subscriptions. I'll have to add a setting such as "Add Episodes With Unknown Airdate" and set it to OFF by default.

The episodes being added have no set airdate, likely because the Chinese Virus has stopped production on these shows, so the airdate has been removed from the metadata.

There'll be a fix for this next update.

**Comment by jaimsitecom** [comment] 2020-04-06 13:15
Yay! Thanks a lot Tikipeter! FEN’s the best!  I so love the feature ‘filter torrents by size’!  Man this si simply genius! Ty

**Closed** 2020-04-06 13:24 UTC
Labels: possible bug

**Comment by Tikipeter** [comment] 2020-04-06 13:36
I'll start a new Issue for the Settings Backup problem.
