### ISSUE TITLE
Real-Debrid issues (Fenomscrapers/Fen, unsure)

### ISSUE THREAD

**Issue by hindsight2021** [Tikipeter/repository.tikipeter#669] opened 2021-12-27 14:00 UTC
Like others, since the latest update (that I've encountered this) I can no longer get Real-Debrid results show or accessed in Fen.
This is the only fenomscrapers addon I use, so I'm unsure if it's related, but I see fen invoking a script and a RD timeout with their API url - which may be helpful in diagnosis.

https://pastebin.com/3rbYvQG5

FULL log from just opening Fen - selecting show from next episodes, and selecting "options" >> Rescrape with all external sources - it showed several hundred results but ONLY from easynews - none from RD, below error repeats:

https://pastebin.com/VJPYpv1Z

Hardware: nVidia Shield 2019 pro - Kodi 19.3 test build with HEVC playback fix for Android (no other changes from default branch).

NVIDIA SHIELD Android TV with Android 9.0.0 API level 28, kernel: Linux ARM 64-bit version 4.9.140-tegra-g19e7acaac93b
2021-12-26 21:21:13.493 T:8977     INFO <general>: FFmpeg version/source: 4.3.2-Kodi
2021-12-26 21:21:13.493 T:8977     INFO <general>: 4 CPU cores available
2021-12-26 21:21:13.493 T:8977     INFO <general>: Product: mdarcy, Device: mdarcy, Board: darcy - Manufacturer: NVIDIA, Brand: NVIDIA, Model: SHIELD Android TV, Hardware: darcy
2021-12-26 21:21:13.496 T:8977     INFO <general>: External storage path = /storage/emulated/0; status = ok
2021-12-26 21:21:13.496 T:8977     INFO <general>: ARM Features: Neon disabled

Latest Fen/Fenomscrapers versions - regularly updated from repo(s).

FindAddons: plugin.video.fen v2.5.16 installed
FindAddons: repository.tikipeter v0.0.6 installed
FindAddons: script.module.fenomscrapers v2.1.0 installed

Action starts (seemingly) around line 117

And seems to culminate in line 235 with: HTTPSConnectionPool(host='api.real-debrid.com', port=443): Read timed out. (read timeout=20.0)

I have no issues accessing Real-Debrid api/resources from other RD addons, and easynews is working in Fen without issue, just isolated to RD specifically for me and seemingly others from reading recent issues. It seems to be API related from RD, timing out. I would not say it's ISP related, as mentioned - it works in other addons presently (scrape/playback, and direct access).

I have cleared cache, revoked/re-auth'd RD, re-synced settings in Fen/Fenomscrapers and "cleaned settings" there too, no change.

Thanks for your review - hopefully the log will help.

**Comment by Tikipeter** [comment] 2021-12-27 16:40
If RD is timing out it is an RD issue.
All I can do is increase the timeout, which is currently at 20 seconds. I am not willing to do that. To be honest, I'd be much more willing to remove RD support altogether. It is a garbage service.

**Comment by Tikipeter** [comment] 2021-12-27 16:42
What tv show episode showed several hundred sources from Easynews? I would like to test this.

**Comment by Tikipeter** [comment] 2021-12-27 16:43
Please link me to all the other recent issues related to RD. I've looked and haven't found them.

**Comment by hindsight2021** [comment] 2021-12-27 16:47
If it’s RD sided, no worries just not sure why I’m getting no RD results, testing later I was able to get some movie results so it could have just been temporary on the API side. Show was Smallville.

**Comment by hindsight2021** [comment] 2021-12-27 16:49
Was seeing similar behaviors re; RD as;

https://github.com/Tikipeter/repository.tikipeter/issues/664

https://github.com/Tikipeter/repository.tikipeter/issues/656

https://github.com/Tikipeter/repository.tikipeter/issues/655

wasn’t sure if there was relation to these at first.

**Comment by pigskins65** [comment] 2021-12-27 16:58
Which service do you prefer?

**Comment by 123Venom** [comment] 2021-12-27 17:33
> If RD is timing out it is an RD issue. All I can do is increase the timeout, which is currently at 20 seconds. I am not willing to do that. To be honest, I'd be much more willing to remove RD support altogether. It is a garbage service.

RD is a terrible debrid service!  The issue is more than likely due a bug in some endpoints we've discovered that have a serious delay issue in the response time and attempts to reach out to RD have failed, no shocker there since they offer no support anymore.  I'm sure this is what is causing your timeout issue.  AD and PM is a far better service and api that do not suffer this issue.  I have become so frustrated over RD I'm currently running with it disabled and contemplating removing support for it.

**Comment by Tikipeter** [comment] 2021-12-27 19:23
>Show was Smallville.

I'm not getting hundreds of Easynews results for s06e17 of this show. I don't know how you were getting hundreds of Easynews results.

The issue though, is large shows like this (10 seasons, 216 episodes) are what the RD bug 123Venom alludes to above is affecting. Large show packs choke RD's API when checking the cached status. Since there aren't a huge amount of results for this episode/show, then all the relevant hashes are sent in one batch of 100 hashes or less. If that one batch fails because of the large torrent bug, then that's it. None of those results will come through. I do have a progress dialog that makes it clear what Fen is doing at this point in the process (Remaining Debrid Check), so there should be a visual cue as to what is failing.

To make sure that is the issue, you can try a currently airing show, or at least a show which will have a much smaller torrent for a season or show pack (less seasons and episodes).

Like I said, raising the timeout is the only way to possibly fix this. How long are people willing to wait to get a cache check from RD? PM and AD return their results almost instantly, all in one big batch. For RD, the hashes need to be broken up into lists of no more than 100, and as you can see if the show is large on seasons/episodes they will often time out.

I would likely need to up the timeout value to 60 seconds to cover for this RD bug. Nope. Not happening. Like I said, it seems possible RD support might be dropped from Fen in the near future. Their API has serious issues (many besides this) and the only reason they are still the service of choice is, well, I don't really know why they are still the service of choice. You should see the absolute garbage their API responds with for us devs. It really is a nightmare to deal with their data. My modules for PM and AD are roughly 300 lines. For RD, over 530 lines. All those extra lines are to deal with the insufferable shit their API returns.

**Comment by Tikipeter** [comment] 2021-12-27 19:29
PM had a recent issue with their API, where I needed to push an update temporarily upping the timeout for them to 60 seconds. But I knew it would be temporary, and they were made aware of the issue and set to work on fixing it. Within a couple of days it was sorted out.

There seems to be no chance of this happening with RD. They simply do not seem to care.

**Comment by 123Venom** [comment] 2021-12-27 19:35
RD does not care and they've removed support because they're the top dog believing they can get away with it ..sad actually since it's the worst debrid service of the big 3.  The only way to get RD's attention is to start making people aware of these bugs and jumping ship to a better debrid service, or devs start dropping them like what happened to TVDb that also seemed to result in them changing their tune.  People have been pushing RD for so long they no longer feel they need to care about their problems, until we make them care.  I can no longer stomach using that service but stuck with it till sub runs out.

**Comment by hindsight2021** [comment] 2021-12-27 19:39
Thanks for the analysis, this makes perfect sense reviewing your feedback. I too work with API for a living, but with actual support behind it, so you’re speaking my language and it makes perfect sense to me - money speaks, and even if they don’t acknowledge it, these addons are a huge portion of their base, so maybe removing support is best - this makes my decision to go back to PM easier, thanks for that. I imagine this could be closed given upping a timeout for defunct API is definitely not a fix worth pursuing - you’ll be applying these bandaids forever, yikes.

Cheers,
Happy new year!

**Comment by Tikipeter** [comment] 2021-12-27 19:39
>RD does not care and they've removed support because they're the top dog believing they can get away with it

Anyone reading this Issue thread should take note of what 123Venom is saying here. He narrowed down the issue with timeouts of show packs to find out what was happening, and he too is likely fed up with RD.

>Which service do you prefer?

Anything really. At this point I would probably point to All-Debrid, then Premiumize. Easynews is great and all, but their playback is hit and miss sometimes. They have an issue with timing out when trying to start the stream. At that point the addon has no control over setting the timeout, as that's on Kodi itself by then. There might be an advancedsetting to change the Kodi time out though. Haven't looked into that. But Easynews is also much better than RD.

**Comment by Tikipeter** [comment] 2021-12-27 19:41
>.......given upping a timeout for defunct API is definitely not a fix worth pursuing - you’ll be applying these bandaids forever, yikes.

Unfortunately, I'll likely end up doing just that. There's just too many people that rely on RD, and it's of course not their fault that RD's API is garbage.

**Comment by 123Venom** [comment] 2021-12-27 19:51
> Thanks for the analysis, this makes perfect sense reviewing your feedback. the “hundreds” referred to the scraping showing lots of results before showing the list, but my filters probably removed most - was basing off that originally (fyi)
> 
> I too work with API for a living, but with actual support behind it, so you’re speaking my language and it makes perfect sense to me - money speaks, and even if they don’t acknowledge it, these addons are a huge portion of their base, so maybe removing support is best - this makes my decision to go back to PM easier, thanks for that. I imagine this could be closed given upping a timeout for defunct API is definitely not a fix worth pursuing - you’ll be applying these bandaids forever, yikes.
> 
> Cheers, Happy new year!

PM is a real good choice and we have a nice direct contact with a sales rep that assists us with issues...we can't even get in contact with RD and if we could I'm convinced they'd just ignore us.

Best bang for the buck is AD imo. Lightning fast api, data response provided is more geared towards Kodi's needs.  It handles m2ts better than any of the debrid services.  The down side is they have less cached torrents than RD but as the user base grows that gap in closing!  I have no issues watching anything with AD.  Their retention period is a bit of a mystery still but again it's not effected my ability to watch anything one bit.   They even have support and I've had good communications with them.

**Comment by Tikipeter** [comment] 2021-12-27 19:57
RD timeout upped to 60 seconds for next update.

I threw up a little in my mouth as I typed that up.

Anyone interested why this affects Fen (and Venom) but not some other addons, I'll write a quick summary below that will cover the basics.

#### TheOath, The Crew, other Exodus forks...

These addons don't have pack capable scrapers, so they are not exposed to this RD bug at all.

#### Seren...

Seren DOES have pack scrapers, but they handle their cache checking differently.
Instead of collecting all the torrent hashes and sending them off after scraping finishes, Seren sends the results of each scraper as they come in, meaning longer original scraping times, but no waiting at the end for cached status. This means Seren DOES suffer from the same RD bug that Fen suffers from, but because the actual scrape process is still running whilst torrent hashes are being sent to RD, then the slow RD response is masked by the continuing scrape process. Of course, Seren must have a timeout higher than 20 seconds for RD, or they would suffer from this issue of no results for some large TV Shows. I have not looked up what their timeout is.

#### Venom...
Venom suffers the exact same issue as Fen, but currently has a 60 second timeout for RD. So eventually the results for large TV Shows do come through. Unfortunately this is the approach I will also need to take.

**Comment by 123Venom** [comment] 2021-12-27 21:12
@Tikipeter excellent write up right there...dead on point!!  Best way one can see this in even Seren is having 2 debrid accounts..then turn RD off and compare a scrape of say GOT s01e01.  The pack files will make the scrapers slow ass crawl across the screen when RD is on...RD off and they fly and source results pops up WAY faster.  RD is terrible!!  It's worse with shows that are ended because RD chokes on show packs badly while they're not available for a show like Yellowstone that is still airing.

**Closed** 2021-12-28 02:43 UTC
Labels: pending update
