### ISSUE TITLE
Playback Monitoring Hangs With EN

### ISSUE THREAD

**Issue by ReaLx3m** [Tikipeter/repository.tikipeter#118] opened 2023-01-22 14:07 UTC
Did open an issue with this same problem [few months ago](https://github.com/Tikipeter/repository.tikipeter/issues/68) which was marked as completed, but even after all this time i do still get the behavior. 

Ill just paste the text from the other issue:
Fen will try playing a link, and while not being successful, (Retry) will not show and will be stuck at the spinning wheel. Sometimes it will retry the first link, and then go to second and get stuck at the second with no retry and not going to the next.
I have left it like that for more than 5 minutes and nothing happens, kodi isnt frozen but back button doesnt do anything, only way to get out is reloading the skin.

@Tikipeter Is this something that only im having a problem with and never happens to you and you cant reproduce the behavior?

Unrelated to the above, but another thing that started happening i think when the new resolving windows got introduced, is that watched status isnt updated when the episode ends when youre in "Next Episodes" or in a season of a TV Show. You need to go one level up and then back in the menu for the status to update.

My solution was going back to 3.0.17 . Playback monitoring does have its quirks with that version but at least there are no hangs so far(been on it last few days) as in the newer versions. Watched status also refreshes properly with 3.0.17.
Dont really mind using the older version, but in light of your breakthrough with Language Invoker(congrats on slaying that beast :) ), it would be better using the latest version if those issues mentioned above could be addressed.

**Comment by ReaLx3m** [comment] 2023-01-22 14:19
Heres a video of the hang im talking about so there are no misunderstandings.
https://www.youtube.com/watch?v=WdxfULjDHqo

**Comment by Tikipeter** [comment] 2023-01-22 18:24
Happens very occasionally. Probably one in 20 plays.

I have been constantly rethinking this whole code since inplemented. I don't like the threads it opens, the fact it often leaves a thread being waited on (not the waiting issue though) & other things that annoy me.

The thing is it works fine if the source works correctly (which includes failing to play correctly). It may end up being a case of taking what I've learnt, wiping what I've done and having another crack at it. I don't know.

If you post a copy of `3.0.17`, I will apply the invoker fix for you in the meantime while I decide what to do. I'm short on time for a little while unfortunately.

**Comment by ReaLx3m** [comment] 2023-01-22 19:13
> Happens very occasionally. Probably one in 20 plays.

Sometimes it can happen more often for me, probably dependant on time of day and server load/availability, but sounds about right in general.

> It may end up being a case of taking what I've learnt, wiping what I've done and having another crack at it. I don't know.

Third time is the charm they say :). 

>If you post a copy of 3.0.17, I will apply the invoker fix for you in the meantime while I decide what to do. I'm short on time for a little while unfortunately.

[Here you go](https://1drv.ms/u/s!AnmxUFF1zODFgcAvWe_6c_4KbSROJA?e=eA8LmK). Appreciate the gesture. Check your reddit chat, pm'd you there.
And yeah do it on your own terms, always better to go in after all the knowledge has been properly digested. Its incredible what difference only passage of time makes in understanding a certain subject.

Btw these few days using 3.0.17 got reminded that it does work faster when going back to next episodes after episode has finished, no delay in resuming... If i remember correctly this is because it doesnt have that kodi spinning wheel suppression right? If so, even though not really an issue, maybe sacrifice bit of eye candy for speed? idk.
And watched status gets updated correctly with 3.0.17, its not only me with this issue on the newer builds right?

**Comment by Tikipeter** [comment] 2023-01-22 19:31
https://easyupload.io/b3zpiu

Hopefully that works OK. Never used that site for an upload. :)

**Comment by ReaLx3m** [comment] 2023-01-22 19:50
All good, downloaded, installed, invoker set to true. Will see how it fares.

**Comment by les017** [comment] 2023-01-22 20:44
> @Tikipeter Is this something that only im having a problem with..... 


Just throwing in here, no it's not only you.

But funny thing is when I get the exact same failure I also can't do ANYTHING in Kodi. I end up going HOME to Nvidia Shield, force close Kodi and clear cache. Then I can go back and select the same source and it almost invariably works just fine

@Tikipeter - let me know if a set of before and after logs of the failure/success would help you any

**Comment by Tikipeter** [comment] 2023-01-27 22:29
I'm (partially) throwing in the towel, at least for the time being.

Next update will have a setting to turn off successful playback monitoring. If monitoring is OFF, then as soon as the playback url has been fetched by FEN, the dialog window will close. Whether the file actually begins to play successfully won't be monitored.

Anyone relying heavily on Easynews as a source is encouraged to set this to OFF (disable the playback monitoring).

After much thought and some tinkering, I don't think it's possible to achieve the playback flow I want when dealing with Easynews. I cannot get around the "freeze" that happens when Kodi is first attempting to play back EN links. It means any inputs to close the window or skip the resolve etc are simply not being registered.

I've triple checked the monitoring code, and I'm as sure as I can be that it is correct. It is simply not reliable with these "freezes" on EN links.

Unfortunately, until I have some more time, the retry of EN links will also need to be disabled when monitoring is OFF. I WILL add this back, but I need a working resolve of EN in the interim.

I'll write here when I have the name and location of the setting.....

**Comment by Tikipeter** [comment] 2023-01-27 23:02
Settings->Playback->Playback Utilities->"Monitor For Successful Playback".

Default is ON,

**Comment by Nuklear92** [comment] 2023-01-27 23:17
> Settings->Playback->Playback Utilities->"Monitor For Successful Playback".
> 
> 
> 
> Default is ON,

Is this feature already on 3.0.39, or this coming in the next update?

**Comment by les017** [comment] 2023-01-28 13:26
@Tikipeter  -  just FYI, this used to be common occurrence for me but since . 38 I have not seen a single EN failure/hang. Sometimes the retry seems to take a long time, but it always moves on and completes. Just my experience...

**Comment by Nuklear92** [comment] 2023-01-29 13:37
> @Tikipeter  -  just FYI, this used to be common occurrence for me but since . 38 I have not seen a single EN failure/hang. Sometimes the retry seems to take a long time, but it always moves on and completes. Just my experience... 

Well, with me it's all the opposite. I'm using 3.0.39, when FEN fails to resolve EN links it just freeze the Kodi App completely and I have to Force Quit from the Apps Viewer list on the Shield. Pretty annoying, because that same link will then playback correctly when I start Kodi again. But the issue is having to restart Kodi pretty often if I end up choosing an EN link and it fails to resolve. 

Another thing, I'm using FEN with Nightly Builds from Kodi Omega v21.0 which have full support of Dolby Vision files as I watch a lot of content in that format. The only issue I have is the EN resolving links, everything else works good from FEN just like if I'd be using it in Kodi 20.0 Stable version, etc.

**Comment by Tikipeter** [comment] 2023-01-31 02:35
Next update has the new setting like I said above, but it may benefit you to check with it enabled first and see if the issues have resolved themselves as there are other changes in the code to try and fix this.

**Comment by Nuklear92** [comment] 2023-01-31 02:40
> Next update has the new setting like I said above, but it may benefit you to check with it enabled first and see if the issues have resolved themselves as there are other changes in the code to try and fix this.

Awesome! I'll definitely provide a feedback once I test it out.

**Closed** 2023-02-01 09:32 UTC
Labels: bug, pending update, I Give Up

**Comment by Nuklear92** [comment] 2023-02-01 19:48
Even though this issue is closed due to the new update option implemented in 3.0.40. I just wanted to say, that now Kodi doesn't freeze ever since I turned off monitor playback option under the Playback settings. Thanks for including tiny but helpful option to somehow make EN links resolve a bit more reliable! 👍
