### ISSUE TITLE
Autoplay resume significantly longer than using rescrape and selecting a source

### ISSUE THREAD

**Issue by unkn0wn234** [Tikipeter/repository.tikipeter#412] opened 2021-03-06 20:59 UTC
When clicking on a movie in the In Progress section of Fen, it takes significantly longer to play the movie than if I just use the context menu, use rescrape and select source and choose a source like that. I am on my PC in windowed at the moment so I do notice that in the first scenario (autoplay) I get a "Kodi Not Responding" for a bit before it goes away but from that point it still takes a while to play the movie compared to using source select w/the context menu. This also doesn't happen if I autoplay a movie that doesn't have progress in it or has already been scraped once before.

Kodiv18

Debug Log:
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/6096095/kodi.log)

**Comment by Tikipeter** [comment] 2021-03-07 21:22
I'll have to look into this. I have not noticed it myself, but I might see something when looking out for it.

**Comment by Tikipeter** [comment] 2021-03-08 14:35
Closing this as I cannot reproduce and there is nothing in the log to signify an error.

**Closed by Tikipeter** 2021-03-08 14:35 UTC
Labels: possible bug

**Comment by unkn0wn234** [comment] 2021-03-09 02:44
> Closing this as I cannot reproduce and there is nothing in the log to signify an error.

Might just be a device thing on my end then thanks for looking into it anyway !
