### ISSUE TITLE
Sort torrents by size (missing?) and Limit Quality issue.

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#213] opened 2020-05-20 17:58 UTC
I am missing a previous settings, or i am doing something wrong.
In the prevrious version i could sort by Provider (like 1337x on top etc), i can't find this setting anymore, it does sort everytime on size now (biggest GB on top).

Am i doing something wrong?

I think the setting was something like 'Sort torrents by size', i did disable that one in the previous version.

**Comment by Tinuz97** [comment] 2020-05-20 18:01
I still think the setting is gone, but i can do the same thing with 'results sorting' i guess,did set it on Provider, Quality,Size.
Still curious if i am crazy, or is the 'Sort torrents by size' gone?

**Comment by Tinuz97** [comment] 2020-05-20 18:04
Meh,it's not the same,before it did order them from Providers first (so 1337x on top), all 1080P files.
Then 1080P hoster, then 720P Torrents,after that 720P hoster.

Now is does all 1337x ontop, including 720P.

Any idea?

**Comment by Tinuz97** [comment] 2020-05-20 20:25
Also noticed that the filter for SD/720P/1080P/4K is not working.
I have 720P/1080P only enabled,still getting 4K and SD: 
![image](https://user-images.githubusercontent.com/47715606/82493753-c4056700-9ae8-11ea-86af-15e118033ede.png)

**Comment by Tinuz97** [comment] 2020-05-20 20:26
Settings: 
![image](https://user-images.githubusercontent.com/47715606/82493805-db445480-9ae8-11ea-9f47-102be8f17b75.png)

**Comment by Tinuz97** [comment] 2020-05-20 22:46
Also noticed a error for cleaning the open scrapers settings file, if you delete the folder (in user data,openscrapers) i noticed (after scraping) it does only create a cache.db file, not a settings.xml anymore ,just fyi.

![image](https://user-images.githubusercontent.com/47715606/82504771-7c88d600-9afc-11ea-8399-35684ce06256.png)

**Comment by Tikipeter** [comment] 2020-05-21 11:05
Hi Tinuz. :)

* The easy one first. Non creation of Openscrapers settings after deletion of userdata folder. That will be fixed next update.

* Fen not honoring quality filter. I cannot for the life of me replicate this issue, whatever qualities I have set, they are the only ones displayed. Make sure you hit OK to exit settings after setting this. I might need more info on this issue.

* The "Sort torrents by size" missing setting. I did clean up settings with the last update, and this setting was a casualty. The setting was now inaccurately named (all results were sorted by size, not just torrents), so I removed it along with "Sort Torrents to Top".
I've added a couple of extra options for "Results Sorting" that should satisfy the sorting you want. I'll include that with the next update. The setting that will correspond to your sorting preference will be **"Quality, Provider, Size"**.
Let me know if it provides the same sorting as you used to have...

**Comment by Tinuz97** [comment] 2020-05-21 11:28
I'm going to try to wipe Fen in the userdata folder, and set it up clean again (for testing the quality filter).

I will report back asap.

**Comment by Tikipeter** [comment] 2020-05-21 11:38
Hang, on!! I miss spoke. Wait until I push an update. Those extra sort setting aren't included yet!!!

**Comment by Tikipeter** [comment] 2020-05-21 11:38
The "Quality, Provider, Size" setting won't do what you want it to until I push the update!!!!

**Comment by Tinuz97** [comment] 2020-05-21 11:40
I know, but testing the quality filters, the issue that it is still showing 4K and SD (720/1080 only enabled).

I wiped settings (removed Fen in the userdata folder, windows 10),and did setup it again. 

Going to test now.

**Comment by Tinuz97** [comment] 2020-05-21 11:42
Yep,still the same issue 
![image](https://user-images.githubusercontent.com/47715606/82555865-e8088d00-9b68-11ea-8a22-998140d57017.png)

**Comment by Tinuz97** [comment] 2020-05-21 11:43
i can (if you want) edit my setting file in userdata (remove my realdebrid and trakt auth), so you can  try the settings i have ,maybey a idea?

**Comment by Tikipeter** [comment] 2020-05-21 11:46
That's a good idea.

**Comment by Tinuz97** [comment] 2020-05-21 11:48
but test it clean,so backup the Fen folder you have,and use a clean one,copy/paste my settings 👍 
Maybey you see a setting that does disturb the filter that needs to remove SD and 4K (like in the past with a other issue i had)

**Comment by Tinuz97** [comment] 2020-05-21 11:50
I think i wiped all the Trakt and Realdedrid id's (i hope lol,i trust you with it,but more for the lurkers in here), can you check that please first, if there is still something in it,i remove the message
[settings.zip](https://github.com/Tikipeter/repository.tikipeter/files/4662269/settings.zip)

**Comment by Tikipeter** [comment] 2020-05-21 11:52
It looks fine, but I've removed it anyway, just in case.

**Comment by Tikipeter** [comment] 2020-05-21 12:07
Bad news. It works fine for me. I cleared the userdata folder, put your settings in there, enabled RD so I got some decent results, and ran a search...

![screenshot000](https://user-images.githubusercontent.com/28930002/82557212-a8fd2a80-9bae-11ea-85ed-7a382d88abcf.png)

I did however have this at the bottom of the results:

![screenshot001](https://user-images.githubusercontent.com/28930002/82557312-d518ab80-9bae-11ea-880f-7820961556ea.png)

**A couple of 'SD' results snuck in even though that quality is OFF in the filters.**

Does it look to you like you are getting 'some' wrong qualities come through, but not all? i.e. It's filtering out 'most' of the 4K, SD results, but not filtering out ALL of them. It looks to me like that might be what's happening.

To test, I'd turn on the 4K and SD filters, and see if you get a LOT more of them after that. If that's the case, then the filters are generally working, but for some reason some rogue results are getting through the filter.

**Comment by Tikipeter** [comment] 2020-05-21 12:09
Looks like there's something wrong with the filtering of 'hoster' links from what I can se. This gives me something to go on....

**Comment by Tinuz97** [comment] 2020-05-21 12:10
The weird part is,i don't see a 'limit quality' in the settings.xml, or is it named diffently?

**Comment by Tinuz97** [comment] 2020-05-21 12:12
plugin.video.fen-1.6.21c.zip, is that the one before all those changes? otherwise i am going to test that one, because i realy never did see a SD or 4K slipping true the filter :)

**Comment by Tikipeter** [comment] 2020-05-21 12:13
The setting is "results_quality".
If you use autoplay, there is a seperate setting: "autoplay_quality"

**Comment by Tinuz97** [comment] 2020-05-21 12:17
i tested Jumanji also (did scrape it 2 times,to make sure all the working scrapers are getting used), but same results,weird (clean Fen). 
![image](https://user-images.githubusercontent.com/47715606/82558261-90b8eb80-9b6d-11ea-9170-8c949064b78f.png)
I closed kodi,to make sure the settings are saved, look at the settings, but they are on 720p/1080P ,so they did get saved(by hitting the OK button)

**Comment by Tikipeter** [comment] 2020-05-21 12:17
plugin.video.fen-1.6.21c is the one before changes, yes.

With the info I've got to go on, I should be able to sort it out if you don't want to do more testing. There'll be a problem somewhere with the logic I'm using for the filter. They are probably getting removed at the 'quality' section, and re-added at another section. I'll sort it out...

**Comment by Tinuz97** [comment] 2020-05-21 12:17
going to test on my phone now,maybey it has something to do with windows? :P

**Comment by Tinuz97** [comment] 2020-05-21 12:22
This is funny. Did the same step on my (Android) phone,so wiped the Fen folder in userdata, used my settings from the computer (that i posted here), and Android does not have this issue, weird.

**Comment by Tinuz97** [comment] 2020-05-21 12:23
So same movie (jumanji), scraped it 2 times, No SD or 4K are slipping true (with the same setting file).

**Comment by Tikipeter** [comment] 2020-05-21 12:26
Interesting. Were there Hoster results that were successfully filtered?

**Comment by Tinuz97** [comment] 2020-05-21 12:28
Installed version 1.6.21c ,clean settings (in Fen,not the file), wiped all caches,issue gone on windows (scraped 2 times also). Also scraping much faster (form me) and 'check realdebrid' after scraping much faster in 1.6.21c also (windows 10). 

The result with 2x scraping jumanji (No SD or 4K are coming true the filter)
![image](https://user-images.githubusercontent.com/47715606/82559140-5fd9b600-9b6f-11ea-9802-6faa5623e689.png)

**Comment by Tinuz97** [comment] 2020-05-21 12:31
> Interesting. Were there Hoster results that were successfully filtered?

like this? (1.6.21c) 
![image](https://user-images.githubusercontent.com/47715606/82559327-b8a94e80-9b6f-11ea-823d-3ee058cbe880.png)

**Comment by Tikipeter** [comment] 2020-05-21 12:32
Yeah. So 1.6.21c is good, then there were changes. I'm logging results now to see where the issue is...

**Comment by Tinuz97** [comment] 2020-05-21 12:32
this is weird,now they are between torrents,lol. (but SD and 4K are gone like it should). i think the downgrade did mess up this? (hosters between torrents,did never see that)
![image](https://user-images.githubusercontent.com/47715606/82559363-cfe83c00-9b6f-11ea-8075-c9724b271230.png)

**Comment by Tinuz97** [comment] 2020-05-21 12:33
Maybey something in the code does not like WIndows 10, because i do not have this issue on my phone (with the latest version,same setting file)

**Comment by Tikipeter** [comment] 2020-05-21 12:49
I think I've got all these problem sorted. I'll do some testing and then push an update.

As for the speed, I changed things in those 1.6.21a/b/c updates to improve speed, which it did for me (quite a bit). But, there was an issue posted here where the user was having the scraper hang for 10+minutes after the changes, so unfortunately I had to revert those speed increases. 🤦‍♂️ Unfortunately, lower powered devices (Firestick/FireTV etc) can't handle the threading I used to speed up scraper preperations. It was a big bummer.

**Comment by Tinuz97** [comment] 2020-05-21 12:51
That is why I like my nvidia shield tv.
People say 'it is overkill for just streaming', well I do like speed, lol.

**Comment by Tikipeter** [comment] 2020-05-21 13:36
I'm having troubles (Fen's Internal Sources makes this harder than it should be).

If you're waiting around for the fix, it's probably going to be a while now. :(

**Comment by Tinuz97** [comment] 2020-05-21 13:50
No problem, no need to hurry.
✌️

**Comment by Tikipeter** [comment] 2020-05-21 15:09
Man, that was rough!

I think I've fixed everything, and tested all the sorting/filtering combinations. But I sure have been wrong in the past.

To get the sorting you used to like, I think you need to set "Results Sorting" to "Quality, Provider, Size" (I know you had this set already, but it behaves differently now). There are some new ones there if you want to try them out. Be sure to hit OK to exit settings after setting the sort, otherwise the chosen setting won't stick.

It seems also that the filtering is now working properly, and there is also the setting to "Include Results with Unknown Size", if you filter by size, which can be toggled on/off (this is mainly for hoster results, pretty much all torrent results now report size).

I'll upload the changes in a second (v.1.6.23)

Let me know if you have any troubles.....

**Comment by Tinuz97** [comment] 2020-05-21 15:10
Will test it later today, bbq time 😄

**Comment by Tinuz97** [comment] 2020-05-21 23:48
On the phone it does work nice (I like the new options for sorting, great!)
On my computer I will test that tomorrow, I had to much beers for testing properly lol).

**Comment by Tinuz97** [comment] 2020-05-22 11:02
Working 100% @Tikipeter ,no more 4K and SD (tested same movies, scraped them twice) on windows 10. Also first torrents 1080P, then Hosters 1080P, then 720P torrents,then 720P hosters like before 💯 🥇

**Comment by Tikipeter** [comment] 2020-05-22 12:48
Awesome. Thanks Tinuz. 👌

**Closed by Tikipeter** 2020-05-22 12:48 UTC
Labels: bug, enhancement, pending update
