### ISSUE TITLE
Not sure if it's the skin or Fen, but...

### ISSUE THREAD

**Issue by ambulancePilot** [Tikipeter/repository.tikipeter#33] opened 2022-09-12 14:56 UTC
When I turn on pagination, page 2 lags and drops my FPS on my screen considerably while locking up the device. It has to do with the "Jump To" item. When it is visible on the screen, everything is extremely slow as if the CPU is at 100% (I can't confirm this since I use a Fire Stick and CPU usage is unavailable through Kodi). If I manage to scroll past the Jump To item, all of a sudden as if a switch is flipped, everything is smooth again.

I'm less interested in figuring out the problem and more interested in if there is a way to just get rid of the "Jump To" item as I just require simple pagination and have no need to jump to anything except the next page. I seem to remember there was an option to enable/disable to Jump To item independent of the pagination setting?

If that's not possible, then what could be causing Kodi to lock up when pagination is set to on and the Jump To item is visible on the screen?

Thanks for the great add-on and any help you can provide. I am using the Arctic Horizon 2 skin, if that helps figure it out. It might just be related to the skin, I am not sure.

**Comment by ambulancePilot** [comment] 2022-09-12 15:11
http://paste.kodi.tv/ovilofoneh

I turned pagination on, then restarted Kodi, loaded page 2 of my trakt list that I have a widget of, and everything locked up as expected when the Jump To item was visible. When I scrolled past it (to item 2 or 3) it seems to resolve and everything is fast again.

One thing to note is that I have my skin set to 100 items max for this widget, but the behavior is the exact same whether I set my skin widget to unlimited items and let Fen do the pagination or not. If you want a log file with the widget set to unlimited items with Fen pagination on, let me know and I can provide.

Thanks!

**Comment by ivarbrandt** [comment] 2022-09-12 19:55
I have an NVIDIA Shield TV Pro and the exact same thing has been happening to me. I think I noticed it when the alphanumeric Jump To feature was implemented. I asked for this feature though and it's awesome cause my collection is quite big.

For me it only slows down when the "Jump To' is either highlighted or just on the screen. Once I scroll away from the "Jump To" item it goes back to normal. This is happening on all skins including Estuary.

**Comment by ambulancePilot** [comment] 2022-09-12 19:58
Thanks for the reply. I noticed it around the same time that new feature became available as well, but I couldn't be sure. Good to know it's not skin related. For now I've turned pagination off but would prefer to have it on as I notice it improves load times (obviously).

**Comment by Tikipeter** [comment] 2022-09-12 21:24
Get the easy stuff out of the way first..... I'll add a setting to exclude the "Jump To.." item altogether for next update.

Apart from that, I'm a little confused. The "Jump To.." item should NOT be appearing on widgets, at all. Yet you mention widgets quite a bit in your posts. Is the "Jump To.." item showing within widgets? Hopefully not as there's code to stop that from happening.

Can you leave the pagination on, and see if your Trakt Collection or Watchlist exhibit the same behavior with regard to the Jump2 item? I'm thinking they may behave correctly, whereas the other Trakt lists don't. Can you confirm this please, as I cannot make this happen on my Windows install I'm testing on.....

**Comment by Tikipeter** [comment] 2022-09-12 21:30
I'll install AH2 and have a look as well. I think I know what the issue is so I'd like to experience it myself for testing.

**Comment by ambulancePilot** [comment] 2022-09-12 21:31
Thanks so much for including that option to get rid of the jump to item all
together. That's much appreciated.

Sorry about the confusion regarding widgets. You can ignore the widgets all
together, as the same behavior is there when accessing the Trakt lists
through Fen directly.

The jump to item does not appear in widgets at all. Sorry for the confusion
there.

As for the testing you asked for, I will do it when I get home this evening
and share my results. Thanks again.

**Comment by Tikipeter** [comment] 2022-09-12 21:34
It's OK. Don't worry about the testing.

I just installed AH2 and the issue is what I thought it was. It's a one line fix and will be in the next update.

I won't wait too long to push the update. Maybe a day to finish up a few other things that need doing..

**Comment by Tikipeter** [comment] 2022-09-12 21:49
Anyone wondering about the issue...

Fen, of course, sets the contents of these Trakt list containers as either movie or tvshow. Up to date skins, through Kodi, want info (metadata) set for each item within that list. Of course the Jump2 item doesn't have any info to set. Either way, Kodi still wants it to be set, even as an empty `dict`. If not set, it seems Kodi isn't happy for at least a few seconds whilst it looks for that info.

I had fixed this in the general Movie and TV Show modules, which cover most all lists, but hadn't fixed it in the Trakt indexers module, which handles other types of personal Trakt lists e.g. "Liked" lists, or your "Personal" lists.

I wasn't experiencing it because I have a very old personal skin that doesn't care whether that info is set or not.

**Comment by Tikipeter** [comment] 2022-09-12 22:06
![screenshot00000](https://user-images.githubusercontent.com/28930002/189766849-851ad73e-404c-4a87-b741-896f2b35230c.png)


Set this to OFF to turn off the Jump2 item after next update.

**Comment by ambulancePilot** [comment] 2022-09-12 22:29
Thanks so much! 🙌 That's just awesome. I'm glad you figured out the lag issue as well. Brilliant.

**Comment by ivarbrandt** [comment] 2022-09-13 00:06
> Anyone wondering about the issue...
> 
> Fen, of course, sets the contents of these Trakt list containers as either movie or tvshow. Up to date skins, through Kodi, want info (metadata) set for each item within that list. Of course the Jump2 item doesn't have any info to set. Either way, Kodi still wants it to be set, even as an empty `dict`. If not set, it seems Kodi isn't happy for at least a few seconds whilst it looks for that info.
> 
> I had fixed this in the general Movie and TV Show modules, which cover most all lists, but hadn't fixed it in the Trakt indexers module, which handles other types of personal Trakt lists e.g. "Liked" lists, or your "Personal" lists.
> 
> I wasn't experiencing it because I have a very old personal skin that doesn't care whether that info is set or not.

Thanks so much for taking a look at this. Like you said it was only happening on Trakt lists like Collection and Watchlist.
I'm confused about something tho. I really do like pagination and the JumpTo feature. I use it along with the Alphanum sorting. So will setting it to off no longer let you use pagination and the JumpTo feature? Or will it just turn off the need for the JumpTo item in the list to gather metadata?

**Comment by Tikipeter** [comment] 2022-09-13 01:41
OFF will mean the lists are paginated, but there will be no "Jump To..." at the start of the lists.

You just need to keep the setting you currently have and it will be fine.

**Comment by ivarbrandt** [comment] 2022-09-13 01:58
Ok awesome. Thank you!

**Closed** 2022-09-13 20:42 UTC
Labels: bug, pending update

**Comment by ivarbrandt** [comment] 2022-09-15 01:53
Thank you so much for trying to fix this. Unfortunately, the issue persists after the update to 3.0.12. It is mostly noticeable in the Trakt TV Shows Collection. When hovering over the Jump To item in that list, FEN becomes almost non-responsive. I thought it could be because I'm running Nexus but I checked and the behavior is the same on Matrix.

Please let me know if you would like a log.
