### ISSUE TITLE
Fen wont save trakt or realdebrid account info !

### ISSUE THREAD

**Issue by ramoun** [Tikipeter/repository.tikipeter#269] opened 2020-09-28 11:48 UTC
Hi, im a long time user of fen  Started having trouble a week or so ago on W7.
Decided to remove fen and kodi, install a fresh etc.
With the latest release of fen it wont save trakt or real debrid for some reason.  It enters ok get approval from trakt and RD. But when you go to search a movie no results.  Then go back in to have a look at external accounts it is no longer registered with Trakt or RD.
Any pointers would be greatly appreciated, as its school holidays and the kids are climbing the walls.
Cheers

**Comment by Tikipeter** [comment] 2020-09-28 13:01
Download an older version of Fen from this github until the issue can be sorted. I am closing this as it is a duplicate of a current open issue.

**Closed by Tikipeter** 2020-09-28 13:01 UTC

**Comment by ramoun** [comment] 2020-09-28 21:50
Many thanks, I can see that thread now.

Thank you for your dedication and all your hard work, its greatly appreciated by everyone, even if most people dont say it. :-)
