### ISSUE TITLE
fen not working in any kodi version on Apple Tv 4k (2022 model)

### ISSUE THREAD

**Issue by alon2023** [Tikipeter/repository.tikipeter#191] opened 2023-03-22 21:08 UTC
i have real debrid account and it's 100% connect to Fen. when i try to play something (movie or T.v show) in my kodi 20.1 which installed on my apple 4k tv there is an error that's said "playback faild". 

link to log : https://paste.kodi.tv/vofocixobe

**Comment by TwilightMercy** [comment] 2023-03-22 21:11
I can add that same behavior happens on my apple tv also. Latest Fen, tried kodi 19.5 and 20.1. 

![image](https://user-images.githubusercontent.com/29895680/227039201-af9bcae3-4e18-4e73-b3a5-fea1bbb3b2e8.png)

**Comment by Tikipeter** [comment] 2023-03-22 21:32
Turn OFF Settings->Playback->Playback Utilities->Monitor For Successful Playback.

If that doesn't solve the issue,  turn ON Settings->General->Wait for Fen Services to Initiate Before Making Widgets. Then restart Kodi.

If that doesn't work then it might be time to look to a different device.

**Comment by TwilightMercy** [comment] 2023-03-22 21:49
I tried both options, and still “Playback failed”. 

Is this behavior specific for Apple TV? does his log helps you understand anything?

I’ve noticed this error line:
`###error in make_settings_dict###: [Errno 2] No such file or directory: '/private/var/mobile/Containers/Data/Application/D21A73FF-98D7-490E-87D4-91AF3A41C4BD/Library/Caches/Kodi/userdata/addon_data/plugin.video.fen/settings.xml'`

**Comment by Tikipeter** [comment] 2023-03-22 21:54
Yes, that thing you have quoted.

An addon can't work properly if Kodi can't even access it's settings file.

I've seen this 3 times on Apple TV devices now.

**Comment by TwilightMercy** [comment] 2023-03-22 22:02
I see. 

I’ve noticed new behavior. regular playback from movies menu - playback failed. 
from Real Debrid history. Works. 

Video:
https://streamable.com/u5p2l4

**Comment by Tikipeter** [comment] 2023-03-22 22:21
That's great and all, but does it have access to it 1.5 seconds after Kodi initializes. Because that is what is needed here. I'm using the exact same path.

**Comment by SoulReaverFan** [comment] 2023-03-22 22:29
> That's great and all, but does it have access to it 1.5 seconds after Kodi initializes. Because that is what is needed here. I'm using the exact same path.

I’m not sure about that one, but just wondered about the path because of the very specific path that was showing in the log with the error. 

I hope it’s possible to fix the issue. Fen is such an awesome addon it would be a shame not to have it work on tvOS. I think the platform will be even more attractive sometime with tvOS 17 when Apple gets forced to make sideloading and 3rd party app stores available and without restrictions to developer accounts for the general public because of the EU regulations. It’s definitely really fast performance wise to use Kodi on this platform.

Btw love the new UI updates to Fen! Looks so clean 😃👍

**Comment by TwilightMercy** [comment] 2023-03-22 22:39
True I agree, Fen on tvOS will be dope. 

I tried just for testing to install “The Promise” + RD account and it worked. 

Is there any way to make a specific fix for Fen + Apple TV only as a workaround for accessing the settings?

**Comment by Tikipeter** [comment] 2023-03-22 23:05
I've done that already (a workaround), and it seems to work. Although the next update did have some "fine tuning" for that code already.

I've managed to quite quickly fix this playback issue on devices that are using this current workaround, which in my experience is predominantly these Apple TV devices.

Long story, since the three of you are quite invested in this:

Fen uses a cached (in RAM, through Kodi's window property assignment method) dictionary of all user's settings. This is made during Fen's startup services, and remade after a settings change. These services are run as soon as Kodi has done a few things when starting up. So for the Apple TV, usually 1-2 seconds after Kodi starts, it begins running all installed addon's services. There is a very significant increase in speed of accessing a user's settings through this cached method, as Kodi's default method of accessing settings is VERY slow. It is an important feature in enabling the speed of Fen, as there could be 10-20 settings needed for a single action within Fen.

The issue for Apple TV's is, at the start of the startup process, Kodi returns a "file does not exist" for the 'settings.xml' file. Which means the dictionary doesn't get assigned to RAM, as Fen can't read the contents. Fen has a fallback when that is the case. It will use Kodi's traditional method of accessing settings, and forego the much quicker method. This is much slower, but it will mean the Apple TV and Fen will still work OK together.

In regards the playback error here, it is to do with a setting I removed last(?) update. The code was still asking for a value for that setting. If the normal cached method of fetching the setting value is used, then there is code to return a default value if the setting returns nothing, as it would in this case as it no longer exists. But, when using Kodi's default method to get a setting, there is no way to assign a fallback value if the setting doesn't exist. Which is fair enough, because why would an addon ask for a setting that doesn't exist?

Anyway, because Kodi is returning `''` as the value for that setting, and I'm trying to turn that setting into an integer as the next step, then the code fails.

So hopefully next update Apple TV users can plug along with only slow settings as the consequence, and playback will work again.

**Comment by SoulReaverFan** [comment] 2023-03-22 23:15
I love these detailed explanations! Learned something new! 👍 Thank you so much! Looking forward to the update 🙂

**Comment by TwilightMercy** [comment] 2023-03-22 23:30
Thanks!!
Please keep the issue open, I’ll update here when it will be released.

**Comment by Tikipeter** [comment] 2023-03-23 00:28
3.1.05 is released and should fix this issue..

**Comment by SoulReaverFan** [comment] 2023-03-23 05:17
> 3.1.05 is released and should fix this issue..

Tested just now and I can confirm that the issue is fixed. Thanks again! 😃👍

**Closed** 2023-03-23 06:16 UTC
Labels: bug, pending update
