### ISSUE TITLE
[Request] Potential to add a Fen Source Select player option for openplayers/tmdbplayers? (Or a go to next source option for auto play)

### ISSUE THREAD

**Issue by Logs22** [Tikipeter/repository.tikipeter#396] opened 2021-02-22 19:13 UTC
Hello Tiki! I have recently switched to mainly using library integration, with Fen as the primary player for the items. I ran into an issue of when using auto play, it found a cached source and attempted to play the file, but it failed resolving, and kicked me out to the home screen of kodi. **_A fix I thought up for this would be to either skip the failed resolving source and go to the next source in line_**, or to have a source select player option so I can manually skip this source. would like to hear your thoughts about this, if its even possible :)

Random log - https://paste.kodi.tv/idoteyemoz

**Comment by Logs22** [comment] 2021-02-22 21:25
found this post https://github.com/Tikipeter/repository.tikipeter/issues/356, ignore the part about a player, but maybe the part about going to the next source could still apply?

**Comment by Tikipeter** [comment] 2021-02-26 15:28
Fen already implements a system to try the next result if the current result doesn't resolve. The issue is the file IS resolved by Fen, then passed to Kodi's player. It's then out of Fen's hands. If Kodi can't play the link, then this will happen.
This has unfortunately always been the way it works, going all the way back to Genesis and SALTS.

**Closed by Tikipeter** 2021-02-26 15:28 UTC

**Comment by Logs22** [comment] 2021-02-26 15:55
ah alright, i only had the issue like one time, didn't know if that was anything that you could help. Thanks for the explanation!
