### ISSUE TITLE
Fen 1.21.1b Playing TMDBH Library Files does not play with Autoplay, and setresolvedurl playback method

### ISSUE THREAD

**Issue by mathu204** [Tikipeter/repository.tikipeter#340] opened 2020-12-06 22:37 UTC
Continuing from here now I get the scraping dialog but it doesnt seem like it picks a file where it says something aloen the lines of RD Cached in a Pink colour, unless the way it is done was changed slightly. Anyways it scrapes I dont know if it finishes or not but it doesnt play anything. Out of about 5-6 attempts, when I browsed into the show manually and played it it did play once. It was an episode of seinfeld.

https://github.com/Tikipeter/repository.tikipeter/issues/336

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5649663/kodi.log)

**Comment by Tikipeter** [comment] 2020-12-06 23:08
Is autoplay in Fen enabled?

**Comment by mathu204** [comment] 2020-12-06 23:08
> Is autoplay in Fen enabled?

Yes

**Comment by Tikipeter** [comment] 2020-12-06 23:19
Turn it off and try again.

If not good still, switch the setting for TMDbH playback method for the Fen player and try again.

**Comment by mathu204** [comment] 2020-12-06 23:37
Changed the Playback method first as I would prefer to keep autoplay :p, it works. However I notice a few things, it scrapes and plays noticeably slower than Fen 1.20, it also does not save resume points in library anymore, I will change autoplay off and revert the playback method and update.

**Comment by mathu204** [comment] 2020-12-06 23:41
Changed it to Source Select, works, and also seems to scrape and play faster, but still a bit slower than 1.20, I do like the new Links dialog it looks really clean great work on that! Keeping the old Playback method also lets me keep my resume points so I will go with the lesser of the 2 evils haha.  I guess I will get to see your beautiful Links dialog, since keeping the resume points is a priority for me. I will upload a log from me changing these settings and the results if it will be of any help to you, and I hope you can get the autoplay working. I will update the bug title to say that this bug only happens with autoplay and setresolvedurl on TMDB.

**Comment by Tikipeter** [comment] 2020-12-06 23:57
I'm going to have to install TMDbHelper to get to the bottom of all this I'm afraid.

**Comment by mathu204** [comment] 2020-12-07 00:12
> I'm going to have to install TMDbHelper to get to the bottom of all this I'm afraid.

If you do, I would really appreciate it you always go above and beyond.

**Comment by Tikipeter** [comment] 2020-12-07 00:39
Findings aren't good for you, I'm afraid......

Firstly, I went into the TMDbH player settings and set `is_resolvable` to TRUE by choosing `setResolvedURL` for the Fen player.

Then I played some media from WITHIN the TMDbH addon, both trying autoplay and not. Everything worked fine.

Then I added a movie to my test Kodi library from TMDbH, and started playback trying both autoplay and not. Everything worked fine.

Then I added a TV Show to my test Kodi library (The Mandalorian) from TMDbH, and started playback of S01E01 trying both autoplay and not. Everything worked fine.

Then I skipped forward playback of both the movie and an episode so that a resume time was set. Both times my Kodi library item was set with a resumetime. Everything worked fine.

Then I selected each of those items again, and they played back from the resume time already set. Everything worked fine.

Then, using autoplay, I enabled Next Episode in Fen and then played S01E02 of The Mandalorian. Autoplay worked fine again. Towards the end, the Notification popped up telling S01E03 was ready to play. Upon completion of S01E02, it was marked as watched in the Kodi library correctly, and automatic playback of S01E03 began. Everything worked fine.

I'm afraid, once I set the TMDbH Fen player setting to TRUE for `is_resolvable`, everything I did worked perfectly.

That means there's something wrong in your setup.

**The main thing for you to do now, is delete that `metacache6.db` file in the addon_data/script.module.tikimeta folder, and restart Kodi and let tikimeta make it again. That is the only thing in your log that looks like an error. I'm hoping, because nearly all the functions to do with playback and marking watched/unwatched needs correct metadata, this might solve your issue.**

**Comment by mathu204** [comment] 2020-12-07 00:40
> Findings aren't good for you, I'm afraid......
> 
> Firstly, I went into the TMDbH player settings and set `is_resolvable` to TRUE by choosing `setResolvedURL` for the Fen player.
> 
> Then I played some media from WITHIN the TMDbH addon, both trying autoplay and not. Everything worked fine.
> 
> Then I added a movie to my test Kodi library from TMDbH, and started playback trying both autoplay and not. Everything worked fine.
> 
> Then I added a TV Show to my test Kodi library (The Mandalorian) from TMDbH, and started playback of S01E01 trying both autoplay and not. Everything worked fine.
> 
> Then I skipped forward playback of both the movie and an episode so that a resume time was set. Both times my Kodi library item was set with a resumetime. Everything worked fine.
> 
> Then I selected each of those items again, and they played back from the resume time already set. Everything worked fine.
> 
> Then, using autoplay, I enabled Next Episode in Fen and then played S01E02 of The Mandalorian. Autoplay worked fine again. Towards the end, the Notification popped up telling S01E03 was ready to play. Upon completion of S01E02, it was marked as watched in the Kodi library correctly, and automatic playback of S01E03 began. Everything worked fine.
> 
> I'm afraid, once I set the TMDbH Fen player setting to TRUE for `is_resolvable`, everything I did worked perfectly.
> 
> That means there's something wrong in your setup.
> 
> **The main thing for you to do now, is delete that `metacache6.db` file in the addon_data/script.module.tikimeta folder, and restart Kodi and let tikimeta make it again. That is the only thing in your log that looks like an error. I'm hoping, because nearly all the functions to do with playback and marking watched/unwatched needs correct metadata, this might solve your issue.**

I deleted the cache file I will try it again and get back to you hope thank you for taking the time to try it out my friend

**Comment by mathu204** [comment] 2020-12-07 01:22
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5649880/kodi.log)

not sure what happened but now it seems to play 2/3 times i got one error if u can take a look, i didnt even delete the cache file yet but im gonna do that right now and get back

**Comment by mathu204** [comment] 2020-12-07 01:30
Okay i think it seems to work for now, I will close this and make a new one if it persists thank you. I deleted the metacache again, I must say tho for whatever reason it feels like it scrapes and plays a bit slower than the previous updates, and even opening paths such as Upcoming, or Next Up in Fen take longer.

**Comment by mathu204** [comment] 2020-12-07 01:33
For the shows that I made the bug issue for such as Kill La Kill that were not working even before the 1.21 updates, they still dont work I will post the log for that show in that issue, my other shows that were working before the update, now work again. Thanks

**Comment by Tikipeter** [comment] 2020-12-07 23:16
I added Kill La Kill to my kodi library using TMDbHelper.

It played correctly, marked a resume point correctly, and marked as watched correctly. There was the error from TMDbH when adding it, but all 24 episodes were added anyway, and they then scanned into my library correctly.

**Comment by mathu204** [comment] 2020-12-08 00:20
Responded to your earlier comment on the other issue Did you delete the metacache6.db file? Because there are still errors in there for that.

Also, go to Tools and clean your settings file. There are a lot of old settings Kodi is looking for. Your whole install looks like a mess to be honest.

I added Kill La Kill to my kodi library through TMDbHelper, and it played, marked progress and marked watched correctly every time.

I'm going to close this issue and keep the other issue open for these problems.

I did a fresh install actually so i am not sure why this is happening, yes i also deleted the metacache.db, you know what maybe i should just fresh install again and see if that will solve anything. if i still get the error i willcome back

**Comment by Tikipeter** [comment] 2020-12-08 00:33
Make sure you delete your userdata folder when doing a fresh install. I assume that's what you mean though.

**Comment by mathu204** [comment] 2020-12-08 00:34
> Make sure you delete your userdata folder when doing a fresh install. I assume that's what you mean though.

Yea I delete everything

**Comment by mathu204** [comment] 2020-12-08 04:23
Okay Fresh Installed, this is the error log i got, Autoplay enabled and setresolvedurl, i think its a huge log cause I fresh installed and setup everything in one go, but playing the episode of Kill La Kill is the very last thing I did, it looked like it scraped, chose a source, and then i got hung on a loading screen forever, i pressed back and got this playback error. 

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5656831/kodi.log)

**Comment by mathu204** [comment] 2020-12-08 04:34
Disabled autoplay, selected a source, but nothing happens. again this is all off a new completely fresh install I went to %appdata% and deleted the whole Kodi folder and reinstalled all addons, and skin from scratch as well as resyncing all my debrids, api keys, etc.

I also played an episode of Seinfeld to see if it works as well for some reason it didnt play the first time but i got that little playing sign though, upon trying again it played, as well as the 1-2 times after that to make sure, Now i went back to Kill La Kill again play an episode but nothing happens. 

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/5656870/kodi.log)

**Comment by mathu204** [comment] 2020-12-08 04:45
Hey Tiki, so I figured out what the real problem is since i was only getting 2 sources for this KLK episode, probalby due to my soure settings leaving out SD or whatever, the sources Fen were trying to play were broken leading me to believe something was wrong with Fen when it was really jsut the source being played. I also realized some of my cloud files were incorrectly named, so upon renaming them correctly my cloud files for KLK played fine from the library using Fen, the other show that wasnt working (Midnight Gospel) also worked fine WITHOUT cloud files. 

So the takeaway here it was just a case of some bad files haha sorry for all the trouble, I do have a feature request based out of this problem so you can close this after your respone whether its a yes or no. Can you make a feature like Seren where it automatically plays the next link after one does not work, or takes too long (maybe a user determined time or something)? 

Anyways thank you for troubling yourself to help me so much with all of this Fen and you are the greatest :D

**Comment by Tikipeter** [comment] 2020-12-08 17:48
Fen already will move onto the next result if a link fails to **resolve**. The problem looks like the link did resolve (because you got the little "playing" icon), but then Kodi failed to play the resolved link.

The problem is that once the link is resolved, Fen's job is done. It sends the playable link to Kodi's player, and Kodi attempts to play it. There isn't really anything Fen can do at that point.

**Closed by Tikipeter** 2020-12-08 17:48 UTC
