### ISSUE TITLE
Trakt In Progress TV Shows Issue

### ISSUE THREAD

**Issue by SpTec** [Tikipeter/repository.tikipeter#64] opened 2019-11-25 13:35 UTC
Hey tikipeter

Not sure an issue with Fen or just me, my in progress tv shows lists in alphabetical order and shows all seasons and episodes rather than only the seasons and episodes I haven't watched. I have recently watched as the sort order in settings so not sure if I ma missing something somewhere

any other addons I have used with Trakt My in progress has worked as described above with no issues not sure why Fen maybe different

Any insights would be great. Thanks

**Comment by Tikipeter** [comment] 2019-11-25 17:15
I think you want "Next Episodes".

**Comment by SpTec** [comment] 2019-11-25 20:44
I did try that but it also shows episodes that I have already watched, plus it doesn't seem to play nice in a widget as it doesn't refresh when an episode is finished so I can select the next episode.

**Comment by Tikipeter** [comment] 2019-11-25 21:23
It's definitely not meant to show items already watched, and it definitely is meant to refresh when an episode is finished. There is something going wrong in your setup.

Assuming you are using Trakt, do you have Settings->Playback->Indicators set to 'Trakt'?

Assuming you are using Trakt, make sure Settings->General->Trakt Navigation & Cache->Trakt Cache Duration is set set to '1 Hour'. Also, reset the Trakt Cache using Tools->Clear List and Data Info->Clear Trakt Cache.

Does the episodes you've already watched that are showing in Next Episodes have a 'watched' check mark on them?

Is Fen actually marking an episode as watched when it has finished playing?

**Comment by SpTec** [comment] 2019-11-26 00:29
Ok had a bit of a play tonight, if you go to next episodes via the addon, after an episode is finished and you go back from the scraped links it does refresh and the next episode of that show is at the top ready to play
 this doesn't happen in the widget I am guessing because the scraper results appear in a dialog box rather than a directory listing,  fen seems work differently to other addons in this respect as I have my in progress setup with 2 other addons and when you select the episode it then goes to a list of the episodes you then select episode it scrapes and then the results are in a directory listing which then refreshes when you go back after the episode finishes

Hope that makes sense 
And the settings you mention are all correct and have cleared cache more than several times
Sorry too be a pain

**Comment by Tikipeter** [comment] 2019-11-27 13:43
The helper scripts your skin uses will refresh widgets after certain Kodi actions, which includes after playback. So Fen showing results as a dialog does not affect this, although it was reasonable to assume that was the problem.

(I thought I best add that I use a Fen Next Episodes widget and it updates after watching an episode. The skin I use is Arctic Zephyr.)

What skin are you using? I will install it and check Next Episodes.

1. It's possible the episode is simply not getting marked watched, meaning the widget will refresh, but won't show a change, making it look like it doesn't refresh. When you get time, watch an episode from the widget, and if the widget doesn't update with the next episode, go into Fen and check there whether the episode you just watched was marked as watched (this would be a fault with Fen).
2. If you have a very large number of in progress shows, maybe the widget is unable to refresh correctly and maintains the previous widget (this would be a fault with Fen).
3. Make sure, if you do have many in progress shows, to give the widget ample time to refresh after playback.

I can't really think of anything else at this time as to what could be the problem. Except, when having ANY troubles with lists not showing correctly, make sure Settings->General->Navigation->Use Threading for Menu Items is set to OFF.

**Comment by SpTec** [comment] 2019-11-28 09:04
> The helper scripts your skin uses will refresh widgets after certain Kodi actions, which includes after playback. So Fen showing results as a dialog does not affect this, although it was reasonable to assume that was the problem.

> **It works just fine in other addons that I have In progress TV shows as a widget**

> (I thought I best add that I use a Fen Next Episodes widget and it updates after watching an episode. The skin I use is Arctic Zephyr.)
> 
> What skin are you using? I will install it and check Next Episodes.

> **Aura**

> 1. It's possible the episode is simply not getting marked watched, meaning the widget will refresh, but won't show a change, making it look like it doesn't refresh. When you get time, watch an episode from the widget, and if the widget doesn't update with the next episode, go into Fen and check there whether the episode you just watched was marked as watched (this would be a fault with Fen).

> **Have already done this as I said in last message refreshes fine when through the addon to Next Episode but not in the widget and is showing a few already watched episodes as well**

> 2. If you have a very large number of in progress shows, maybe the widget is unable to refresh correctly and maintains the previous widget (this would be a fault with Fen).

> **How many is too many?**

> 3. Make sure, if you do have many in progress shows, to give the widget ample time to refresh after playback.

> **Is 24  hours (roughly) enough time?**

> I can't really think of anything else at this time as to what could be the problem. Except, when having ANY troubles with lists not showing correctly, make sure Settings->General->Navigation->Use Threading for Menu Items is set to OFF.

> **It is OFF**

What about my original question about the in progress TV shows showing all seasons and episodes regardless if watched or not  and showing in Alphabetical order even tho have it set to Recently Watched in settings
While I think Fen is a good addon and you have done some great work on it I don't think it plays nicely with Trakt as never had these issues with any other addon and trakt

**Comment by Tikipeter** [comment] 2019-11-28 15:38
In Progress TV Shows is a list of TV Shows that you have started to watch (in progress). That is what it is supposed to look like and how it is supposed to behave. There is no setting to change the order of "In Progress TV Shows". The setting tab that lets you change order says 'Next Episodes', and that is the menu item it changes settings for; 'Next Episodes'.

I have no idea how many is too many in regards to Next Episodes. There shouldn't be a number that is too many, but I'm only taking guesses as to the reason for the problem you're experiencing. I'll install the Aura skin, un-hide all the Shows in my Trakt progress, and see if I can get it to behave as yours is.

If you can give me an example of a show that is incorrectly showing watched episodes in the Next Episodes list, that would be great (and also whether said episode has a watched checkmark showing in the list).

**Comment by SpTec** [comment] 2019-11-29 13:18
Ok we seem to differ in our opinions on how In progress TV Shows should work, as I have said in all other addons I have used trakt (around 5 years now) yoda, numbers leviathan and the original exodus the in progress only showed unwatched seasons and episodes with a setting in settings to order them by recently watched, so I saw that setting in fen settings and assumed it would work the same but guess not.
Also the several people I spoke to before asking here thought it should work the same way too, for me it would be a really good change to make 

I may have 20 or so in progress at the moment, not at home currently but will check when home, and will also check what watched episodes are showing in the next episodes list, I know for sure they all have the watched tick next to them

**Comment by SpTec** [comment] 2019-11-29 13:20
Oh and is there a way to talk to you privately I need to show you something, mysterious I know but don't want to do it publicly

**Comment by Tikipeter** [comment] 2019-11-29 20:43
I tried on Aura with 13 episodes active for Next Episodes and they showed correctly. I'll have to test with a show or two of yours that is displaying incorrectly.

Unfortunately I'm not a member of any social networks, so private messaging is not an option.

**Comment by SpTec** [comment] 2019-12-02 16:51
Only just returned home, the watched episodes that are still showing are 
Another Life 1x02
Mad Dogs 4x01
Limitless 1x01

All have the watched tick both in the next episode list and the widget (see screenshot for example)

![SpTec 18 4-nextepisode](https://user-images.githubusercontent.com/58175589/69978182-f4018380-1523-11ea-845b-255b937aaec1.png)

![SpTec 18 4-widget](https://user-images.githubusercontent.com/58175589/69978231-067bbd00-1524-11ea-8fc9-b14bf03bb26a.png)

**Comment by Tikipeter** [comment] 2019-12-03 03:33
Thanks for replying SpTec.

I will have a look at this again with this new info and report back. :)

**Comment by SpTec** [comment] 2019-12-04 01:00
Think I may have worked out why not refreshing after episode finishes, certain episodes don't get scrobble by the trakt addon in fen for instance jack Ryan ep 2x05 scrobble fine in other addons but when I play in fen it  doesn't which seems a bit strange, any ideas?

Other episodes work ok and they update ok

**Comment by Tikipeter** [comment] 2019-12-04 13:15
Hi SpTec.
I tried all the shows in your list above (Another Life, Mad Dogs, Limitless), plus just now tried Jack Ryan, and they all mark watched correctly and show the next episode in Next Episodes correctly. 

I'm really still no closer to knowing what the problem is with your install. :( :(

**Comment by Tikipeter** [comment] 2019-12-06 23:46
Latest release (v.1.5.78) has some changes that may help with the widget not reloading after playback issue.

**Comment by SpTec** [comment] 2019-12-10 17:38
As I said in my last post the reason is not updating and i never noticed before was that the episode wasn't being scrobbled by the trakt addon when ended so the widget won't refresh as trakt has no idea I have watched it, the series I noticed it on was jack ryan no episodes would scrobble in fen but did in other addons, episodes that scrobble in fen the widget then updates ok

If you could just get the the in progress tv shows to be ordered by recently watched I would use that in the widget instead of next episode (which was my original query)

I hate to be a pain but you did lead me down this next episode rabbit hole lol

Thanks

**Comment by Tikipeter** [comment] 2019-12-10 21:08
> As I said in my last post the reason is not updating and i never noticed before was that the episode wasn't being scrobbled by the trakt addon when ended so the widget won't refresh as trakt has no idea I have watched it, the series I noticed it on was jack ryan no episodes would scrobble in fen but did in other addons, episodes that scrobble in fen the widget then updates ok
>
That's not the reason. I'm sorry, but you are incorrect.

> If you could just get the the in progress tv shows to be ordered by recently watched, (which was my original query)...
>
You're original query was to also have 'In Progress' only show the seasons and episodes you hadn't watched yet. I don't want it to work that way, which is why I directed you down the 'rabbit hole' of 'Next Episodes' in the first place.

> ...which is a setting in all the exodus type fork addons I use
>
Fen is not an 'Exodus type fork', so it should not be suprising that Fen does not have this setting.
The description of Fen states: "Please Note: This add-on is NOT an Exodus fork, and as such will behave differently to an Exodus fork." I put that in the description to avoid all the "The other Exodus forks do this, why doesn't Fen" statements.

> I would use that in the widget instead of next episode and I would leave you in peace
>
I was/am still happy to help with the Next Episode problem you are having, but I also understand you are not interested in it functioning correctly for you, as you don't wish to use it. The problem is, I have no interest in coding 'In Progress' to work the way you want it to. It currently works as I intend it to work.

> I hate to be a pain....
>
You are never a pain. I can sympathize with your situation, but I'm not sure I can help it. :(

> Thanks
>
Thank you. :)

**Closed** 2019-12-17 16:47 UTC
Labels: 7 Days no reply..., possible bug
