### ISSUE TITLE
Fen/My Accounts not saving debrid auth settings

### ISSUE THREAD

**Issue by Tinuz97** [Tikipeter/repository.tikipeter#267] opened 2020-09-26 22:29 UTC
No more results since last update (zero links) 
It shows how many duplicates are removed, after that no results (geen resultaten in Dutch language). 
Cleaned Fen with every cleaning option in the addon, rebooted kodi (phone), did not test on my computer/shield yet, because it is almost bed time. 
Can't see any errors in the log related to Fen..... 
Any idea? 

![Screenshot_20200927-002327](https://user-images.githubusercontent.com/47715606/94351342-0f5ff100-0058-11eb-9668-4d172bee12d8.jpg)

**Comment by Tinuz97** [comment] 2020-09-26 22:36
Also did authorize Realdebrid again, still no results 😕

**Comment by Tinuz97** [comment] 2020-09-26 22:41
It looks that it does not save the Realdebrid auth? 
It says successful, bit If I go to the setting again, account details gone. 

![Screenshot_20200927-004006](https://user-images.githubusercontent.com/47715606/94351549-112ab400-005a-11eb-8fa0-c3988ead9219.jpg)

**Comment by Tikipeter** [comment] 2020-09-26 23:01
Try and check if there is a `script.modules.myaccounts` folder made in the `userdata` folder, and that there's a `settings.xml` file within.

**Comment by Tinuz97** [comment] 2020-09-26 23:22
Nope, so that must be the problem (for me).
It does not create a script.modules.myaccounts folder (for me) in the userdata folder (on my Oneplus 5 android 10 phone).

**Comment by Tikipeter** [comment] 2020-09-26 23:25
I know it's your bed time, but when you get a chance, navigate to the `myaccounts` settings by going to `Programs` in Kodi rather than through Fen's settings first. Change a setting (maybe put in a random number for IMDb ID) save and exit out of settings and go back in and see if they stick.

**Comment by Tinuz97** [comment] 2020-09-26 23:31
A random IMDB number did create the folder in userdata/addon_data. 

So my guess is that this will give issues to many users, or can you make a workaround that it will create the folder for not experienced users?

**Comment by Tikipeter** [comment] 2020-09-26 23:35
There will need to be a fix for this, for sure. I just have to pin down why it's happening. It looks to be an issue if there is no folder/settings.xml created yet, and the user accesses MyAccounts for the first time through another addons settings. The folder and settings.xml look like they're not made then.
I appreciate the bug report tinuz, this needs to be fixed.

**Comment by Tinuz97** [comment] 2020-09-26 23:35
Folder created (1 message above this one), but Realdebrid auth does not stick (the settings.xml is also created with the random IMDB number), but still does not stick, resulting in no results after scraping.

**Comment by Tikipeter** [comment] 2020-09-26 23:38
You hit OK (save) after it authed to close the MA settings?

**Comment by Tinuz97** [comment] 2020-09-26 23:43
> You hit OK (save) after it authed to close the MA settings?

Yes, this is with auth (screenshot), then I hit OK to save it, then I open the my accounts again, auth gone (my name gone, and the authorize button is back. 
![Screenshot_20200927-014014](https://user-images.githubusercontent.com/47715606/94352223-8ac6a000-0062-11eb-86d3-09410339f1cf.jpg)

**Comment by Tikipeter** [comment] 2020-09-26 23:45
OK. Thanks Tinuz. I will try and replicate this and see what's happening.

**Comment by 99Maxwell99** [comment] 2020-09-27 01:16
I got this too but I went into fenom scrapers and enabled all premium hosters and it gave me a list of results after I scraped again

**Comment by Tinuz97** [comment] 2020-09-27 06:39
> I got this too but I went into fenom scrapers and enabled all premium hosters and it gave me a list of results after I scraped again

Did that also  before creating this ticket, but did also not fix the issue for me.

**Comment by Tinuz97** [comment] 2020-09-27 09:33
It seems that Venom has the same issue @Tikipeter, did read did few minutes ago on Facebook. (but that does not work for me either) 
![Screenshot_20200927-113208](https://user-images.githubusercontent.com/47715606/94361533-3bf62600-00b5-11eb-9073-eb3155099cfd.jpg)

**Comment by 99Maxwell99** [comment] 2020-09-27 10:20
> > I got this too but I went into fenom scrapers and enabled all premium hosters and it gave me a list of results after I scraped again
> 
> Did that also before creating this ticket, but did also not fix the issue for me.

Did you try auth RD after enabling. I did my RD first and checked in my accounts to make sure it saved it.

**Comment by onlytanmoy** [comment] 2020-09-27 12:04
Working now! This is what I did on my Shield Pro- went to settings Fen > Accounts > Open My Accounts
Re-auth Trakt, RD, returned back to Accounts section and clicked (Re)Sync Fen Settings with my accounts. That's it.

**Comment by Junkdewd** [comment] 2020-09-27 19:04
The adding a random entry to imdb, saving, then resynching accounts to fen settings has fen working correctly for me. 

I have noticed an increased number of hard crashes of Kodi when I've had errors with fen. 
I haven't uploaded logs for or investigated much, as I know you are rewriting quite a bit of the code atm, but I will starting now, as I realize it might help you pinpoint an issue you are trying to track down.  

Thanks for all you are doing for us.

**Comment by Tikipeter** [comment] 2020-09-27 21:18
I am going to rename this Issue thread because I need to concentrate on the issue OP is having (My Accounts not saving debrid settings). Anything not related to that please start a new Issue.

**Comment by Tikipeter** [comment] 2020-09-27 21:23
@Tinuz97 
I tried on all my regular tv devices, my computer and also 2 phones to replicate this issue, including fresh installs and I cannot make it happen. There is definitely something going on because there are other reports with similar issues.
Have you tried it on your computer with success?

I've read one user had success by clearing the data (cache?) for Kodi in Android. Perhaps that is worth a try.

**Comment by Tinuz97** [comment] 2020-09-27 21:35
I just tested it on my phone, need to test computer.
I did read at Venom Git that someone also has the issue on Linux. 

I'm not able to test now, but tomorrow I can (almost bedtime here).

**Comment by Tinuz97** [comment] 2020-09-27 22:15
Fast test on the computer @Tikipeter , that does work fine.
So it seems that people that are having issues like me, have Linux or Android?

Also I noticed some things are not translated in the settings to Dutch, and TOOLS: Autoriseer Debrid Diensten (auth debrid accounts) is not working either (I did auth Realdebrid in the my accounts settings), I think that shortcut is still linking to old auth?

**Comment by Tikipeter** [comment] 2020-09-27 22:25
Linux I'll have to retest. Atleast Android (some) seem to be having issues.
Leaving Auth'ing through the TOOLS section is an oversight on my part. That should not be there anymore.
As to the non-translated strings in settings, are they like that only on your phone, or all devices you've tried?

**Comment by Tinuz97** [comment] 2020-09-27 22:31
Open Mijn Accounts (voer hier accountgegevens in)   is the one you noticed above here.

**Comment by Tinuz97** [comment] 2020-09-27 22:34
On the computer,and android also these missing : Please visit my accounts to change settings, that is in Dutch:
Bezoek Mijn Accounts om instellingen te wijzigen

That are the 2 i see at the moment :)

**Comment by Tikipeter** [comment] 2020-09-27 23:08
Thanks Tinuz. 👍 
I re-tested a LibreELEC install, and all settings were saved successfully. I'm thinking the problem is going to be mainly android.

**Comment by Tinuz97** [comment] 2020-09-27 23:09
I am translating Fenom Scrapers also,if you can use it (see 123Venom Git) :)

**Comment by Tikipeter** [comment] 2020-09-27 23:10
You're a hero Tinuz!
Great job mate!!!

**Comment by Tikipeter** [comment] 2020-09-27 23:26
@Tinuz97 
Turn off the language invoker on the phone install and see if that fixes the issue. I've got an idea of what it might be unfortunately.
(At the bottom of Tools).

**Comment by Tinuz97** [comment] 2020-09-27 23:34
Disabled (screenshot), rebooted kodi (phone), tryed to auth trakt (does not stick), Realdebrid auth, does not stick either with invoker turned off :/

Going to bed now (uploaded the zip for strings/Fenom scrapers already). 

![Screenshot_20200928-013234](https://user-images.githubusercontent.com/47715606/94378521-8fef2200-012a-11eb-98af-7cc0103e8afa.jpg)

**Comment by Tikipeter** [comment] 2020-09-28 16:57
Damn! I was hoping that would be the only issue to address. There's something else again going on.

**Comment by Tinuz97** [comment] 2020-09-28 16:59
A buddy of my tested on a raspberry pi 4, libreelec, no issues either.

**Comment by Tinuz97** [comment] 2020-09-28 17:00
Tinuz be like 
![49562517_2476184055731250_5752766523963619196_n-9541719234](https://user-images.githubusercontent.com/47715606/94463237-e9079600-01bc-11eb-86ad-673ce9ab12aa.jpg)

**Comment by Tikipeter** [comment] 2020-09-28 17:01
We'll get it sorted, don't worry!
While I've got you here Tinuz, I got your translations. Thanks mate. :)
Can you delete that Issue on addons4kodi github, as myaccounts doesn't actually reside there anymore. I'll post it's github home below for you:
https://github.com/Mr-Kodi

**Comment by Tinuz97** [comment] 2020-09-28 17:28
Closed it, did not see a delete option?

**Comment by Tikipeter** [comment] 2020-09-28 20:30
> Closed it, did not see a delete option?
That's fine. Thanks tinuz.

New update of MyAccounts should be live (v.1.0.2).
Added your translations (forgot to do a changelog, so I need to credit you with the next update SORRY) and hopefully a fix for your current issues.

Let it update, restart Kodi and give it a test. Fingers crossed.....

**Comment by Tinuz97** [comment] 2020-09-28 20:37
> > Closed it, did not see a delete option?
> 
> That's fine. Thanks tinuz.
> 
> New update of MyAccounts should be live (v.1.0.2).
> Added your translations (forgot to do a changelog, so I need to credit you with the next update SORRY) and hopefully a fix for your current issues.
> 
> Let it update, restart Kodi and give it a test. Fingers crossed.....

Translations working nice. 

One step further now, it does save my Realdebrid account settings now, but still the message Geen Resultaten (No Results in English). 

Did the update, closed kodi, started kodi, cleaned all possible options in Fen.

**Comment by Tikipeter** [comment] 2020-09-28 20:40
Is RD enabled in Fen's settings?

**Comment by Tinuz97** [comment] 2020-09-28 20:43
> Is RD `enabled` in Fen's settings?
> And are the settings from MyAccounts successfully synced to Fen (it should show now your RD username in Fen)?

Yes 
![Screenshot_20200928-224215](https://user-images.githubusercontent.com/47715606/94483955-f84a0c00-01db-11eb-92ca-0288c3f797f3.jpg)

**Comment by Tikipeter** [comment] 2020-09-28 21:03
That all looks good now. The My Accounts issue should fix this, but for some reason it hasn't. It is working correctly now though with regard to setting/supplying your RD settings for Fen.

* Can you navigate into "My Services"->Real Debrid and do things within there (navigate Cache, check Account Info etc)?

**Comment by Tinuz97** [comment] 2020-09-28 21:09
> That all looks good now. The My Accounts issue should fix this, but for some reason it hasn't. It is working correctly now though with regard to setting/supplying your RD settings for Fen.
> 
> * Can you navigate into "My Services"->Real Debrid and do things within there (navigate Cache, check Account Info etc)?

Yes, all the options working 
![Screenshot_20200928-230826](https://user-images.githubusercontent.com/47715606/94486363-9c818200-01df-11eb-9cf9-6514a52c3e56.jpg)

**Comment by Tikipeter** [comment] 2020-09-28 21:28
Well that's more good news.
Onto FenomScrapers then..
Make sure all scrapers are enabled, and let me know what process happens when you try to scrape. Does it go through the whole process of scraping i.e. finding the links as you see it through the dialog, then checking the debrid accounts for cached torrents, and only failing after that right at the last step of actually displaying the results.

**Comment by Tinuz97** [comment] 2020-09-28 21:56
> Well that's more good news.
> Onto FenomScrapers then..
> Make sure all scrapers are enabled, and let me know what process happens when you try to scrape. Does it go through the whole process of scraping i.e. finding the links as you see it through the dialog, then checking the debrid accounts for cached torrents, and only failing after that right at the last step of actually displaying the results.

This is weird. 
After opening kodi on the 3th time, I get results after scraping. 
First 2 times I didn't.... 

I already did enable all scrapers (hosters, torrent), it did go true the whole process like usual, but at the end no results. 

But now it does give results after starting kodi for the 3th time (without changing anything), weird.

**Comment by Tikipeter** [comment] 2020-09-28 22:04
Very weird.
OK. Does this mean everything is working now? Did your Trakt auth work and sync with Fen as well as any other debrids?
There will be an update later to FenomScrapers to fix a couple of small issues, but I'm hoping this is finally working right.

**Comment by Tinuz97** [comment] 2020-09-28 22:07
Testing Trakt in a minute, did not auth that yet. BRB.

**Comment by Tinuz97** [comment] 2020-09-28 22:11
Getting results, Trakt auth is saved in My Accounts, but does not sync with Fen (Screenshot) 

![Screenshot_20200929-000933](https://user-images.githubusercontent.com/47715606/94491245-27ff1100-01e8-11eb-94a1-41f747318317.jpg)

![Screenshot_20200929-000730](https://user-images.githubusercontent.com/47715606/94491227-1cabe580-01e8-11eb-8e7b-61c143dadb2e.jpg)

**Comment by Tinuz97** [comment] 2020-09-28 22:13
And also this one same behavior,after the 3th time opening,it does sync with Fen,realy weird.

**Comment by Tikipeter** [comment] 2020-09-28 22:14
> And also this one same behavior,after the 3th time opening,it does sync with Fen,realy weird.

Trakt you mean?

Man this is freaky. I'm hoping it's an Android caching issue, but now that it's sorted any new changes show immediately.

**Comment by Tinuz97** [comment] 2020-09-28 22:15
i know how to show it,gonna make a video.
It does sync, but after checking it,gone. gonna make a video.

**Comment by Tinuz97** [comment] 2020-09-28 22:19
Check this @Tikipeter https://tinuz97.stackstorage.com/s/dnTxJeVe1y2DJfOd

**Comment by Tikipeter** [comment] 2020-09-28 22:23
That screen in the background (addon info screen) needs to be backed out of before the settings are written to file.

To take that out of the equation, access My Accounts through Fen Settings->Accounts and try again. Perhaps just a resync will do if the settings are being saved in My Accounts.

**Comment by Tinuz97** [comment] 2020-09-28 22:32
> That screen in the background (addon info screen) needs to be backed out of before the settings are written to file.
> 
> To take that out of the equation, access My Accounts through Fen Settings->Accounts and try again. Perhaps just a resync will do if the settings are being saved in My Accounts.

That did work. 
But weird that you can't control it this way, I hold my finger on Fen normally,so I get the pop-up menu, select configure (that is why you see the addon info screen). 
That did always work (with any addon), and I know that many people also using that method, is that fixable?

**Comment by Tonkapug** [comment] 2020-09-28 22:58
Hi Tikipeter, I can confirm the exact issue being described here. I was just about to create an issue but decided to browse for a possible open issue already and here i am!

The My Accounts addon is not saving settings during auth. The only way i could create a settings.xml in addon_data directory was by enabling logging and clicking ok. 

If you auth an account the details are shown. As soon as you click ok (save and exit) and reopen the settings are gone and no record saved in the addon_data directory.

I even attempted via the Fen addon menu and still no go. The settings are just not saving

I'm testing on my Android tablet

I tested on a windows device and 1st try settings have saved.

**Comment by Tikipeter** [comment] 2020-09-28 22:58
It's not fixable by me, only Kodi. It will work the way you want, it's just if you exit settings and come back into settings without also first exiting the info dialog, the settings aren't written by Kodi.

As long as you exit that info screen first, the settings should work going in the way you like. It may be because the ADDON (Fen) is setting that particular setting from within it's code, and not you doing it manually through the settings window. That might be why it doesn't stick until you back out.

I'll test that and see if that's the case.

**Comment by Tikipeter** [comment] 2020-09-28 22:59
@Tonkapug  have you got the latest My Accounts addon (version 1.0.2). That has hopefully fixed this issue, as it has for Tinuz97 above.

**Comment by Tonkapug** [comment] 2020-09-28 23:01
@Tikipeter Yes, i am running 1.0.2. Still the same issue on Android. Windows no issue

**Comment by Tonkapug** [comment] 2020-09-28 23:03
@Tikipeter I will try and fresh start on my Android as i was tinkering with it for awhile. I just tested on windows before coming here to drop you a line.

**Comment by Tikipeter** [comment] 2020-09-28 23:05
Trying fresh is a good idea.
Also, access fen's settings through the addon if you can, rather than the method Tinuz used above, just to eliminate one possible issue.

**Comment by Tonkapug** [comment] 2020-09-28 23:17
@Tikipeter I uninstalled Fen, Fenomscrapers and My Accounts. Exited kodi and Force stopped the app cleared Android cache. Reinstalled everything and exact same issue. Even when attempting through the Fen addon settings. The auth settings are not being saved within the My Accounts addon.

**Comment by Tikipeter** [comment] 2020-09-28 23:23
Is it making a `script.modules.myaccounts` folder in your user_data folder? And a `settings.xml` file within that?

**Comment by Tonkapug** [comment] 2020-09-28 23:26
@Tikipeter Negative....that's the issue. Only way i can create it is to enable another setting and click ok to save. Boom there it is!

**Comment by Tikipeter** [comment] 2020-09-28 23:30
OK. So after it makes the folder, test authing something and see if the results stick now. Be sure to hit OK to exit each settings window.

**Comment by Tonkapug** [comment] 2020-09-28 23:33
@Tikipeter Already did, it will not save the auth settings. Neither through the My Accounts or Fen.

**Comment by Tonkapug** [comment] 2020-09-28 23:37
@Tikipeter Are you able to reproduce this on an Android device yourself?

**Comment by Tikipeter** [comment] 2020-09-28 23:39
No, I installed Kodi on my phone briefly to try and replicate, but it worked fine. I authed 3 debrid services and my Trakt account all without incident, and also before the update to My Accounts.

I have no other Android devices I can test with unfortunately.

**Comment by Tonkapug** [comment] 2020-09-28 23:46
@Tikipeter Me either, i am away from home for another couple weeks. My tablet is running Android 7.0. Windows i just revoked and redone the auth and synced with Fen. Works flawlessly. I'm gonna clear data for Kod1 and retry. Just to be sure there's no issue there. I'll post back with the results

**Comment by Tonkapug** [comment] 2020-09-29 00:00
@Tikipeter Did a complete fresh start (cleared data) and still the same. Settings are not saving on my Android device. Very strange. Appears to be Android related though. Which could account for the varied results i have seen throughout the community. Some, it works flawlessly and others no go.

**Comment by Junkdewd** [comment] 2020-09-29 02:25
It could have something to do with the tv box versions of android.  May help to take a pill. I use an Ematic Jetstream, similar to mi box 3s hardware, running Android TV version 9.  

The workaround worked first try for me, latest release Kodi, xonfluence skin.

**Comment by Tonkapug** [comment] 2020-09-29 03:38
@Junkdewd For me, it doesn't matter if the settings.xml file is created or not. It will not save the auth data no matter what i try. I'm using and Android Tablet 7.0 OS. They only way i can get it to work is to auth on windows and copy the settings.xml to the Android and sync via Fen. Works fine then!

**Comment by Junkdewd** [comment] 2020-09-29 04:14
> @Junkdewd For me, it doesn't matter if the settings.xml file is created or not. It will not save the auth data no matter what i try. I'm using and Android Tablet 7.0 OS. They only way i can get it to work is to auth on windows and copy the settings.xml to the Android and sync via Fen. Works fine then!

I'm only offering up my experience so that Peter can have my data in case it may be helpful.  I understand others are having different experiences than I am.

**Comment by Tonkapug** [comment] 2020-09-29 10:30
This is how I managed to get the settings to save. Couldn't get them to save any other way. 

You need to click 'ok' after the Auth code window closes but before the notification pops up saying 'Real Debrid is authorized'. The settings will then save. You can confirm by reopening the My Accounts addon and check the Debrid Accounts section for your details.

If the settings stick, you can then go into Fen settings and Resync to My Accounts.

**Comment by Tikipeter** [comment] 2020-09-29 17:50
I will look into Tonkapug's issue above, but to everybody reading through this thread, please remember the following:

Kodi WILL NOT save your auth data once a service has been authorized UNTIL YOU CLICK THE OK BUTTON IN THE SETTINGS WINDOW.
I know the settings appear in the window like they've been written to the settings file (username of authed service is displayed etc), but they have not yet been written to the settings file.
If you back out of settings after authing, instead of clicking OK, they will not be saved.

I am not saying this is the issue everyone is having at the moment, but there will definitely be some out there who are experiencing issues because they are not doing this.

**Comment by mrchen911** [comment] 2020-09-29 19:09
I'm experiencing the same issue but only on my cell phone. I had no problems setting up my 2 fire sticks. I've uninstalled venom, fen, and my accounts. I cleared the cache, reinstalled venom. Going only into my accounts, nothing will save. I tried doing imdb, hit ok, went back in, still can't get trakt or rd to stick, even hitting ok afterwords. The imdb setting does stick.

**Comment by Tonkapug** [comment] 2020-09-30 00:19
> I'm experiencing the same issue but only on my cell phone. I had no problems setting up my 2 fire sticks. I've uninstalled venom, fen, and my accounts. I cleared the cache, reinstalled venom. Going only into my accounts, nothing will save. I tried doing imdb, hit ok, went back in, still can't get trakt or rd to stick, even hitting ok afterwords. The imdb setting does stick.

After entering your code to pair with your Debrid service and the Auth code window is still open in Kod1 keep clicking where the ok button is continously (button is still in the background) until the code window closes on its own. It'll then save. You have to be quick.

**Comment by mrchen911** [comment] 2020-09-30 00:59
That's hard to do when switching from browser to Kodi on my cell. I'll have to enter the code in another device. Will report back if it works or not.

**Comment by mrchen911** [comment] 2020-09-30 17:27
> > I'm experiencing the same issue but only on my cell phone. I had no problems setting up my 2 fire sticks. I've uninstalled venom, fen, and my accounts. I cleared the cache, reinstalled venom. Going only into my accounts, nothing will save. I tried doing imdb, hit ok, went back in, still can't get trakt or rd to stick, even hitting ok afterwords. The imdb setting does stick.
> 
> After entering your code to pair with your Debrid service and the Auth code window is still open in Kod1 keep clicking where the ok button is continously (button is still in the background) until the code window closes on its own. It'll then save. You have to be quick.

I can confirm, this did work.

**Comment by Tikipeter** [comment] 2020-09-30 22:14
I know I've been quiet on this thread the last 24 hours, but I've been reading what is written and, believe me, I've been thinking a lot about what might be causing this and have spent a lot of time trying to make it happen for me (the only real way I can fix this is if I'm able to replicate it happening).

I've tried on Windows, LibreELEC (Linux) and also Android, with all different combinations of entering My Accounts either through Fen or through Kodi's "Programs" menu, having a folder and settings file in `userdata` or not, saving a text setting (like IMDb ID) first or not. Clean install straight to authorizing a debrid account or not.

Nothing I do will make this happen for me on any of the three OS's I listed above. I've tried for hours to get these errors to happen.

We haven't given up, though, but thought I'd give a (bad news so far) progress report on the issue.

**Comment by Tinuz97** [comment] 2020-10-01 19:23
Premiumize won't stick now for me on May phone (Realdebrid does stick), did it the same way as earlier. Also some Dutch users are still experiencing 'the won't stick' issue.
It's a weird thing, because some people have this, and some do not have the issue. :/

**Comment by Tikipeter** [comment] 2020-10-01 20:00
How are you entering My Accounts settings Tinuz?
Fen Addon Info->Configure->Enter My Accounts Settings?

**Comment by mrchen911** [comment] 2020-10-01 20:11
I run Kodi on 3 devices and only had the problem on one.

For me, it didn't matter how I accessed accounts, whether directly through the my accounts app or through venom or fen, the behavior was the same.

**Comment by Tikipeter** [comment] 2020-10-01 20:13
Touchscreen on the problem device?

**Comment by mrchen911** [comment] 2020-10-01 20:16
> Touchscreen on the problem device?

Yes, Android 11 on a pixel 4a. The other 2, which were not a problem, were firetv 4k sticks.

**Comment by Tinuz97** [comment] 2020-10-01 20:17
> How are you entering My Accounts settings Tinuz?
> Fen Addon Info->Configure->Enter My Accounts Settings?

Nope, that did go wrong before that way (with Realdebrid). 
I open Fen, settings/accounts/open my accounts.

Also tryed to go directly to my accounts, won't save either. 
Realdebrid is working (that we did a day or 2 back) on the phone.

**Comment by Tikipeter** [comment] 2020-10-01 20:36
123venom is currently trying to get some useful info from a Venom user. If that doesn't pan out, I think I am going to need to post here test builds for both Fen and My Accounts. It will be the only way to solve this once and for all. I have a couple of ideas as to what it might be now, but it doesn't make sense why it is happening. So I'll just need someone to test and see if it fixes it.
Sorry everyone.

**Comment by Tikipeter** [comment] 2020-10-01 21:15
No luck with 123Venom's user. He/she was not hitting OK to close EACH settings window.
I have pinned a new Issue with a test build for both Fen and My Accounts.
Please install both to test.
https://github.com/Tikipeter/repository.tikipeter/issues/274

**Comment by mrchen911** [comment] 2020-10-01 21:50
As a test, with the current version, I revoked my trakt authorization and saved it. Went back in to my accounts, it was cleared, so I authorized it again, was in no rush to hit ok, the authorization did not stick.

**Comment by Tinuz97** [comment] 2020-10-01 21:57
> No luck with 123Venom's user. He/she was not hitting OK to close EACH settings window.
> I have pinned a new Issue with a test build for both Fen and My Accounts.
> Please install both to test.
> #274

For me it did work, no idea for others (see my comments on #274

**Closed** 2020-10-03 21:51 UTC
Labels: bug
