### ISSUE TITLE
Problem with scrapping new shows and movies

### ISSUE THREAD

**Issue by unicornsandcandies** [Tikipeter/repository.tikipeter#52] opened 2022-10-09 08:51 UTC
Recently Fen stopped working for me when it comes to any new shows or movies. They only work when they're already on my debrid account and even this is not always helping. This happens for me on both my devices (ubutnu 22.04 laptop and raspberry pi 4) and on both on them Umbrella addon, that as far as I know is literally using the same scrapers finds plenty of sources. At first I was thinking that maybe I'm watching show that aren't that popular for having many torrents right after release, but now it's just confusing to me.
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9741125/kodi.log)
![ubrella](https://user-images.githubusercontent.com/112720004/194747364-c00089c1-b0c6-402c-a29b-8484fa7b90c5.png)
![2022-10-09_10-44](https://user-images.githubusercontent.com/112720004/194747372-fc21c755-b30a-4516-8181-54271c485829.png)

**Comment by ivarbrandt** [comment] 2022-10-09 10:33
I just scraped for links for this title and Fen found lots of them. So let's try a few things to hopefully fix this issue you are having.

1. While having the movie highlighted in the menu item, go into the into the Options menu by accessing the context menu. If you are on something like a Shield you would long press the movie. If you are on a computer, hit Enter on the movie and hold it until the context menu pops up. Click Options, Playback Options, Rescrape and Select Source.
2. If that still doesn't yield any results, try going into Tools menu in the main menu, Clear Databases and Settings Files, then clear the cache of the service that you are using. For example, if you use Real Debrid, click Clear Real Debrid Cache. 
3. Now go back to the movie and try scraping for links again. I hope this helps.

**Comment by unicornsandcandies** [comment] 2022-10-09 11:05
> I just scraped for links for this title and Fen found lots of them. So let's try a few things to hopefully fix this issue you are having.
> 
>     1. While having the movie highlighted in the menu item, go into the into the Options menu by accessing the context menu. If you are on something like a Shield you would long press the movie. If you are on a computer, hit Enter on the movie and hold it until the context menu pops up. Click Options, Playback Options, Rescrape and Select Source.
> 
>     2. If that still doesn't yield any results, try going into Tools menu in the main menu, Clear Databases and Settings Files, then clear the cache of the service that you are using. For example, if you use Real Debrid, click Clear Real Debrid Cache.
> 
>     3. Now go back to the movie and try scraping for links again. I hope this helps.

None of this helped. I've also tried reauth real debrid and it didn't help either.

**Comment by ivarbrandt** [comment] 2022-10-09 11:30
I'm not sure what's going on then. I do see that you're running quite a few add-ons. I know some people have had issues running Fen and Ezra at the same time. See if disabling Ezra and its scraper package helps. If not, I would just sit tight till the developer responds to you.

**Comment by unicornsandcandies** [comment] 2022-10-09 11:40
> I'm not sure what's going on then. I do see that you're running quite a few add-ons. I know some people have had issues running Fen and Ezra at the same time. See if disabling Ezra and its scraper package fixes the issue. If not, I would just sit tight till the developer responds to you.

Doesn't work. And on pi4 I don't even have Ezra installed and it's not working

**Comment by Nuklear92** [comment] 2022-10-09 11:46
I have the same issue as well, I first thought it was because FEN was designed to scrape Movies and Shows only when they're officially Released Digitally, etc. and not prior their release date like other addons do. But yeah, even some titles after they're officially released still not being scrapped for some odd reason. 🤷‍♂️

**Comment by Tikipeter** [comment] 2022-10-09 20:29
I'll need all those screenshots I mentioned on reddit.

**Comment by unicornsandcandies** [comment] 2022-10-09 20:43
![1](https://user-images.githubusercontent.com/112720004/194778616-ed349337-e2d4-4f01-8689-7ce6884eac16.png)
![2](https://user-images.githubusercontent.com/112720004/194778617-7eff1c60-6a86-42bc-9c0c-0ce6acafedc8.png)
![3](https://user-images.githubusercontent.com/112720004/194778618-2782bad4-350c-45f9-b657-a886b354d5ff.png)
![4](https://user-images.githubusercontent.com/112720004/194778620-165a9541-be4b-40f9-86ec-e7b5fe21ce0d.png)
![5](https://user-images.githubusercontent.com/112720004/194778622-7b1be06d-5046-42e3-97e1-b48d575c2d3e.png)
![6](https://user-images.githubusercontent.com/112720004/194778623-d931005e-dbc5-4844-bc1f-72bdc3816db3.png)
![7](https://user-images.githubusercontent.com/112720004/194778624-39c58d80-bbbf-4f6a-8600-f44482ba3d77.png)
![8](https://user-images.githubusercontent.com/112720004/194778625-c8b6b331-3481-42b2-a7c2-384eb6931f25.png)
![9](https://user-images.githubusercontent.com/112720004/194778626-07108bbc-33d3-443d-b092-62f7841a8362.png)
![10](https://user-images.githubusercontent.com/112720004/194778627-898b3f95-657d-4632-b043-591e76ac9e4e.png)

**Comment by Tikipeter** [comment] 2022-10-09 21:42
OK. Good job on the images. Thanks for that.

I've replicated your settings and am getting results no problem, but there was something in your log that piqued my interest.

Try this please....

Turn off "Check Year Before Search" in Settings->Results->General.

Clear the Providers cache in Tools->Clear Databases & Clean Settings Files->Clear External Scrapers Cache.
Also clear "Clear Internal Scrapers Cache".

Try a scrape of a Movie and see if it provides results now. Might be better to turn off autoplay so you can see the actual results in this test.

**Comment by unicornsandcandies** [comment] 2022-10-09 21:59
> OK. Good job on the images. Thanks for that.
> 
> I've replicated your settings and am getting results no problem, but there was something in your log that piqued my interest.
> 
> Try this please....
> 
> Turn off "Check Year Before Search" in Settings->Results->General.
> 
> Clear the Providers cache in Tools->Clear Databases & Clean Settings Files->Clear External Scrapers Cache. Also clear "Clear Internal Scrapers Cache".
> 
> Try a scrape of a Movie and see if it provides results now. Might be better to turn off autoplay so you can see the actual results in this test.

It works now! But can I do something to have this option on? Sometimes it's very helpful
![11FINAL](https://user-images.githubusercontent.com/112720004/194781404-fc69d489-d15c-4e96-b4a8-5c6a5c0277e3.png)

**Comment by Tikipeter** [comment] 2022-10-09 22:03
I need to find out what's wrong with it and fix it.

Did that Scooby Doo movie above not work before changing that setting?

If so, I'll use that to test. Otherwise, just give me 1 movie where there definitely were no results when the setting was enabled.

**Comment by Tikipeter** [comment] 2022-10-09 22:23
Will be fixed for next update.

Until then, do 2 things:
1. Make sure the setting is turned off.
2. Go to Tools->Clear Databases & Clean Settings Files and run "Clear IMDb Cache".

After next update you can turn the setting back on.

**Comment by unicornsandcandies** [comment] 2022-10-09 22:39
> I need to find out what's wrong with it and fix it.
> 
> Did that Scooby Doo movie above not work before changing that setting?
> 
> If so, I'll use that to test. Otherwise, just give me 1 movie where there definitely were no results when the setting was enabled.

Yes, Scooby Doo from screens above is good

**Comment by Nuklear92** [comment] 2022-10-10 01:58
The newly released animated Mortal Kombat movie is also having this issue when you have Check Year Before Scraping. 

Mortal Kombat Legends: Snow Blind

**Comment by Nuklear92** [comment] 2022-10-10 23:17
Just found another newly released Movie from Paramount+ that isn't being scrapped when having **Check Year Before Search** turned ON.

**Significant Other**

**Comment by Tikipeter** [comment] 2022-10-11 02:56
LOL, thanks Nuklear92 but not needed. It's already fixed for next update. :)

**Closed** 2022-10-11 10:36 UTC
Labels: bug, pending update
