### ISSUE TITLE
Trakt - HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out error

### ISSUE THREAD

**Issue by ronfrankhill** [Tikipeter/repository.tikipeter#549] opened 2021-08-20 22:41 UTC
By any chance you are getting a pop up in Fen TV progress section saying Fen trakt error https connection error. It might not be anything concerning Fen but on trakt.tv end. This is happen with the new update. Never was getting this before the update.

**Comment by Tikipeter** [comment] 2021-08-20 23:00
Trakt issue. Wait a day and report back if it hasn't sorted itself out.

**Comment by Tikipeter** [comment] 2021-08-20 23:01
MIGHT be worth re-authing Trakt. I wouldn't normally recommend anything like that, but for trakt specifically it has helped occasionally in the past. Not sure why, but it has.

**Comment by ronfrankhill** [comment] 2021-08-20 23:02
Okay. Thanks. I noticed it started happening right after the update. I reactivate the trakt but still getting that pop up.

**Comment by Tikipeter** [comment] 2021-08-20 23:20
* Go into My Accounts settings.
* Select "Revoke" to revoke the auth.
* Make sure you hit OK to save the settings.
* Open Fen settings.
* Go to Meta Accounts and click "(Re)Sync Fen settings with My Accounts.
* Make sure you hit OK to save the settings.
* Go back into My Accounts and authorize Trakt.
* Make sure you hit OK to save the settings.
* Open Fen settings.
* Go to Meta Accounts and click "(Re)Sync Fen settings with My Accounts.
* Make sure you hit OK to save the settings.

See if that solves it.

**Comment by Tikipeter** [comment] 2021-08-20 23:21
Also go to Tools->Clear Databases and Clean Settings Files and select "Clear Trakt Cache.

**Comment by ronfrankhill** [comment] 2021-08-20 23:42
Still getting the error issue. http connection pool

**Comment by Tikipeter** [comment] 2021-08-21 00:16
Do any trakt items work? Collection?

**Comment by ronfrankhill** [comment] 2021-08-21 02:56
I have tried twice in order to get In Progress TV Shows to work. Also In Progress Episodes. Don't mind the pop up comes up. Watched no pop up. Trakt Watchlists for TV and movies no issue. So only in Progress TV Shows and I n Progress Episodes still pop up is happening.

**Comment by KalAvroniev** [comment] 2021-08-21 13:59
I've been havng same issues. I even uninstalled Kodi and started fresh adding everything, the popup error still shows.
Sometimes due to the error Net Episodes and Progress become stuck and never load. I have to either go back and try again or restart the device to clear any stuck processes.

Sometimes episodes do not get marked as watched because of the error as well.

On another unrelated topic the new update removed a few settings which I used like Show release year for movies and shows, preemptive termination.

And the auto play next episode no longer works it either does not show at all or pops up after the episode has stopped playing and I'm back in the Episodes screen. When it shows after the video stops playing I have to hit Play Now to go to the next episode. Maybe related to - https://github.com/Tikipeter/repository.tikipeter/issues/544,

As a whole it feels like the new update has introduced a lot of breaks resulting in sometimes the addon becoming non responsive a lot of times it just gets stuck in loading and the Next Episodes screen does not load. Deleting the watched_status.db does not help as well. 

Could be related to the Tracked issue **Trakt Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv',**

**Comment by Tikipeter** [comment] 2021-08-21 15:13
The next ep autoplay issues wil be related to the trakt error issue.

Ill have to include some logging next update and then someone will have to make this error happen and supply me with a log.

**Comment by KalAvroniev** [comment] 2021-08-21 15:54
That can be done, I tried getting logs but could not see the error in it.

**Comment by Tikipeter** [comment] 2021-08-21 17:52
Are either of you using TMDb Helper as the player for these vids?

**Comment by ronfrankhill** [comment] 2021-08-21 18:03
No.

**Comment by Tikipeter** [comment] 2021-08-21 23:39
If anyone wants to test:

Go to Settings->General->Watched Indicators and set it to "Fen". Save the setting and open any TV Show list.

Then, go back into Settings->General->Watched Indicators and set it back to "Trakt".

See if that has any effect on fixing this issue.

**Comment by Tikipeter** [comment] 2021-08-22 00:54
Whilst browsing Issues of other addons, I came across this recent (2 days ago) issue for Seren:
https://github.com/nixgates/plugin.video.seren/issues/673

The log for that issue has the error involving trakt and `HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out`

This could well be another one of these trakt glitches that are affecting some users and not others.

**Comment by KalAvroniev** [comment] 2021-08-22 01:59
No TMDb Helper here also.
Removing Trakt for Watched indicator makes everything so much faster because it does not have to hit their API. 

One suggestion after looking at Trakt API docs, maybe change the URL from **api-v2launch.trakt.tv** to **api.trakt.tv**, based on https://trakt.docs.apiary.io/#introduction/api-url. Could be better load balanced.

Another thought, could it be related to the Trakt cache?

It is just very intermittent and error comes up very quickly to be a timeout. Could it have anything to do with Trakt's Rate Limits - https://trakt.docs.apiary.io/#introduction/rate-limiting (POST, PUT, DELETE calls are limited to 1 per second)

**Comment by Tikipeter** [comment] 2021-08-22 03:43
>One suggestion after looking at Trakt API docs, maybe change the URL from api-v2launch.trakt.tv to api.trakt.tv, based on https://trakt.docs.apiary.io/#introduction/api-url.

I will do that but both url's behave the same. It's not the problem.

>Another thought, could it be related to the Trakt cache?
Not unless your Trakt cache is malformed. To check, look at it's size. If it's 0kb then the tables have not been made correctly, and it will not be holding the info I cache to it.

>Could it have anything to do with Trakt's Rate Limits
Definitely not. The total movies watched and episodes watched info from trakt is only 2 calls to them (although I do also get info for hidden items as well when dealing with episodes). So that is only called when the current cache is expired, and it is first needed. After that there are no more calls to trakt to do with watched statuses, it's all cached already. The issue is if it doesn't get that info, then each page load it will try and get it again, causing the slowdown issues you're experiencing, plus the inaccessible lists that ronfrankhill is experiencing.

I, and I assume most others, are not having any issues with Trakt as we speak, so it's a bit of a mystery what's happening.

**Comment by derrgoo** [comment] 2021-08-22 03:47
> I've been havng same issues. I even uninstalled Kodi and started fresh adding everything, the popup error still shows.
> 
> Sometimes due to the error Net Episodes and Progress become stuck and never load. I have to either go back and try again or restart the device to clear any stuck processes.
> 
> 
> 
> Sometimes episodes do not get marked as watched because of the error as well.
> 
> 
> 
> On another unrelated topic the new update removed a few settings which I used like Show release year for movies and shows, preemptive termination.
> 
> 
> 
> And the auto play next episode no longer works it either does not show at all or pops up after the episode has stopped playing and I'm back in the Episodes screen. When it shows after the video stops playing I have to hit Play Now to go to the next episode. Maybe related to - https://github.com/Tikipeter/repository.tikipeter/issues/544,
> 
> 
> 
> As a whole it feels like the new update has introduced a lot of breaks resulting in sometimes the addon becoming non responsive a lot of times it just gets stuck in loading and the Next Episodes screen does not load. Deleting the watched_status.db does not help as well. 
> 
> 
> 
> Could be related to the Tracked issue **Trakt Error: HTTPSConnectionPool(host='api-v2launch.trakt.tv',**

Strange, I don't have these issues. Everything working fast and precise from trakt and fen. Doesn't seem as if new update effected any of my 5 devices adversely. I have seen better speed and like the next up switch to turn on or off. It seems as if this was big problem would possibly be more report showing up here. I don't play from TMDB a helper either. Just straight from fen which is the fastest method I think.

**Comment by KalAvroniev** [comment] 2021-08-22 09:20
Forgot to mention that episodes no longer get marked as watched as well. Must be related to the error.

**Comment by KalAvroniev** [comment] 2021-08-22 11:47
This error is making the Fen experience very frustraiting. Kodi has become virtually non usable because of this error. 
The interesting thing is the error is only observerd on PC and Mac installs. No issues so far on Fire TV stick.

**Comment by ronfrankhill** [comment] 2021-08-22 11:59
Last night l use Fen trakt movie watchlist. No issue on that end concerning pop ups etc. I haven't use Fen trakt TV watchlist but the issue is coming only In Progress TV Shows and ln Progress Episodes.

**Comment by KalAvroniev** [comment] 2021-08-22 12:24
> Last night l use Fen trakt movie watchlist. No issue on that end concerning pop ups etc. I haven't use Fen trakt TV watchlist to watch vids but the issue is coming only In Progress TV Shows and ln Progress Episodes. I am using a android TV box.

Those and Next Episode use Trakt API to get list of episodes/shows to watch and if trakt times out or errors the addon gets stuck in a limbo and it also seems like it is avoiding/bypassing the caching for those, it seems to be calling the API all the time when navigating in and out of those 3 areas (In Progress TV Shows/Episodes and Next Episodes).

Also disabling Trakt addon does nothing, issues remain.

**Comment by DaveP-kodi** [comment] 2021-08-22 22:00
Hi just to add a bit to this going from collection. Loads fine first episode marks as watched next and following episodes show error and no watch indicator. If I manually mark the episode as watched in trakt through context menu error will pop up but backing out and going back in shows it's marked. Verified the watch item in track website.
A few users in a group I'm in having same issues.
I Tested the above mentioned changing to fen and back to trakt, problem still remains. For now manually marking works. I remember seren had the same problem not marking episodes in the change from 18-19. Addon is still my goto manually marking is no problem but some people aren't noticing it. This is on a few Nvidia shield tv's and another android devices

**Comment by ronfrankhill** [comment] 2021-08-23 01:18
Now l can't get movies in trakt watchlist or TV progress shows to play. The files have been cached in the RD torrents section site but unable to play. I had no issue yesterday but tonight nothing is playing. The previous version of Fen was working perfectly. I don't know what is going on. I am still a loyal supporter of Fen.

**Comment by DaveP-kodi** [comment] 2021-08-23 01:32
> Now l can't get movies in trakt watchlist or TV progress shows to play. The files have been cached in the RD torrents section site but unable to play. I had no issue yesterday but tonight nothing is playing. The previous version of Fen was working perfectly. I don't know what is going on. I am still a loyal supporter of Fen.

I just booted up to check my end, movies watchlist is fine, show progress was taking a while to load I just canceled went to progress episodes worked fine. Went back and progress tv shows loaded. No update so your RD will be your end clear all cache reboot and try again is what I'd try.

**Comment by Tikipeter** [comment] 2021-08-23 04:45
I need this to be kept on the ONE topic of the `HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out` issue.
It doesn't help in any way to be listing obviously unrelated issues within this issue.

I posted an updated Fen with extra logging over 4 hours ago. If anyone wants me to have any chance of fixing this, they need to provide me with a log file. That MIGHT have something in it that will help. But, the issue is obviously coming from an inability to connect successfully with Trakt's API, at least for certain queries.

What might be a good idea is to try another addon and see if it behaves as expected, or in turn also has problems connecting to trakt. Venom would be a good candidate, as we share the same My Accounts dependency. But PLEASE DO NOT then go onto his github page and report the issue. Just come back here and let me know if it is working or not.

My biggest hurdle is that this issue is not happening for me. AT ALL. Trakt is working fine with no errors on multiple devices. I either need a log, or I need to be able to replicate the problem myself for there to be any chance of me fixing it. All the rest of this is just noise otherwise, and of no use at all towards fixing the issue.

**Comment by KalAvroniev** [comment] 2021-08-23 05:02
As per your advise I got the updated version with extra logs. I also enabled Debug, event and notification event loggin. I can  now see the error towards the end of the file. This is the section
`2021-08-23 14:54:38.599 T:1872     INFO <general>: ###error###: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=15.0)
2021-08-23 14:54:38.599 T:1872     INFO <general>: ###error get_watched_info_tv###: 'NoneType' object has no [kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7029256/kodi.log)ribute 'raise_for_status'
2021-08-23 14:54:38.604 T:1872    DEBUG <CAddonSettings[script.module.myaccounts]>: trying to load setting definitions from old format...
2021-08-23 14:54:38.606 T:6912    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2021-08-23 14:54:39.657 T:1872    DEBUG <CAddonSettings[script.module.myaccounts]>: trying to load setting definitions from old format...
2021-08-23 14:54:47.701 T:6912    DEBUG <general>: ------ Window Deinit (DialogNotification.xml) ------
2021-08-23 14:54:53.321 T:11136   DEBUG <general>: Thread JobWorker 11136 terminating (autodelete)
2021-08-23 14:54:53.322 T:5908    DEBUG <general>: Thread JobWorker 5908 terminating (autodelete)
2021-08-23 14:54:54.728 T:1872     INFO <general>: ###error###: HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=15.0)
2021-08-23 14:54:54.728 T:1872     INFO <general>: CPythonInvoker(20, C:\Users\Kal\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\fen.py): script successfully run`

Also file has been attached for review. Hope it helps
[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/7029259/kodi.log)

**Comment by Tikipeter** [comment] 2021-08-23 10:45
Don't create a separate issue. There's no point in noticing whether things like that work when you can't connect to trakt properly to get watched statuses. Many things won't work when that's the case, including next episode autoplay.

I can't look at that log now, but from the snippet you posted it doesn't look good for me providing a fix. The facts look to be unchanged - trakt is simply not responding in time to the call for watched status info. All i can do is make sure the call is made correctly, which it is, and then handle the data returned correctly, which it would be if data was returned at all.

At this point i don't see what i can do about this to be honest.

**Comment by Tikipeter** [comment] 2021-09-02 18:49
Anyone still experiencing this issue, or has it resolved itself?
I am still unable to replicate it. Trakt is working perfectly fine for me, and there has been nothing written here for 11 days.

**Comment by ronfrankhill** [comment] 2021-09-02 20:17
It has resolve itself. The pop up might show up once in a blue moon but nothing to worry about. I think it only shows up when it's taking to long to connect with trakt TV progress section but it still loads the data and fanart for users. Just my opinion.

**Comment by KalAvroniev** [comment] 2021-09-03 08:22
I still see it from time to time but not as often as before.

**Closed** 2021-09-03 09:59 UTC
Labels: bug

**Comment by KalAvroniev** [comment] 2021-09-04 06:37
I was able to force the issue by cleaning All Settings, Database and All Cache, especially Trakt. Then error starts comming up as before, on almost every call.

**Comment by Junkdewd** [comment] 2021-09-04 23:32
I'm sorry, Peter, but I was still having this issue as late as an hour ago.  

I haven't been able to participate due to being unable to upload a log.  I have vision issues, and have not had a person here to help until today.  

I uninstalled, cleared all data, and was going to fresh install, turn on debug, and upload if issue persisted, unfortunately, I get an error about tikiskins dependency installing the .06 repository, and an error, which I can't identify until my helper returns, when I try to use the master repo zip.  Please advise, and pardon lack of log for the moment, of how to possibly proceed.

**Comment by Traxtar928** [comment] 2022-02-14 00:15
I'm currently having this issue as well...
