### ISSUE TITLE
[Question] Forking FEN

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/repository.tikipeter#245] opened 2023-06-06 07:13 UTC
Hi,

If that’s ok to ask -

I manually added to FEN code a feature for my build users (https://github.com/Tikipeter/repository.tikipeter/issues/216)

Beside my code addition, nothing else has changed. All rest of FEN look & features are the same. 

I want to make it a FEN Fork with different addon name (“Twilight”) and custom icon. 

Beside changing the name in addon.xml, and fen_icon.png file, any other tips / requirements to keep it consistent?

Like changing “Fen” strings to “Twilight” in strings.po, or other stuff I didn’t think about. 

Thank you very much!

**Comment by Tikipeter** [comment] 2023-06-06 19:28
* Change addon id, name, icon, fanart and clearlogo.
* Change all instances of the fen logo being used throughout addon, including skin files and custom skin files.
* Change all instances of `plugin.video.fen` within addon.
* Change all instances of APIs within addon. TRAKT: `CLIENT_ID` and `CLIENT_SECRET`. TMDB: `tmdb_default_api`, FANART: `fanarttv_default_api` etc.
* Change all instances of `github.com` pointing to the Tikipeter repo throughout addon.
* Change ALL window property name strings within addon (these mainly start with `fen.` or `fen_`).
* Change all instances of `Fen`, `fen`, `FEN` within addon including, but not limited to, within the language file.
* Change icon path locations within `icons.py`.
* Change ALL user agent values.


Those are some specific things to look out for. The main thing you will need to do is search through the ENTIRE addon and change all instances of `fen` to `twilight`. That would get you 80-90% of the way there. Then just focus on the other important things mentioned above that weren't fixed by doing that.

Then you will need a repo set up for the custom colors zip file, and the custom skins zip file.

That's not going to be everything, but that's mostly what I can think of off the top of my head.

NONE of the forks of Fen that appeared when I shut it down last year did all the necessary changes, so they all had issues when Fen returned. Since I'm still here and you're attempting a fork, it will be important to be more thorough. You don't want changes I make to Fen to affect your fork because you haven't changed a property string to reference `twilight` instead of `fen` etc.

**Comment by TwilightMercy** [comment] 2023-06-07 03:12
Thank you so much.

**Comment by TwilightMercy** [comment] 2023-06-23 07:12
Hi Tiki,

I have question/suggestion, I've seen that some other people asked that in the past but trying my luck again -

Will you consider, in addition to `repository.tikipeter` that contains FEN .zip files, to create a GitHub repository `plugin.video.fen` that contains the code itself? Example of [skin.fentastic](https://github.com/ivarbrandt/skin.fentastic)

Reasons:

1. Allow for the people who likes to, in addition to reading FEN's changelog, read the changes in the code itself between versions.

2. Easier maintenance of FEN forks when fetching code changes from the original repository for addon updates.

**Comment by TwilightMercy** [comment] 2023-06-24 13:19
Hello dear Tikipeter,

I read `3.1.17` changelog and reading your words immediately made me sad and guilty for the anger you experience.
First of all, thousand of apologies for making this situation happen.

As you can see in this issue, forking FEN entirely indeed was in my planning, to run it as a separate and dedicated addon to my build - and that is the reason for this issue I've opened.

In addition, that's why I recently asked you about this: https://github.com/Tikipeter/repository.tikipeter/issues/245#issuecomment-1603797010 , to make the whole process easier and faster.

Unfortunately, It didn't happen yet, because my lack of time and knowledge to do it successfully, without screwing up things. I appreciate your [detailed instructions](https://github.com/Tikipeter/repository.tikipeter/issues/245#issuecomment-1579331114), and sorry that it didn't happen yet.

-----------------------------------------------------------------------------------------------------------------------------------------


**Anyway, let me give you some background:**

1. The build is managed through Telegram group named "Kodi + Real Debrid Israel":
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/cdfe6ba1-12b1-46aa-9a10-895fd710a344)

The goal of the build is to help less technical Israeli Kodi users, to install plug-and-play Hebrew build, connect their Real Debrid account, and have everything set up and ready. (Using FENtastic skin + dedicated Hebrew subtitles addon, etc..)

**Video demonstration:**
https://streamable.com/q30q9a

-----------------------------------------------------------------------------------------------------------------------------------------


2. The Telegram group does consist `5K` members, but according to real life experience and day-to-day giving help and support for users - my estimate that the number of the active build users is around 100-200, (unless of course there always some silent users that just install the build and use it without asking for any support).

While it is a nice number of users, in your opinion, does it count as large number? during the fact that `FEN` is worldwide known Kodi addon, and one of the best recommended by tons of users in reddit / other forums.

If that's OK to ask, did your API key's usage grow by a lot last month? do you see the growth historically for more than one month back? because nothing specific happened in my group the last month that isn't different from the other (almost a year) months until now.
Did your API Key usage reached a limit? (I'm not familiar with using it, but I assume it's no big deal to create my own.)

**That being said, that doesn't the change fact that I'm willing of course to do whatever is needed to help reducing your API Key usage, by forking FEN entirely in my build.**

-----------------------------------------------------------------------------------------------------------------------------------------

3. The build uses FEN as it's primary video addon for Real Debrid sources.

I'm using the original out of the box FEN version from your repository, but with the addition of "Hebrew Subtitles Matching to Sources" feature I've implemented into FEN code.

 Reference to past issue regarding this feature: https://github.com/Tikipeter/repository.tikipeter/issues/216 (only custom code addition)

-----------------------------------------------------------------------------------------------------------------------------------------

4. My plan to entirely fork `FEN` into `Twilight` addon was always the plan. But as a fast solution, would changing the API Keys for `TMDb `+ `Fanart.tv` in `FEN` settings inside the build will be enough? (or any more keys I've missed?)
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/2f3fbc50-56b7-43d8-aee4-0f4afda80f08)

-----------------------------------------------------------------------------------------------------------------------------------------

Thank you for everything and sorry again.. I'm here for anything needed to be done.

**Comment by TwilightMercy** [comment] 2023-06-24 13:35
Update:

I've created my own API Key in TMDb website, configured it in FEN settings, and it works

![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/2d966e9b-53db-4eaf-a53a-aab7f7e4524e)

**Comment by Tikipeter** [comment] 2023-06-25 00:40
>I read 3.1.17 changelog and reading your words immediately made me sad and guilty for the anger you experience.

I was more angry with the shenanigans that went on in that thread opened by one of your users. Posts were being deleted, and post counts were going up and down whilst I was at work and couldn't check constantly what was being posted. When I went to check the post count had changed again.

I've since calmed down, so I'm sure we can come to a reasonably easy solution.

>As you can see in this issue, forking FEN entirely indeed was in my planning

Now that I know you're running this build, that is true. I remember that issue post.

>Unfortunately, It didn't happen yet, because my lack of time and knowledge to do it successfully, without screwing up things. I appreciate your https://github.com/Tikipeter/repository.tikipeter/issues/245#issuecomment-1579331114, and sorry that it didn't happen yet.

The instructions were for what I thought would be a completely new addon, where you could write code and have complete independence from what I was doing with Fen. There are easier ways to achieve what I need to have happen in this situation.

>If that's OK to ask, did your API key's usage grow by a lot last month?

Doubled roughly over a period of approximately 2 months. I only have access to the last 1 month of usage at any one time.

>Did your API Key usage reached a limit?

No, there is no limit. 

>Reference to past issue regarding this feature: https://github.com/Tikipeter/repository.tikipeter/issues/216 (only custom code addition)

Plus the info line at the top of the window. :) That's mainly what I noticed.

==================================================================
THE ISSUE:

My main issue is builds have been targeted in the past by rights holders. Builds and IPTV services. Addons like Fen have NOT been targeted in the past. Assuming you are adequately protected against that happening, the issue for me is my addon will be bundled within that build. I don't want my tag name, which is of course included as the author of the addon, within a build. I also don't want my addons name associated with a build. The API key usage is secondary but was the catalyst to me knowing that something was amiss.

==================================================================
SOLUTION;

When you have enough time, describe for me what you do when you're ready to make a new version of your build, as it relates to Fen. I would assume you grab the latest available Fen, make the changes in code for your subtitle and top label features, add a Hebrew language folder, and then include it in your build. That about right?

After that I can make a solution for you that won't be much more different than what you are currently doing, and will keep us both happy.

**Comment by TwilightMercy** [comment] 2023-06-25 04:42
Good morning (in my TZ). I’ve read everything, but since I will be busy at work for most of the day I’ll will be able to fully reply in about 10-12 hours, sorry for the delay.

**Comment by TwilightMercy** [comment] 2023-06-25 09:44
> The instructions were for what I thought would be a completely new addon, where you could write code and have complete independence from what I was doing with Fen. There are easier ways to achieve what I need to have happen in this situation.

I see, maybe I wasn't clear enough when initially writing the issue. My goal was/is to keep using the original `FEN` addon, but only adding custom code addition for the feature implementation, while updating once in a while (about every 2-3 new versions) my custom "fork" with latest `FEN` version.

Not a completely new and independent addon.

> When you have enough time, describe for me what you do when you're ready to make a new version of your build, as it relates to Fen. I would assume you grab the latest available Fen, make the changes in code for your subtitle and top label features, add a Hebrew language folder, and then include it in your build. That about right?

> After that I can make a solution for you that won't be much more different than what you are currently doing, and will keep us both happy.

Exactly as you said, I'll add more specific details:
1. Grab latest `FEN` version from your repository.

2. Manually apply my code addition/changes to the following:

  - Add new directory `resources\lib\kodirdil` - contains all modules and functions for Hebrew subtitle search and source matching.
  - `resources\settings.xml` - Added new settings menu in settings window for the feature: (In Hebrew langauge).
  
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/6c020e1f-d82f-41f5-8bda-0e11eb8dd5dc)

  - `resources\language\resource.language.he_il\strings.po` - Add Hebrew language strings.po translation.
  - `resources\language\resource.language.en_gb\strings.po` - Add Hebrew language strings.po translation also to English language.
  - `resources\skins\Default\1080i\sources_results.xml` - Customize window (for top info line + sources "SUBTITLE" addition)
  - `resources\lib\modules\kodi_utils.py` - Code addition for the feature.
  - `resources\lib\caches\__init__.py` - Code addition for the feature.
  - `resources\lib\scrapers\external.py` - Code addition for the feature.
  - `resources\lib\windows\sources.py` - Code addition for the feature.

----------------------------------------------------------------------------------------------------------------------------------------

You can see full example of this process in the [following commits](https://github.com/kodi7rd/FEN-Hebrew-Subtitles-Match/commits/master): (updated `FEN` from 3.1.16 to 3.1.17 + applied extra code)


![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/ced387cd-04be-466c-b65c-2b017ed4ca30)


> Doubled roughly over a period of approximately 2 months. I only have access to the last 1 month of usage at any one time.

> No, there is no limit.

I see. I understand now that the API Key usage is secondary, and there's no limit at all. It was weird to me, because even though the large number of users for the small Israel country - I'm sure that out-of-the-box API Keys from `FEN` is being used worldwide with bigger numbers.

Anyway, it will be no problem for me at all to switch in the build (and for all users) to use my own API keys (for `TMDb`, `Fanart.tv`, `Trakt`).


> THE ISSUE:
> 
> My main issue is builds have been targeted in the past by rights holders. Builds and IPTV services. Addons like Fen have NOT been targeted in the past. Assuming you are adequately protected against that happening, the issue for me is my addon will be bundled within that build. I don't want my tag name, which is of course included as the author of the addon, within a build. I also don't want my addons name associated with a build. The API key usage is secondary but was the catalyst to me knowing that something was amiss.

First, let me explain how Kodi builds targeting by right holders is working specifically in Israel:

In Israel, there is an organization called "Zira", which acts to prevent/block any Kodi build / online websites / other applications + their respective Telegram community - that violates their rules by using/providing illegal content in their platforms.

Adding link to [Zira](https://he-m-wikipedia-org.translate.goog/wiki/%D7%96%D7%99%D7%A8%22%D7%94?_x_tr_sl=iw&_x_tr_tl=en&_x_tr_hl=iw&_x_tr_pto=wapp) Wikipedia page for more information. (There is no official English wiki page, so it's translated from Hebrew to English)

Also, If I may, adding a quote from your comment in the [Reddit post](https://www.reddit.com/r/Addons4Kodi/comments/14i6n8r/psa_from_the_latest_fen_update_3117_changelog/?utm_source=share&utm_medium=ios_app&utm_name=iossmf):

> The build contains IPTV as well as "normal" addons, so it not a good situation for an addon to be associated with it.

If that is your main issue with `FEN` being inside the build, I can assure you 100% that you have nothing to worry about, and `FEN` through the build, and the entire build is not targeted.

**Reasons:**

1. Generally, the build is dedicated only to Israeli & Hebrew users - with support and installation guides only from my Telegram group. It is not globally advertised outside of there or something.

2. The build consists 3 video addons:
`plugin.video.fen` - FEN
`plugin.video.youtube` - YouTube (for trailers through FEN)
`plugin.video.idanplus` - a VOD/IPTV Israeli addon called "Idan Plus" for Israeli content & channels.

**BUT** - "Idan Plus" addon is **100%** legal and free to use. "Idan Plus" is a legit and free digital television broadcasting service inside Israel. all of it's content is **100%** free to watch through the platforms:

- Idan+ TV Receiver
- Idan+ Android app
- "Idan Plus" Kodi addon.

Adding link to [Idan+](https://he-m-wikipedia-org.translate.goog/wiki/%D7%A2%D7%99%D7%93%D7%9F+?_x_tr_sl=iw&_x_tr_tl=en&_x_tr_hl=iw&_x_tr_pto=wapp) Wikipedia page for more information. (There is no official English wiki page, so it's translated from Hebrew to English)

Beside that, there is no and won't be, intention to add illegal IPTV addons. I don't want any troubles with Zira - explanation about their recent activity history:

The build exists for 10 months for now, and never been targeted by Zira - as opposed to other Telegram groups that were targeted and shut down just in the last 3 weeks:

- Israeli Kodi Telegram group + build with illegal and rights held Israeli content - `3K` members.
- Israeli Telegram group + Android application with illegal and rights held Israeli content - `7K` members.
- Israeli Telegram group to support illegal IPTV services and content - `2K` members.

**Comment by Tikipeter** [comment] 2023-06-26 18:57
_**IMPORTANT THINGS TO CHANGE:**_

1. `addon.xml`: Change the plugin name to "Twilight" and **replace my author name**.

2. `resources/media`: replace the 3 fen artworks with alternative artworks.

3. Remove link to Cocoscrapers in your repo `addons.xml`. The scrapers only update every few months at best anyway.

That'll be enough. Leave the API keys as is for now. As I said, the main thing is removing my name and addon name from the build. Even though the addon id is the same this will have to do. Fen will still be Fen, just with a different external name and icon etc.

Appreciate you taking the time to do this.

If you want some help on lowering the amount of files you have to edit update to update, let me know. I saw some things you could do to bring the number of Fen files needing editing down.

**Comment by TwilightMercy** [comment] 2023-06-26 19:43
> _**IMPORTANT THINGS TO CHANGE:**_
> 
> 1. `addon.xml`: Change the plugin name to "Twilight" and **replace my author name**. Leave the addon id as is.

addon + author name - No problem.
For addon id, I assume for forking `FEN` entirely to `Twilight`, changing addon id will also require dealing with the change in `FENtastic` skin (for it to call `plugin.video.twilight` instead of `plugin.video.fen`), thanks for considering it and making it easier.

-----------------------------------------------------------------------------------------------------------------------------------------

> 2. `resources/media`: replace the 3 fen artworks with alternative artworks.

No problem. just to make sure:
`fen_icon.png` - 512x512
`fen_fanart.png` - 1280x720
`fen_clearlogo.png` - 800x310

You've also stated in your first comment of this issue:
> Change icon path locations within icons.py

What about icons in this file that uploaded to imgur?
I've found there "fen" icon that the URL leads to:
https://i.imgur.com/IfNMnPJ.png
a small 180x180 FEN icon.

-----------------------------------------------------------------------------------------------------------------------------------------


> 3. Remove link to Cocoscrapers in your repo `addons.xml`. The scrapers only update every few months at best anyway.

I've noticed that it isn't getting updates frequently, but why would the direct link in my repo matters?
It serves as a dependency source when installing `FEN` / `Twilight` through my repo, otherwise the installation failed.
What is the reason for that?

-----------------------------------------------------------------------------------------------------------------------------------------

> That'll be enough. Leave the API keys as is for now. As I said, the main thing is removing my name and addon name from the build. Even though the addon id is the same this will have to do. Fen will still be Fen, just with a different external name and icon etc.

Are you sure about the API Keys? I created my own `TMDb` API key, only `Fanart.tv` and `Trakt` left. and it's no big deal to create those and replace in the code / settings.

-----------------------------------------------------------------------------------------------------------------------------------------

> If you want some help on lowering the amount of files you have to edit update to update, let me know. I saw some things you could do to bring the number of Fen files needing editing down.

I would be happy for any improvement / cleaning to my custom feature in the code. Thank you very much. Will it be OK if I'll open a separate issue for this matter / reopen past issue https://github.com/Tikipeter/repository.tikipeter/issues/216? (But not urgent now, after all the other work will be done.)



-----------------------------------------------------------------------------------------------------------------------------------------

As a side note, what do you think about my explanation regarding my build legal addons usage + Israeli target method? because honestly I think that you shouldn't be worried at all about `FEN` being in a build that isn't violating Israel right holders rules, hence it remains active until now (as opposed to other Israeli builds that got shut down)

**Comment by Tikipeter** [comment] 2023-06-26 21:12
>addon + author name - No problem.
For addon id, I assume that to fork FEN entirely to Twilight, changing addon id will also require dealing with the change in FENtastic skin (for it to call plugin.video.twilight instead of plugin.video.fen), thanks for considering it and making it easier.

Yes, that is correct. FENtastic code that related to Fen would need to change, which I don't think would have happened. Leaving the plugin id intact fixes that, as well as 100 other issues. If the plugin id changes, many more changes are needed within Fen. It's not ideal, but a name and icon change achieves a superficial fix that should be OK. If it bugs you that there'll be a different name within the addon on dialogs etc, you could change the fen strings in the `.po` file as well and that would take care of most instances within the addon. Some would slip through though and require a more thorough search.

>You've also stated in your first comment of this issue:
Change icon path locations within icons.py
What about icons in this file that uploaded to imgur?
I've found there "fen" icon that the URL leads to:
https://i.imgur.com/IfNMnPJ.png
a small 180x180 FEN icon.

That's OK. That was when I thought you wanted to make a complete, independent fork of Fen. I don't mind references/images to Fen withn the addon. Just the outward facing addon icon and name change will do.

>I've noticed that it isn't getting updates frequently, but why would the direct link in my repo matters?
It serves as a dependency source when installing FEN / Twilight through my repo, otherwise the installation failed.
What is the reason for that?

I'm not entirely sure why but the dev asked me to ensure that was done. I assume it's so there's not a link to that repo within a build's repo. If you include it in your repo then it will still install.

I thought the idea of builds was that users didn't have to install addons/dependencies? Isn't Cocoscrapers already within your bundled build?

>Are you sure about the API Keys? I created my own TMDb API key, only Fanart.tv and Trakt left. and it's no big deal to create those and replace in the code / settings.

Up to you, but it's secondary to me and not necessary. Plus, you will not be able to change the Trakt API without all users needing to re-auth their Trakt accounts.

>As a side note, what do you think about my explanation regarding my build legal addons usage + Israeli target method? because I honestly think that you shouldn't be worried at all about FEN being in a build that isn't violating Israel right holders rules, hence it remains active until now (as opposed to other Israeli builds that got shut down)

The problem is it's OK until it isn't. Whether your build falls within the law is neither here nor there. If they want to shut it down, they will shut it down. They'll just ruin you financially trying to win in court to keep it open. And sympathetic judges would likely rule against anyway.

>I would be happy for any improvement / cleaning to my custom feature in the code. Thank you very much. Will it be OK if I'll open a separate issue for this matter / reopen past issue https://github.com/Tikipeter/repository.tikipeter/issues/216? (But not urgent now, after all the other work will be done.)

Yep, open a new issue. I can include a couple of things in Fen, and there are a couple of modules in Fen that you will not need to change each time with minor adjustments to your code.

**Comment by TwilightMercy** [comment] 2023-06-26 21:44
> Yes, that is correct. FENtastic code that related to Fen would need to change, which I don't think would have happened. Leaving the plugin id intact fixes that, as well as 100 other issues. If the plugin id changes, many more changes are needed within Fen. It's not ideal, but a name and icon change achieves a superficial fix that should be OK. If it bugs you that there'll be a different name within the addon on dialogs etc, you could change the fen strings in the `.po` file as well and that would take care of most instances within the addon. Some would slip through though and require a more thorough search.

I actually just finished to make a FULL fork of `FEN` into `Twilight`, just to see if I succeed to follow the full instructions. it didn't took that long.

I replaced every instance of `fen` to `twilight`, `FEN` to `TWILIGHT` and `Fen` to `Twilight` in the code, including `plugin.video.twilght`, `fen.py` to `twilight.py`, icons, etc..

 If you want to take a look : )
[plugin.video.twilight-3.1.17.zip](https://github.com/Tikipeter/repository.tikipeter/files/11874266/plugin.video.twilight-3.1.17.zip)


I've ran in in Kodi and everything loads, works and looks good.

-----------------------------------------------------------------------------------------------------------------------------------------


The only things I skipped are:
1. API Keys (left untouched)
2. This:
> Then you will need a repo set up for the custom colors zip file, and the custom skins zip file.

I found this line, but left untouched because I don't use it at all:
`custom_skins_version_path = 'https://github.com/Tikipeter/custom_skins/raw/main/version.txt'`

-----------------------------------------------------------------------------------------------------------------------------------------


I did it just to try. but of course it will require more changes such as in `FENtastic` code in the build, other stuff. so I don't think I'll do FULL fork, only the specific things you've mentioned.


-----------------------------------------------------------------------------------------------------------------------------------------


> I'm not entirely sure why but the dev asked me to ensure that was done. I assume it's so there's not a link to that repo within a build's repo. If you include it in your repo then it will still install.
> 
> I thought the idea of builds was that users didn't have to install addons/dependencies? Isn't Cocoscrapers already within your bundled build?

Yes, `script.module.cocoscrapers` indeed is bundled with build, but I wanted to make FEN/Twilight addon (+ my custom feature addon) to be available to install manually in Kodi from my repo.

Can you check with him again about this? If he still wishes to, I will remove it of course.

And as other alternative, can I upload `script.module.cocoscrapers` itself to my repo, without a link to his GitHub repo?


-----------------------------------------------------------------------------------------------------------------------------------------


> Up to you, but it's secondary to me and not necessary. Plus, you will not be able to change the Trakt API without all users needing to re-auth their Trakt accounts.

Ok, I'll leave them the default keys for now. If you want it to be changed in the future, just tell me.



-----------------------------------------------------------------------------------------------------------------------------------------


> The problem is it's OK until it isn't. Whether your build falls within the law is neither here nor there. If they want to shut it down, they will shut it down. They'll just ruin you financially trying to win in court to keep it open. And sympathetic judges would likely rule against anyway.

I still think that won't happen in my case, because no illegal IPTV / Israeli content in the build. That's why I think you shouldn't be worried that `FEN` is bundled in the build. But as you wish all good : )

-----------------------------------------------------------------------------------------------------------------------------------------


> Yep, open a new issue. I can include a couple of things in Fen, and there are a couple of modules in Fen that you will not need to change each time with minor adjustments to your code.

Thanks, will do in the near future.

**Comment by Tikipeter** [comment] 2023-06-27 21:57
>And as other alternative, can I upload script.module.cocoscrapers itself to my repo, without a link to his GitHub repo?

Yes, I think that is what they want.

**Comment by TwilightMercy** [comment] 2023-06-28 10:24
> _**IMPORTANT THINGS TO CHANGE:**_

> 3. Remove link to Cocoscrapers in your repo `addons.xml`. The scrapers only update every few months at best anyway.

It is [done](https://github.com/kodi7rd/repository/commits/master).

**Comment by TwilightMercy** [comment] 2023-06-30 19:56
My fully forked "Twilight" addon with new artwork.

[plugin.video.twilight-3.1.17.zip](https://github.com/Tikipeter/repository.tikipeter/files/11920049/plugin.video.twilight-3.1.17.zip)

**Comment by TwilightMercy** [comment] 2023-07-01 07:35
![image](https://github.com/Tikipeter/repository.tikipeter/assets/29895680/23befe6d-a28e-4da3-b1d1-b748baa0695c)

**Comment by Tikipeter** [comment] 2023-07-09 22:24
Love the artwork,

If you change the `addon_id` like you have done, then the Fen specific features of the Fenstruary skin will not work. You would need to change them as well. You don't have to change that addon id if you don't want to.

**Comment by TwilightMercy** [comment] 2023-07-10 07:06
I changed them as well  to plugin.video.twilight (in FENtastic + Helper), everything works great and the same :)

**Closed** 2023-07-16 00:54 UTC
Labels: question

**Comment by TwilightMercy** [comment] 2023-07-18 04:39
All changes are done, no remnants of FEN inside my build - only Twilight addon. 
Glad that we worked it out and thank you very much for your help forking the addon. 

If anything will be needed to change in the future (ex: my own API keys, etc) just tell me
