### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by cabban** [Tikipeter/repository.tikipeter#120] opened 2020-01-29 15:41 UTC
When browse for subs fen and kodi not answering. Not crash only not answering and can't then use it kind regards

@Tikipeter

**Comment by Tinuz97** [comment] 2020-01-29 17:40
It sounds that you use kodi 18.5. (please provide more info like that: kodi version,Fen verion).
If you use 18.5 (now it is just guessing) ,use the Download option,not the search in kodi, this is a 18.5 bug that is causing the freezing.

**Comment by cabban** [comment] 2020-01-29 17:59
> It sounds that you use kodi 18.5. (please provide more info like that: kodi version,Fen verion).
> If you use 18.5 (now it is just guessing) ,use the Download option,not the search in kodi, this is a 18.5 bug that is causing the freezing.

Download option. Correct subtitle is not available. But browse works in exodus 8.6. . Shame it's not working in best addons fen 🤨

**Comment by Tikipeter** [comment] 2020-01-29 20:14
I don't think I'm understanding you both. The options for Fen's subtitles are "OFF, AUTO, SELECT". Are we talking about Fen's subtitles, Kodi's subtitles through a subtitle add-on or a combination of the two?

**Comment by Tinuz97** [comment] 2020-01-29 20:23
I personally think he is talking about subtitle Addons, because he did mention  browse, Fen only has off/auto/select like you did write above here.

That is why I mentioned 'use the download' option (for the addons like opensubtitles, subscene etc in kodi), because search is broken, and will kodi will be freezing, aka I think this ticket has nothing to do with Fen (working fine here).

**Comment by cabban** [comment] 2020-01-29 20:31
> I personally think he is talking about subtitle Addons, because he did mention browse, Fen only has off/auto/select like you did write above here.
> 
> That is why I mentioned 'use the download' option (for the addons like opensubtitles, subscene etc in kodi), because search is broken, and will kodi will be freezing, aka I think this ticket has nothing to do with Fen (working fine here).

You don't have to belive thank u for answering though.

**Comment by Tinuz97** [comment] 2020-01-29 20:34
We are trying to figure out what the issue is, but you lack Info (with all the respect).

Fen has no  browse for subtitles option as a example....

**Comment by cabban** [comment] 2020-01-29 20:34
> I don't think I'm understanding you both. The options for Fen's subtitles are "OFF, AUTO, SELECT". Are we talking about Fen's subtitles, Kodi's subtitles through a subtitle add-on or a combination of the two?

I try to explain once again When u tap subtitle u have options download compensation language and browse. When I tap browse to choose a subtitle from desktop . It has worked 1 time. Next times. It only freezing😥 and I need to close. I try in exodus no freeze . I can't send a video or do u have a email I can send bug video?😀

**Comment by cabban** [comment] 2020-01-29 20:36
> We are trying to figure out what the issue is, but you lack Info (with all the respect).
> 
> Fen has no browse for subtitles option as a example....

Kodi have same in all addons same settings to find manually pick subtitle. In fen it doesn't work but in exodus it does . And that's shame 😥

**Comment by cabban** [comment] 2020-01-29 20:37
> > We are trying to figure out what the issue is, but you lack Info (with all the respect).
> > Fen has no browse for subtitles option as a example....
> 
> Kodi have same in all addons same settings to find manually pick subtitle. In fen it doesn't work but in exodus it does . And that's shame

In general all videos has manually subtitle in all addons also in fen exodus venom.

**Comment by Tikipeter** [comment] 2020-01-29 20:42
What do you have as the setting for subtitles in FEN, cabban?

**Comment by cabban** [comment] 2020-01-29 20:50
> What do you have as the setting for subtitles in FEN, cabban?

Thank u 
Auto 
First language Swedish
Secondary language English😀

**Comment by Tikipeter** [comment] 2020-01-29 20:59
OK.  Make sure you have 'Show Searching Notification' in the subtitle section of FEN settings also turned on (just until we can find the problem).

What happens if you don't 'tap subtitle' when the video starts to play? Does FEN get the subtitles and start displaying them? If not, what does the notification say when it fails?

The point being, if you have FEN set to auto download and display subtitles, you are not meant to need to use Kodi's subtitle button to get them, FEN should be fetching them itself. The subtitle button visible during playback uses whatever subtitle addon/s you have installed, and is not anything to do with FEN.

There may be a problem with FEN fetching subtitles for you.

IMPORTANT FOR YOU TO TEST:
TRY LETTING FEN AUTO DOWNLOAD YOUR SUBS, AND REPORT BACK WHAT THE NOTIFICATION SAYS. DON'T CLICK ON ANY SUBTITLE BUTTON WHEN PLAYBACK STARTS. :) :)

**Comment by cabban** [comment] 2020-01-29 21:09
> OK. Make sure you have 'Show Searching Notification' in the subtitle section of FEN settings also turned on (just until we can find the problem).
> 
> What happens if you don't 'tap subtitle' when the video starts to play? Does FEN get the subtitles and start displaying them? If not, what does the notification say when it fails?
> 
> The point being, if you have FEN set to auto download and display subtitles, you are not meant to need to use Kodi's subtitle button to get them, FEN should be fetching them itself. The subtitle button visible during playback uses whatever subtitle addon/s you have installed, and is not anything to do with FEN.
> 
> There may be a problem with FEN fetching subtitles for you.
> 
> IMPORTANT FOR YOU TO TEST:
> TRY LETTING FEN AUTO DOWNLOAD YOUR SUBS, AND REPORT BACK WHAT THE NOTIFICATION SAYS. DON'T CLICK ON ANY SUBTITLE BUTTON WHEN PLAYBACK STARTS. :) :)

Yes it does works to fetch absolutely that is not the problem but not all movies has subtitles.I'm
Swedish also English . And the button browse has nothing with subs addons installed .tex I download a subtitle and want to use that specific one 
Or maybe translated a sub cause it not available in Swedish . Hope u understand now. 😀

**Comment by Tikipeter** [comment] 2020-01-29 21:29
I'm getting there with the understanding. :)

Are you saying this....

"You use FEN's subtitle auto download. Sometimes it doesn't work, or sometimes you have your own subtitles that you have already downloaded to use. When you have your own subtitles, or when FEN can't provide subtitles, you click on the subtitle button. When you click on 'Donwload Subtitle' or 'Browse for Subtitle' Kodi stops responding and you have to restart it. And this only happens when playing a video through FEN."

Please tell me if the above is correct and I will start trying to find out why...

**Comment by cabban** [comment] 2020-01-29 21:44
> I'm getting there with the understanding. :)
> 
> Are you saying this....
> 
> "You use FEN's subtitle auto download. Sometimes it doesn't work, or sometimes you have your own subtitles that you have already downloaded to use. When you have your own subtitles, or when FEN can't provide subtitles, you click on the subtitle button. When you click on 'Donwload Subtitle' or 'Browse for Subtitle' Kodi stops responding and you have to restart it. And this only happens when playing a video through FEN."
> 
> Please tell me if the above is correct and I will start trying to find out why...

Now u understood the issue 😀it's correct whole fen and kodi isn't responding when I browse for my downloaded or translated subtitles 😐

**Comment by Tikipeter** [comment] 2020-01-30 00:00
When you get a chance, turn FEN's subtitles to OFF, and see if it still freezes Kodi when browsing for subtitles yourself when playing a video from FEN. Then I'll be better able to decide what area of code I need to look into.

When I get a chance in a few hours, I'll try and replicate this issue myself by downloading some subtitles and try to browse to them when playing a video from FEN.

**Comment by cabban** [comment] 2020-01-30 13:44
> When you get a chance, turn FEN's subtitles to OFF, and see if it still freezes Kodi when browsing for subtitles yourself when playing a video from FEN. Then I'll be better able to decide what area of code I need to look into.
> 
> When I get a chance in a few hours, I'll try and replicate this issue myself by downloading some subtitles and try to browse to them when playing a video from FEN.

Yes it still freezes and not responding with settings subtitle off unfortunately 😀

**Comment by Tikipeter** [comment] 2020-01-31 01:58
I am still trying to get this to happen on my machine, cabban. So far, I haven't been able to replicate your issue. I am still trying, though. :)

**Comment by cabban** [comment] 2020-01-31 06:36
> I am still trying to get this to happen on my machine, cabban. So far, I haven't been able to replicate your issue. I am still trying, though. :)

Thank u , maybe it's only my mom's new laptop. I will try desktop and app from windows store 😀se if any difference

**Comment by Tikipeter** [comment] 2020-01-31 08:58
@cabban 

Even though I cannot make the freeze happen on my machine, I have included a setting for the next update that I want you to turn to OFF and see if it makes a difference. The setting will be "Force Enable Local Subs", and is found with the other subtitle settings in FEN (Settings->Playback->Subtitles)

The only thing FEN does when local subtitles are found is to automatically make sure they are turned on. The code for that was added a while ago, and it's the only thing I can think of that might cause you issues. This new setting gives you the chance to set it to OFF. See if it fixes your problem.

I'll still keep trying to make the freeze happen on my end in the meantime. :)

**Comment by cabban** [comment] 2020-01-31 10:23
> @cabban
> 
> Even though I cannot make the freeze happen on my machine, I have included a setting for the next update (v.1.5.93) that I want you to turn to OFF and see if it makes a difference. The setting will be "Force Enable Local Subs", and is found with the other subtitle settings in FEN (Settings->Playback->Subtitles)
> 
> The only thing FEN does when local subtitles are found is to automatically make sure they are turned on. The code for that was added a while ago, and it's the only thing I can think of that might cause you issues. This new setting gives you the chance to set it to OFF. See if it fixes your problem.
> 
> I'll still keep trying to make the freeze happen on my end in the meantime. :)

Thank u you are the best🏁😀

**Comment by cabban** [comment] 2020-01-31 15:48
@Tikipeter update i tested with setting force local
Subtitle off. 2 times its slow but no freeze 😀.  So maybe there is something there and to speed it up:-)  thank u for checking

**Comment by Tikipeter** [comment] 2020-02-01 06:14
That sounds promising. I will continue to look into this cabban.

**Comment by cabban** [comment] 2020-02-01 06:48
> That sounds promising. I will continue to look into this cabban.

Thank u 😀 great work . Much appreciated

**Comment by cabban** [comment] 2020-02-01 18:26
@Tikipeter Tiki

I deletet kodi and reinstalled, but now it stops responding every time when search for my subtitles, only on my computer in my bedroom :-)  it's very odd and strange issue §🤣

**Comment by Tikipeter** [comment] 2020-02-01 21:49
@cabban 

I know what the problem is and it's not good news.

When you hit Browse for the subtitles, Kodi first tries to load the location of where the file was found. So for an online stream it would be the url of the movie you are streaming. This causes kodi to freeze a lot of the time, but not ALL of the time, because many streaming urls will cause it to freeze.

For example, if I play a Real-debrid link, then the system will freeze when selecting browse for susbtitles, but if I play a Premiumize link it won't freeze because premiumize sends back an error 404 (not found) straight away.

This happened to me also with the Venom addon, so I am sure it is not a FEN specific problem.

To test this yourself, you would have to have a PM account active. Try to play a file from PM, and you will see that the browse feature now works.

Let me know if you get the same findings as me cabban......

**Comment by Tikipeter** [comment] 2020-02-01 23:03
I found a subtitle addon that will allow you to hit 'Download Subtitle' instead of 'Browse Subtitle' and then it let's you browse from the download subtitle dialog. It gets around the Kodi freezing issue.

The maker's github is here:
https://github.com/peno64/LocalSubtitle

and the download for the addon is here:
https://github.com/peno64/LocalSubtitle/raw/master/localsubtitle/service.subtitles.localsubtitle_1_2_0.zip

Install from zip on Kodi and it works well.

Here is what you see when you select 'Download Subtitles':
![screenshot000](https://user-images.githubusercontent.com/28930002/73600338-e065ae00-45a2-11ea-8acc-eb1729a7a13e.png)

And then when you click browse you get this:
![screenshot001](https://user-images.githubusercontent.com/28930002/73600342-eeb3ca00-45a2-11ea-8b4e-a59b18753c0a.png)


Before testing it, I went to Kodi's settings->Player->Language and in the subtitles section I changed 'Subtitle storage location' to 'Custom location' and then entered a 'Custom subtitle folder'. The subtitle addon then defaulted to this folder when it browsed for my sub. I also set this addon to be the default service for movies and tv shows.

**Comment by cabban** [comment] 2020-02-02 06:22
> @cabban
> 
> I know what the problem is and it's not good news.
> 
> When you hit Browse for the subtitles, Kodi first tries to load the location of where the file was found. So for an online stream it would be the url of the movie you are streaming. This causes kodi to freeze a lot of the time, but not ALL of the time, because many streaming urls will cause it to freeze.
> 
> For example, if I play a Real-debrid link, then the system will freeze when selecting browse for susbtitles, but if I play a Premiumize link it won't freeze because premiumize sends back an error 404 (not found) straight away.
> 
> This happened to me also with the Venom addon, so I am sure it is not a FEN specific problem.
> 
> To test this yourself, you would have to have a PM account active. Try to play a file from PM, and you will see that the browse feature now works.
> 
> Let me know if you get the same findings as me cabban......

Thank u for local addon it works :-) 
But strange browse subs works in exodus addon without delay or freeze 🤔

**Comment by davequattro** [comment] 2020-02-02 10:59
I have same problem with fen, i use  the addon Opensubtitles.org by Opensubtitles for ever now, and it has worked always with no problem also with fen, but since version, i believe 1.5.92 no more, i'll get ''error searching for subtitles". The settings in fen are blocking something, even when i select no subs in fen.
I was looking for problems on the web, so i get here, this problem is also in kodi 17.6 as in 18.5

**Comment by Tikipeter** [comment] 2020-02-02 13:47
@cabban I won't put "Exodus" on my system, I don't trust the developer. Have you got any other Exodus forks you use? Or, if you meant Exodus Redux, I am willing to put that on my system and check it. If you have Venom, could you try that one and see if it matches what I said about RD and PM?

@davequattro I'm looking into it.

**Comment by davequattro** [comment] 2020-02-02 13:48
Subscene.com and Addic7ed.com sub addons give me also errors only just in fen.
I'm Dutch, and only opensubtitles.com as subs provider is not enough, that site is not always on the air..
Subscene.com and Addic7ed.com has also good Dutch subs.
Podnapisi.net gives me no error in fen

**Comment by Tikipeter** [comment] 2020-02-02 13:58
@davequattro 
Your issue I will have fixed in the next update.

**Comment by cabban** [comment] 2020-02-02 14:27
> @cabban I won't put "Exodus" on my system, I don't trust the developer. Have you got any other Exodus forks you use? Or, if you meant Exodus Redux, I am willing to put that on my system and check it. If you have Venom, could you try that one and see if it matches what I said about RD and PM?
> 
> @davequattro I'm looking into it.

No I don't want you to but I try. But exodus is working to browse the others I don't know how to find 😀 I check thank u😀

**Comment by Tikipeter** [comment] 2020-02-02 14:30
@cabban 
I downloaded Exodus Redux, played a stream from RD, and as I suspected it froze Kodi and I had to shut it down after hitting browse subtitles. That's now Venom and Exodus Redux where this issue also happened. I'm going to try Seren in a minute.
You need to take notice of where the stream you are playing is coming from when trying to debug this situation. As I said, a stream from RD should ALWAYS cause this to happen. If that isn't the case with you, let me know the stream you tried that worked and I will try it too...

**Comment by cabban** [comment] 2020-02-02 14:39
> @cabban
> I downloaded Exodus Redux, played a stream from RD, and as I suspected it froze Kodi and I had to shut it down after hitting browse subtitles. That's now Venom and Exodus Redux where this issue also happened. I'm going to try Seren in a minute.
> You need to take notice of where the stream you are playing is coming from when trying to debug this situation. As I said, a stream from RD should ALWAYS cause this to happen. If that isn't the case with you, let me know the stream you tried that worked and I will try it too...

I tried venom no freeze 😀
Dark fate terminator. Ex

**Comment by Tikipeter** [comment] 2020-02-02 14:44
Let me know the link you tried in Venom i.e. which Hoster.
You don't use any premium services??

**Comment by cabban** [comment] 2020-02-02 14:46
> Let me know the link you tried in Venom i.e. which Hoster.
> You don't use any premium services??

Link 02 
And no 😀

**Comment by davequattro** [comment] 2020-02-03 15:54
> 
> 
> @davequattro
> Your issue I will have fixed in the next update.

I see that you fixed my problem, thanx for that!!!!

**Comment by cabban** [comment] 2020-02-04 15:54
@Tikipeter did u find anything😀

**Comment by Tikipeter** [comment] 2020-02-04 19:35
I've got a couple of clues to go on, but I haven't got anything sorted out yet. The problem is the Exodus forks all do the same freezing for me, but they don't seem to for you. So it's hard to pinpoint what a fix might be...

**Comment by Tikipeter** [comment] 2020-02-25 19:53
I've looked into this multiple times, and unfortunately I cannot provide a fix.
There was one method that did fix this issue, but it raised a couple of other even worse issues.
I'm sorry cabban. :( :(

**Closed by Tikipeter** 2020-02-25 19:53 UTC
Labels: possible bug

**Comment by cabban** [comment] 2020-02-26 19:55
Alles ok. 😀

tisdag 25 februari 2020 skrev Tikipeter <notifications@github.com>:

**Comment by peno64** [comment] 2020-04-01 19:28
@cabban , @Tikipeter 

I just read this thread about kodi freazing when you browse for a subtile. Tikipeter told:

"I found a subtitle addon that will allow you to hit 'Download Subtitle' instead of 'Browse Subtitle' and then it let's you browse from the download subtitle dialog. It gets around the Kodi freezing issue.

The maker's github is here:
https://github.com/peno64/LocalSubtitle

and the download for the addon is here:
https://github.com/peno64/LocalSubtitle/raw/master/localsubtitle/service.subtitles.localsubtitle_1_2_0.zip

Install from zip on Kodi and it works well."

I am the developer of this addon because I discovered this issue when I moved to kodi 18. I even reported the problem to the kodi developers but they didn't want to solve this problem because it only occurs in 'illegal' addons. According to me the problem only occurs starting from kodi 18 and not in kodi 17. Probably the issue will still be there in kodi 19.
I discovered this long before I used fen and as far as I know this is in all addons that stream content from scraped sites but as Tikipeter mentioned maybe only when using real debrid as I always do. It does for example does not happen when you play video's from youtube.

Anyway the problem is for sure not a specific fen issue.
