### ISSUE TITLE
Announcement: Testing Before Release....

### ISSUE THREAD

**Issue by Tikipeter** [Tikipeter/repository.tikipeter#65] opened 2022-10-27 03:01 UTC
Hi all.

There is new code in Fen that hopes to achieve a more "seamless" approach to playback. This will include a new full screen window when the source for playback is resolving, and that window will stay right up until "successful" playback has started. It will hopefully also mean a more seamless approach taken to autoplay next episode.

This means that "successful" playback needs to be monitored, and the playback of the video stopped manually and the next source tried if successful playback doesn't start within a certain period of time. Successful playback monitoring is something I have had in Fen in the past, but it did not seem to work well with Android systems (at least). They did not seem to like a python script manually calling for a stop to the playback, and would often hang.

In saying that, I really want this new approach to resolving added to Fen, so if some people could test the playback of files and whether they experience any hangs it would be beneficial before a wider release.

People with Easynews accounts and Android systems may experience the most issues, if any. But any system and provider combination will be valuable for testing.

If you want to test this build, here is what you will mainly be looking for:
* Does the "resolving" window appear in a timely fashion after selecting a source?
* Does the  "resolving" window stay visible right up until playback starts of the video?
* If a source is skipped due to unsuccessful playback, does your system freeze for an extended period of time, or become inoperable completely? (You can see the current source being resolved at the bottom of the "resolving" window. If it changes, then Fen is trying the next source)
* During Autoplay Next Episode, does the "resolving" window appear immediately after "Play" is selected?
* Did you encounter a situation where the playback was unsuccessful, and you were unable to close the "resolving" window?

Anyone who can test and report back with their findings will be very much appreciated. There's no need for log files, just explain what happened if there were any issues, or report back that everything seemed to work OK.

A couple of notes:
* If the "resolving" window becomes stuck on screen, it's possible your only recourse will be to restart Kodi/your device.
* It might be a good idea if you are a Trakt user, to switch to "Fen" as the Indicators Provider during testing, so as to not pollute your Trakt account with items that haven't really been watched. If you plan to test this during normal viewing, then of course this would not be needed.
* When this is installed via zip, you will lose the connection between Fen and the Tikipeter repo, meaning Fen will not automatically update from the repo anymore. To fix this, you need to reinstall Fen from the Tikipeter repo once you have finished testing this release.

Thanks to anyone who can test.

EDIT: Updated zip.
[plugin.video.fen-3.0.18s.zip](https://github.com/Tikipeter/repository.tikipeter/files/9879952/plugin.video.fen-3.0.18s.zip)

**Comment by ReaLx3m** [comment] 2022-10-27 14:09
Looks like its working fine in general, but there are some small quirks.
There are some half a second or so freezes(kodi blue busy wheel pops over the resolving window wheel) when initially trying to play the first link you clicked. 

Sometimes when playback  of the first source is unsucessful and it goes to the second one, and that one is succesfull, the video wont play straight away but the episodes list will be visible and black screen in the background for couple of seconds before playback starts. Sometimes playback will fail and you get returned to the episodes menu after that black screen.
Though i think ive seen that black screen before, and not really sure if its related to the new feature youre testing. I think it might be EN related.

Since i see it only tries a source once, and with EN as we know its common most of the time to play the same source after second try, and on more rare occasions on the third... Would it be possible for an option to be added to choose how many times should it retry before going to next source?
I think this would be preferable instead of going down to a lower quality source right away.

I will look around some more during the day, and share any new findings.

**Comment by ReaLx3m** [comment] 2022-10-27 16:03
> Thanks ReaLx3m.
> 
> Great job with the report back. Much appreciated. 🥇

No trouble at all, after all the work YOU have done, this is the least i can do :).

> Since Easynews in general is pretty problematic, we may unfortunately have to put up with any "small" quirks. I'm hoping for there to be no "large" quirks as it were. :)

What do you mean put up? Because of the convenience i was willing to ignore those 10-15 seconds freezes in the previous iteration of the feature before it got removed, so in current state looks like its miles ahead and nowhere near being called "putting up" haha.

> so I haven't really got anything to look through and copy ideas from.

Well somebody has to be first. Now we wait for people to start copying you and build on the idea/implementation, and then you copy back :)

**Comment by Projectal374** [comment] 2022-10-28 02:44
I am using it with the arctic horizon 2 skin and the text is getting clipped on the resolving window.

![20221027_125028_HDR](https://user-images.githubusercontent.com/116296903/198447212-f3eca6bd-8752-4b41-96b5-c70bdf8855ba.jpg)
![20221027_125937_HDR](https://user-images.githubusercontent.com/116296903/198447266-ff0ae90d-60ef-43cd-9a5f-ec2c3648e0b2.jpg)

I also noticed with my in progress movies/episodes, they start at the beginning for a sec then abruptly ff to the correct resume point. This didn't happen with 0.18.

Unrelated to the testing, more a feature request before next release if possible. Can you allow the Genre,Time,Decades folders to set independent viewtypes please. Doesn't seem possible with AH2 skin.

**Comment by ivarbrandt** [comment] 2022-10-28 08:35
I tested this with a NVIDIA Shield TV Pro running Android with Real Debrid as my service. Overall, I really like the new resolving window. Sometimes it is a little slow resolving movies but shows worked just fine. 

I took a few videos that combine movie/show resolving with/without autoplay and RD Cloud resolving or links straight from scraping. I have added these videos because I  want you to see exactly how the new resolver window runs on an Android system. You might be able to see things that I don't according to how you want the new window to function. I have also added specific observations/concerns to each section of videos.


**Movies - Full Scrape - Source Select (RD Cloud + Direct)**

https://user-images.githubusercontent.com/54084201/198538133-c43c4777-1306-4c67-b50a-1a62790d10da.mov

https://user-images.githubusercontent.com/54084201/198538943-9f8f8b36-8de2-4053-9513-f1d77a6e6c63.mov

For the most part, everything looks good here. The resolving window does close before playback starts though. It shows the list items of the menu item that I was in briefly before playback starts.


**Shows - Autoplay - (RD Cloud + Resume + Direct)**

https://user-images.githubusercontent.com/54084201/198539613-e6c692eb-6321-4436-bf9a-24fbc2fdee6e.mov

https://user-images.githubusercontent.com/54084201/198539680-ba211c2c-425c-4a97-9c82-c7cf05ed0efe.mov

https://user-images.githubusercontent.com/54084201/198539768-9773d324-053f-4ff7-9a28-3fe8064943f4.mov

Here I'm seeing the same thing as with movies where the item in the list you are currently in briefly pops up after the resolving window closes. Everything else looks and runs smooth.


**Shows - Next Episode (RD Cloud + Direct)**

https://user-images.githubusercontent.com/54084201/198541022-fc9a880a-7a53-4869-958d-6fc4a1af8ab4.mov

https://user-images.githubusercontent.com/54084201/198541061-343d76de-dc1c-4c9c-b1d3-e4fe5d04fa50.mov

https://user-images.githubusercontent.com/54084201/198541111-492f4c16-e521-4e1a-b30e-ceb09f88b232.mov

Again, same thing as mentioned above.

**Comment by IG2022** [comment] 2022-10-28 12:13
> Good job IG2022. Thanks for testing. 🥇
> 
> I'm going to update the zip file above, as there is a bug (unrelated to resolving) in the current one.

Not a problem! I've been using this for some time now and I haven't had any big issues. The only thing I noticed was that when resuming a movie or tv show the resume window comes in after the video has already started playing its that's not a huge deal but I thought I'd let you know.

Also, I've noticed a huge improvement in the scraping process especially when pre-scraping the RD cloud,  it's instant now whilst before it took a few seconds, thank you so much for improving this.

**Comment by jigoop1** [comment] 2022-10-28 12:16
it's work on firestick 4k even smoothly as expected given hardware limitations.

**Comment by Tikipeter** [comment] 2022-10-28 21:59
Projectal374
thanks for that report on the text height. I'll get that sorted. 🥇 

ivarbrandt
Wow! Great job on all the videos! You went above and beyond. 🥇 
Unfortunately your videos hold mostly bad news. :) That window should be staying right up until the video starts. Not good that it isn't ever happening for you. But, in saying that, at least there's no major issues.

IG2022
> The only thing I noticed was that when resuming a movie or tv show the resume window comes in after the video has already started playing

Yeah I needed to change it to that approach since I'm now waiting for the video to start before deeming a successful resolve. I'll probably find a better way to do it after the next release is finished. Maybe before. There's a couple of things stopping me using the old (better) method of resume playback.

jigoop1

🥇  Big thanks, as always, for pointing out a code error. I'll fix that before release too.

**Comment by MrC001** [comment] 2022-10-30 22:47
Only issue I had, after getting sources and playing one.  If i go back or stop it playing and try to play again it runs through all sources and errors out (auto-play) only way to get that show/movie to play again is go to a different one, play, stop and go back to the one I originally played.  Using premiumize.  Other then that .. very nice.

**Comment by Tikipeter** [comment] 2022-10-31 17:05
Thanks for the report MrC001.

>Only issue I had, after getting sources and playing one. If i go back or stop it playing and try to play again it runs through all sources and errors out (auto-play) only way to get that show/movie to play again is go to a different one, play, stop and go back to the one I originally played

I've not witnessed any of the behavior you've outlined above. There will be a release within the next few days, so hopefully thi behavior has been sorted out without having to reinstall.

>Still FEN error when try add uncached torrent to premiumize.

Also haven't seen this. Wait until after the next official release, and if it's still happening then unfortunately I'll need a log file that includes the error.

**Comment by jigoop1** [comment] 2022-11-01 13:27
@Tikipeter
hi i was playing with this and it look interesting 3D illusion. 
if you like to add in fen, here is the spinners.
```
<control type="image">
                <left>505</left>
                <top>0</top>
                <width max="100">auto</width>
                <height max="100">auto</height>
                <texture flipx="false" colordiffuse="FFE55E35">common/spinners/spin1.png</texture>
                <animation effect="fade" time="400" delay="400">Visible</animation>
                <!-- for spin.png <animation effect="rotate" start="360" end="0" center="auto" time="1200" loop="true" reversible="false" condition="true">Conditional</animation> -->
                <animation effect="rotatey" start="360" end="0" center="auto" time="1200" loop="true" reversible="false" condition="true">Conditional</animation>
                <animation effect="fade" start="0" time="1200" condition="true" pulse="true">Conditional</animation>
            </control>
```
[(https://user-images.githubusercontent.com/60192287/199242911-e219c7ab-5744-44b1-8287-29deeb130d55.png)]

**Comment by ivarbrandt** [comment] 2022-11-01 15:26
Not a problem. Glad I could help you test!

> That window should be staying right up until the video starts. Not good that it isn't ever happening for you. But, in saying that, at least there's no major issues.

Makes sense. It's not a big deal for me cause it still works lol.


On another note. I didn't know if I should make a separate issue for this but I decided not to. 
On this version, 3.0.18s, I'm getting a new error that I wasn't getting with 3.0.18. This is happening on my Nexus install.

This is only happening on a specific skin but it wasn't happening on that skin with version 3.0.18 so I'm not sure if the error is being caused by Fen or the skin. I have attached the log for your viewing pleasure.

[kodi.log](https://github.com/Tikipeter/repository.tikipeter/files/9911638/kodi.log)

**Comment by Tikipeter** [comment] 2022-11-02 01:11
ivarbrandt, how many movies were in your In Progress list, what did you have set for items per page, and on what page did the error occur?

**Comment by ivarbrandt** [comment] 2022-11-02 03:40
> how many movies were in your In Progress list

0

> what did you have set for items per page

50

> on what page did the error occur

The error didn't occur inside a list, it occurred inside a custom shortcut folder. I have two shortcut folders, one for movies and one for shows. This error is frequently occurring when I open my movies shortcut folder.

**Comment by Tikipeter** [comment] 2022-11-02 04:31
I removed the try/except wrapper (which makes errors silent) for the Movie and TV Show code for the testing zip. It sounds as if the skin is trying to pre-fetch the contents of each list item and failing on In Progress because you have nothing to show for there. Normally that won't invoke an error, but it will when there is no try/except wrapping the code.

Install this zip and see if it still occurs...

[plugin.video.fen-3.0.18y.zip](https://github.com/Tikipeter/repository.tikipeter/files/9915936/plugin.video.fen-3.0.18y.zip)

**Comment by ivarbrandt** [comment] 2022-11-02 07:51
> It sounds as if the skin is trying to pre-fetch the contents of each list item

Yes as far as I know this is correct because the skin uses embedded lists.

I tried that zip and all the errors went away. I can also now access my In Progress even though it is empty.

So what do I do with this information? Do I talk to the skin developer and mention what you said above about the try/except wrapper?

**Comment by Tikipeter** [comment] 2022-11-02 07:58
You won't need to do anything about this.

The try/except will always be there around the movie/show lists. I just removed it for this test zip so any errors would show in a log if needed.

Chalk it up to unintended consequences of doing that. Coupled with skins being more adventurous these days.

**Comment by ivarbrandt** [comment] 2022-11-02 09:26
Ok but if I don't do anything and you put the try/except back in, then are the errors are likely to come back?

And I just have to ignore them?

**Comment by Tikipeter** [comment] 2022-11-02 20:48
The error won't come back. The try/except *basically* makes python ignore the errors. Or more accurately you won't see them happen. This batch of code is designed that way: for the error to happen, but you not see it and python not report it.

**Comment by ivarbrandt** [comment] 2022-11-02 22:12
Oh ok I understand. Thank you for the clarification.

**Comment by Tikipeter** [comment] 2022-11-03 00:01
Well I couldn't leave this well enough alone, and have made a bunch of changes. Including of course things that were pointed out to me here.

I appreciate you all for helping test for me. Hopefully a new release will come tomorrow, and this will work as intended.

Fingers crossed.

**Comment by IG2022** [comment] 2022-11-03 02:24
> Well I couldn't leave this well enough alone, and have made a bunch of changes. Including of course things that were pointed out to me here.
> 
> I appreciate you all for helping test for me. Hopefully a new release will come tomorrow, and this will work as intended.
> 
> Fingers crossed.

Looking forward to the new release and seeing the changes made!

**Closed** 2022-11-03 17:18 UTC

**Comment by MrC001** [comment] 2022-11-03 18:29
Sounds like me.....with anything.

**Comment by JFG1000** [comment] 2022-11-21 23:14
@Tikipeter just been reading these comments and can also confirm my window results window doesn't also stay up all the way til playback like @ivarbrandt, is this something that your able to adjust? Thanks for your hard work
